### ISSUE TITLE
How to do movie volume increase and decrease with using mobilevlckit for swift?

### ISSUE THREAD

**Issue by dimsancing2015** [librariesio/libraries.io#1017]
I used mobilevlckit in my project. Have mobilevlckit any other features code like movie volume increase , decrease  and skip next chapter . This is my first time to use mobilevlckit with swift.

**Comment by andrew** [comment]
This isn't the issue tracker for MobileVLCKit, you'll need to reopen your issue here: https://code.videolan.org/videolan/VLCKit/issues
