### ISSUE TITLE
The impact of civic technology 

### ISSUE THREAD

**Issue by BenJam** [librariesio/libraries.io#1019]
I would like to present an idea for TICTec 2017 which looks at the impact of civic technology at a level *below* that of what is already established as 'impactful' civic tech. My goal here is to expose which projects — specifically those that lack financial support — should be the subject of more attention in 2017 and beyond. 

For each of the projects below I would like to understand the libraries that are used by all/most of these applications: 

### FOI-related sites
Alaveteli https://github.com/mysociety/alaveteli
MuckRock https://github.com/MuckRock/muckrock
FragDenStaat https://github.com/okfde/fragdenstaat_de

### Mapping
FMS https://github.com/mysociety/fixmystreet
SeeClickFix https://github.com/SeeClickFix/dev.seeclickfix.com
Melbourne Urban Forest https://carto.com/gallery/melbourne-urban-forest/ (https://github.com/CartoDB/cartodb)
Ushahidi https://github.com/ushahidi/Ushahidi_Web
LargeLots https://github.com/datamade/large-lots-staging

### Parliamentary sites
TWFY https://github.com/mysociety/theyworkforyou
GovTrack https://github.com/govtrack/govtrack.us-web
PRS Legislative http://www.prsindia.org/ no idea about the code
Democracy Club https://github.com/DemocracyClub/WhoCanIVoteFor

### Others
Loomio https://github.com/loomio/loomio
RecordTrac https://github.com/codeforamerica/recordtrac

**Comment by andrew** [comment]
@BenJam do you have a date that this needs to be done by?

**Comment by BenJam** [comment]
I am going to start writing the application to speak today, it is due in the 30th of Jan, I will pull the idea if nothing interesting pops out :)

**Comment by andrew** [comment]
Here's the list of repos as they are indexed by libraries.io:

- https://libraries.io/github/mysociety/alaveteli
- https://libraries.io/github/MuckRock/muckrock
- https://libraries.io/github/okfde/fragdenstaat_de
- https://libraries.io/github/mysociety/fixmystreet
- https://libraries.io/github/SeeClickFix/dev.seeclickfix.com
- https://libraries.io/github/CartoDB/cartodb
- https://libraries.io/github/ushahidi/Ushahidi_Web
- https://libraries.io/github/datamade/large-lots-staging
- https://libraries.io/github/mysociety/theyworkforyou
- https://libraries.io/github/govtrack/govtrack.us-web
- https://libraries.io/github/DemocracyClub/WhoCanIVoteFor
- https://libraries.io/github/loomio/loomio
- https://libraries.io/github/codeforamerica/recordtrac

Will make sure they are all synced up and have their dependencies properly parsed

**Comment by andrew** [comment]
Interestingly https://github.com/SeeClickFix/dev.seeclickfix.com, https://github.com/DemocracyClub/WhoCanIVoteFor and https://github.com/govtrack/govtrack.us-web don't seem to have a license for the code 😱

**Comment by andrew** [comment]
Three of those projects don't use any kind of files to list their dependencies, instead list them in the readmes

- https://libraries.io/github/ushahidi/Ushahidi_Web
- https://github.com/datamade/large-lots-staging
- https://github.com/govtrack/govtrack.us-web

Libraires.io couldn't find any dependencies for https://github.com/DemocracyClub/WhoCanIVoteFor d but it definitely has some in requirements/production.txt so there's a bug to investigate

**Comment by andrew** [comment]
Fixed dependencies on https://libraries.io/github/DemocracyClub/WhoCanIVoteFord so here's the ones we can analyse automatically:

- https://libraries.io/github/mysociety/alaveteli
- https://libraries.io/github/MuckRock/muckrock
- https://libraries.io/github/okfde/fragdenstaat_de
- https://libraries.io/github/mysociety/fixmystreet
- https://libraries.io/github/SeeClickFix/dev.seeclickfix.com
- https://libraries.io/github/CartoDB/cartodb
- https://libraries.io/github/mysociety/theyworkforyou
- https://libraries.io/github/DemocracyClub/WhoCanIVoteFor
- https://libraries.io/github/loomio/loomio
- https://libraries.io/github/codeforamerica/recordtrac

**Comment by andrew** [comment]
@BenJam I can't see there being a lot of crossover between the python and ruby projects, but we can definitely look for the most popular in the 5 rubygems ones and the 4 python ones.

I'm sure we can also manually find the javascript libraries that are used across most of those without any kind of package manager

**Comment by andrew** [comment]
Initial findings:

Ruby: https://gist.github.com/andrew/1aeda55731b6f4db899c3a6d0042047e

```
Rubygems/rake (4)
Rubygems/rack (4)
Rubygems/nokogiri (4)
Rubygems/builder (4)
Rubygems/multi_json (4)
Rubygems/sass (4)
Rubygems/ffi (4)
```

Python: https://gist.github.com/andrew/541e445b2377aecda0317330bc0d04b3

```
Pypi/psycopg2 (4)
Pypi/gunicorn (4)
Pypi/requests (4)
```

**Comment by andrew** [comment]
Working on https://github.com/librariesio/libraries.io/issues/909 so we can easily calculate the full dependency tree for a repository

**Comment by BenJam** [comment]
So it looks like the sample size is a little small. So how about we look at it from a organisational level? I think if we look at all FOSS code produced by known Civic Tech groups we might find something more interesting. Cross checking with the Knight Foundation's list https://twitter.com/CivicNinjas/lists/knight-civictech/members  this means:

mySociety
DemoClub
OpenNorth
Gov.uk
18F
FCI
Code for America
Open Knowledge
MuckRock
Ushahidi
DataMade
Loomio
Wikimedia
(parts of) the World Bank
ManaBlas

Are there any that we’re missing or should look into @rebeccarumbul ?

**Comment by andrew** [comment]
Sounds good, just need to dig out the github orgs for each of those groups

**Comment by BenJam** [comment]
I can do that!

**Comment by BenJam** [comment]
Updated with links to GH repos.

**Comment by andrew** [comment]
Just running the [rake](https://github.com/librariesio/libraries.io/blob/912f46ee6f3f3ef428fa2bafcd722cb68f0231ef/lib/tasks/research.rake) task now, there's 4000+ repos across all those orgs, might take a little while, will dump the result to a gist

**Comment by BenJam** [comment]
Tak!

**Comment by andrew** [comment]
~5600 unique dependencies across all those repos, most popular 25: 

```
NPM/grunt (296)
Rubygems/rake (286)
NPM/grunt-cli (243)
NPM/grunt-jsonlint (227)
NPM/grunt-banana-checker (220)
Rubygems/json (212)
Rubygems/sass (196)
Rubygems/multi_json (182)
Rubygems/nokogiri (179)
Rubygems/rails (176)
Rubygems/i18n (172)
Rubygems/minitest (167)
Rubygems/rack (158)
Rubygems/thor (157)
Rubygems/safe_yaml (157)
Rubygems/activesupport (156)
Pypi/requests (155)
Rubygems/mime-types (153)
Rubygems/tzinfo (146)
Rubygems/uglifier (145)
Packagist/jakub-onderka/php-parallel-lint (144)
Rubygems/execjs (143)
Rubygems/ffi (140)
Rubygems/diff-lcs (139)
NPM/mocha (138)
```

https://gist.github.com/andrew/b055fe66ca7c0c6e3eab17a0cb5f1198

n.b. that doesn't resolve transitive dependencies itself but they'll be in the lockfiles for ruby and php projects, that means there's probably some transitive node projects that are lurking behind the surface, can dig them out but it'll take a day or so of work.

**Comment by BenJam** [comment]
*very* interesting, thanks.

**Comment by BenJam** [comment]
Should know by 23rd Feb whether accepted.

**Comment by BenJam** [comment]
Talk *accepted* hoping that we can put together a paper alongside a talk.

**Comment by andrew** [comment]
cc @camillem

**Comment by BenJam** [comment]
Questions that I think will have interesting answers?

### Definitions

* we define 'civic tech' as any of the 4,551 projects 'owned' by one of the fifteen orgs above for which sourcecode is available on GitHub, GitLab or BitBucket (in reality everyone is on GitHub) plus the 5,706 dependencies of any of those projects, of which we have data for 4,646. 
* we define 'civic tech community' as anyone who has committed to any project owned by any of the 
fifteen orgs above.
* we define 'digital infrastructure' as the top 1,000 most depended upon projects amongst the 23m repositories that Libraries.io tracks. 

### Which projects do we currently consider as 'digital infrastructure'?

### How many of these projects underpin the civic tech community?

### Were any of these projects created within the civic tech community?

### How much value is extracted from these projects by the civic tech community?

### How much value is injected back to these projects from within the civic tech community?

### Are there particular projects that lack attention that this community could support? (i.e. where are the risks)

### How best can the civic tech community support these projects?

### How best can these projects support themselves?

**Comment by andrew** [comment]
CII projects without repos to be updated: https://github.com/librariesio/libraries.io/issues/1370

**Comment by BenJam** [comment]
closing this ticket for now, I'll link through to a follow up blog post.
