### ISSUE TITLE
Support Puppet Forge

### ISSUE THREAD

**Issue by petems** [librariesio/libraries.io#1026]
Add libraries.io support for the Puppet Forge

URL: https://forge.puppet.com/modules?utf-8=%E2%9C%93

API Documentation: https://forgeapi.puppetlabs.com/#!/module/getModule

**Comment by petems** [comment]
@andrew Is there a rough pointer on how to add a new package type? Like what rake tasks I need to create the new objects and stuff? Wouldn't mind trying to implement this myself if I get some slack time :

**Comment by andrew** [comment]
@petems most of the code to add a new package manager is adding a new class to this folder: https://github.com/librariesio/libraries.io/tree/master/app/models/package_manager

Rubygems is a good example of some of the functions that need to be implemented: https://github.com/librariesio/libraries.io/blob/master/app/models/package_manager/rubygems.rb

**Comment by andrew** [comment]
This has shipped now 🎉

**Comment by petems** [comment]
Thanks to @andrew and @garethr for getting this done, super cool! 👍
