### ISSUE TITLE
Document how to add support for a new package manager

### ISSUE THREAD

**Issue by andrew** [librariesio/libraries.io#1031]
Make it easier for anyone to contribute support for a new package manager by describing the steps involved and where to add code, perfect for: https://github.com/librariesio/libraries.io/issues/1026

Fixes https://github.com/librariesio/documentation/issues/9

**Comment by BenJam** [comment]
so much this. 👍

**Comment by andrew** [comment]
Fixes https://github.com/librariesio/documentation/issues/9
