### ISSUE TITLE
Add Crystal docs links

### ISSUE THREAD

**Issue by andrew** [librariesio/libraries.io#1034]
https://crystal-docs.org/ by @barisbalic, 

Example: https://crystal-docs.org/will/crystal-pg/

n.b doesn't support versions yet

**Comment by flyinggrizzly** [comment]
The https://crystal-docs.org URLs are returning 50x errors. Should this issue be update to link to https://crystal-lang.org/docs/ instead?

**Comment by andrew** [comment]
@flyinggrizzly the docs from https://crystal-docs.org covered all the different crystal libraries rather than crystal-lang itself.

I'm going to close this as the app is still broken.
