### ISSUE TITLE
Login with GitLab

### ISSUE THREAD

**Issue by andrew** [librariesio/libraries.io#1039]
Dependent on https://github.com/librariesio/libraries.io/issues/1040

Omniauth plugin for gitlab: https://github.com/linchus/omniauth-gitlab

**Comment by royka** [comment]
I guess eventually will want to be able to connect accounts too, i.e. login with github then connect a gitlab account

**Comment by andrew** [comment]
Yep 👍

**Comment by andrew** [comment]
🚢

**Comment by andrew** [comment]
@samjacobclift opened a separate issue for linking accounts: https://github.com/librariesio/libraries.io/issues/1074
