### ISSUE TITLE
Support cpanfile and cpanfile.snapshot

### ISSUE THREAD

**Issue by andrew** [librariesio/libraries.io#1049]
TIL via https://github.com/librariesio/libraries.io/issues/1019 that Perl has more ways of specifying dependencies, namely `cpanfile` and `cpanfile.snapshot` using https://github.com/perl-carton/carton, we should add support to https://github.com/librariesio/librarian-parsers and https://github.com/librariesio/bibliothecary for them.

Example files:

- https://github.com/mysociety/fixmystreet/blob/master/cpanfile
- https://github.com/mysociety/fixmystreet/blob/master/cpanfile.snapshot

More details on spec: https://metacpan.org/pod/cpanfile

**Comment by andrew** [comment]
Moving this to the [Backlog](https://github.com/librariesio/libraries.io/blob/master/Backlog.md) as we'd still like to implement it but can't see that happening in the near future.

**Comment by zmughal** [comment]
I can help implement this. Would I need to submit against bibliothecary? The simplest approach would be to use [`Module::CPANfile`](https://metacpan.org/pod/Module::CPANfile) and [`Carton::Snapshot::Parser`](https://metacpan.org/source/Carton::Snapshot::Parser) from CPAN. These can be put in scripts that are called.
