### ISSUE TITLE
Displaying wrong profile

### ISSUE THREAD

**Issue by gautamkrishnar** [librariesio/libraries.io#1050]
I am using libraries.io and logged in using github, it is displaying my profile as https://github.com/kdubya050: 

My actual profile is: https://github.com/gautamkrishnar

![screenshot 265](https://cloud.githubusercontent.com/assets/8397274/21716692/012fdf06-d432-11e6-889f-2628fa26cec7.png)

**Comment by andrew** [comment]
@gautamkrishnar thanks for reporting, fixed in https://github.com/librariesio/libraries.io/commit/6a1a50a00a4f6d0687f9f37afb6ec6cb5b8bd85f
