### ISSUE TITLE
page to remove from libraries.io

### ISSUE THREAD

**Issue by brondou** [librariesio/libraries.io#1063]
I would it be possible to remove the following page on your portal?
https://libraries.io/github/brondou/ENTSOE-OPDM
The repository does not exitst and I do not longer to be referenced.

kind regards
Bart Rondou

**Comment by andrew** [comment]
I've removed that for you now, thanks for letting me know

**Comment by brondou** [comment]
Hi Andrew

Thanks for the fast response.
Can the reference be removed as well on this page?
https://libraries.io/maven/org.apache.servicemix.bundles:org.apache.servicemix.bundles.elasticsearch

kind regards

**Comment by andrew** [comment]
@brondou should be gone now

**Comment by brondou** [comment]
Hi Andrew

Thank you very much.

Bart Rondou
