### ISSUE TITLE
Allow linking your GitHub/Gitlab/Bitbucket accounts together

### ISSUE THREAD

**Issue by andrew** [librariesio/libraries.io#1074]
Now that we have https://github.com/librariesio/libraries.io/pull/1046, we should allow a logged in user to connect all their accounts together from the account section so they can eventually build up a mega-profile

**Comment by samjacobclift** [comment]
Can people connect as many accounts as they would like?

**Comment by andrew** [comment]
@samjacobclift oh, interesting, I didn't think of that, I don't see why not

**Comment by samjacobclift** [comment]
PR for the luz :) https://github.com/librariesio/libraries.io/pull/1075
