### ISSUE TITLE
Regular open source usage emails for maintainers

### ISSUE THREAD

**Issue by andrew** [librariesio/libraries.io#1078]
As a maintainer of open source libraries I find it helpful to see who and how people are using my software so that I can make better decisions about future changes and support existing users better.

Libraries.io currently surfaces more information about open source usage than any other platform but it's still a chore to dig through the lists of dependent projects looking for new and interesting ones.

I'd like to receive a regular email highlighting new and interesting open source libraries and applications that depend on libraries I contribute.

Some interesting data points:

- New dependent libraries that are built on top of my libraries
- New dependent applications that use my libraries
- Projects that have stopped depending my libraries recently
- Related/alternative libraries that have been released recently
- Libraries that are often used alongside my libraries
- Community metrics like stars, contributor counts, open issues/prs, issue/pr response rate
- Suggestions of things to fix, missing license, lack of changelog entry etc

Any other data points that maintainers would like to have surfaced for them that I've missed?

**Comment by Turbo87** [comment]
@andrew this might be fixed already, but last I looked the dependent projects list included quite a few project forks next to the forked project which was hiding other projects. maybe forked projects should be made less important in that list?

**Comment by andrew** [comment]
@Turbo87 if you have an example link I can fix that up quickly if it's not already

**Comment by Turbo87** [comment]
@andrew I'll let you know when I run into it again. Thanks for your work on this project!

**Comment by Turbo87** [comment]
@andrew coming back to the actual content of this issue: I personally don't necessarily need to receive these things via email, but it would be awesome to have these in some sort of news stream on the webpage which could then be aggregated for the emails once per week

**Comment by andrew** [comment]
From @yoshuawuyts on twitter: 

> uptake in usage is a fun one. Being notified if folks revert / pin versions could be critical as it signals poss. semver breakage

**Comment by ncoghlan** [comment]
Pulling the downstream redistributor mappings from release-monitoring.org (when available - libraries.io currently covers more projects and software publishing platforms than r-m.o)

**Comment by mrjoelkemp** [comment]
Would love to know my most popular projects ranked by stars and/or downloads. Would also love to know when a project spikes or drops in downloads (kind of like a top winners/losers for the day/week).

**Comment by willingc** [comment]
An easy way to determine what linux flavors/versions support our dependencies.

**Comment by willingc** [comment]
Finding the https://github.com/librariesio/org-pulse report a useful weekly report. A way to aggregate info from multiple orgs easily would be nice info to have.

**Comment by buger** [comment]
Information about forks activity: how many forks with custom commits and what the changes are (at least link to changeset)

**Comment by KrauseFx** [comment]
A list of the most active contributors, so you can start granting push access to those people.

**Comment by hzoo** [comment]
> A list of the most active contributors, so you can start granting push access to those people.

@KrauseFx Doesn't directly give you the answer but I created https://github.com/hzoo/contributors-on-github for tracking Babel issues/PRs. Basically just adds how many issues/PRs they've had to the repo/org/etc. Then its easier to know if it's someone's first PR or not

<img width="848" alt="screen shot 2017-01-21 at 8 25 18 pm" src="https://cloud.githubusercontent.com/assets/588473/22179107/c129b8cc-e017-11e6-9b73-3bd5c2b75e68.png">

Would be great as a built-in thing on github but right now it's just a chrome extension.

**Comment by KrauseFx** [comment]
@hzoo That's a great plugin, I've been using this for multiple months now, super happy with it, thanks for building it 👍

**Comment by ncoghlan** [comment]
For contributor reporting, @glasnt's octohatrack may also be a useful source of ideas: https://github.com/LABHR/octohatrack/blob/master/README.md

**Comment by andrew** [comment]
Moving this to the [Backlog](https://github.com/librariesio/libraries.io/blob/master/Backlog.md) as we'd still like to implement it but can't see that happening in the near future.
