### ISSUE TITLE
Allow users to "poke" / request an update/re-read of an updated package.

### ISSUE THREAD

**Issue by dceejay** [librariesio/libraries.io#1080]
Occasionally libraries.io seems not to catch a new version of a package on npm. It would be nice if there was a a way to flag a missing update to get it scanned directly, or as soon as possible.

**Comment by andrew** [comment]
@dceejay just deploying this now 🚢

**Comment by andrew** [comment]
The button shows up on the bottom of the right hand column for logged in users if the project hasn't been syned within the past 24 hours:

![screen shot 2017-01-19 at 4 48 24 pm](https://cloud.githubusercontent.com/assets/1060/22116080/48035fd6-de67-11e6-9fd6-b8478e1ca2f1.png)

**Comment by dceejay** [comment]
Magic. Thanks.
