### ISSUE TITLE
Allow a user to queue up a manual refresh of a package

### ISSUE THREAD

**Issue by knolleary** [librariesio/libraries.io#1084]
We have seen npm packages get out of sync between libraries.io and npmjs.org. For example,
at the time of raising, https://libraries.io/npm/node-red-contrib-counter lists 0.1.3, https://www.npmjs.com/package/node-red-contrib-counter lists 0.1.4.

@andrew has been very responsive to my twitter dm's to nudge individual packages, but it would be nice to have a means for a user to queue up a manual refresh of a package. That would allow us to fix up packages and also help highlight where the underlying system has missed an update.

**Comment by andrew** [comment]
@knolleary I fixed this for @dceejay yesterday: https://github.com/librariesio/libraries.io/issues/1080

**Comment by knolleary** [comment]
🤣 

I should really talk to my colleagues. Thanks!
