### ISSUE TITLE
Allow sorting repositories in the dashboard

### ISSUE THREAD

**Issue by andrew** [librariesio/libraries.io#1086]
If you have a lot of repos then finding the ones you want to monitor on the dashboard may be tricky, sorting by similar attributes as regular repo search

**Comment by samjacobclift** [comment]
Ahh do you mean updating this route `https://libraries.io/repositories` to enable us to have extra filters on it. i.e. kinda like this route `https://libraries.io/Atom`

I guess these are the kinda filters we would be interested in

1. Text
2. Language
3. Package Manager

Any others :)

**Comment by andrew** [comment]
Yeah, I don't think we need the filters right now, just the sorting options, there isn't enough space in the UI for the whole search interface right now

**Comment by andrew** [comment]
Moving this to the [Backlog](https://github.com/librariesio/libraries.io/blob/master/Backlog.md) as we'd still like to implement it but can't see that happening in the near future.
