### ISSUE TITLE
No results for search 'NTPsec'

### ISSUE THREAD

**Issue by ghane** [librariesio/libraries.io#1092]
Hi,

The NTPSec project [https://ntpsec.org] is a fork of the original ntpd, concentrating on security, and supported by the CII.

Code is available at:  https://gitlab.com/NTPsec/ntpsec
Other project repositories are available at:  https://gitlab.com/NTPsec/

**Comment by BenJam** [comment]
we have recently added support for GL #910. Llibraries.io will only process libraries distributed by one of the package managers supported #48 .
