### ISSUE TITLE
Scoped NPM packages not accessible

### ISSUE THREAD

**Issue by Turbo87** [librariesio/libraries.io#1094]
e.g. https://www.npmjs.com/package/@glimmer/syntax should be available at https://libraries.io/npm/%40glimmer%2Fsyntax or maybe even https://libraries.io/npm/@glimmer/syntax, but apparently that doesn't work yet.

**Comment by Turbo87** [comment]
@andrew any news on this? do you need more information? can I help in any way to unblock this?

**Comment by andrew** [comment]
@Turbo87 https://libraries.io/npm/@glimmer%2Fsyntax, sorry for the delay, just fixed a scoped module bug yesterday

**Comment by Turbo87** [comment]
awesome, thank you!!

**Comment by Turbo87** [comment]
@andrew is there a way to trigger the "Dependent repositories" analysis? [fkling/astexplorer](https://github.com/fkling/astexplorer/blob/master/website/package.json#L41) for example should probably show up there

**Comment by andrew** [comment]
@Turbo87 I just double checked and it didn't find any, looking at fkling/astexplorer theres a bug with the parser that doesn't find nested package.json files (opened an issue here: https://github.com/librariesio/librarian-parsers/issues/116), any other examples I can use to investigate?

**Comment by Turbo87** [comment]
> any other examples I can use to investigate?

I'll let you know if I find any others

the astexplorer recently changed to a nested `package.json`, maybe you could analyse an older revision if that helps?

**Comment by andrew** [comment]
@Turbo87 atm libraries only checks the latest commit, it doesn't have a way to step backwards through the history of git repos right now as that's a pretty intensive job
