### ISSUE TITLE
Establish some personas 

### ISSUE THREAD

**Issue by BenJam** [librariesio/libraries.io#1127]
Libraries.io does a lot of things for a lot of people. As such it would be good to establish and agree who those personas are. From there we can establish some use cases. 

Having written much of the strategy the current straw man looks like this:

## Google 
_is hungry for your linked datas so she can serve you up search traffic_

## Searcher 
_is a developer with a problem, she is looking for something to help solve it._ 

## Producer 
_has a product or products that incorporates some FOSS dependencies. She needs to ensure the product(s) are well maintained, free of vulnerabilities and licence compatible._

## Maintainer
_is a developer with a successful FOSS project. She's looking to understand more about those who use her project, attract more contributors and manage their contributions well._

## Extender 
_has her own ideas. She wants access to the raw data so that she can mash up her own service and offer it to the world._

## Overlord
_has a vast empire of people, products and projects. Some of which she publishes as open source, some are proprietary. She wants to ensure that her policies regarding the use of dependencies are adhered to and that her team are as efficient as possible._

It's very likely that some of these personas are also users of dependencyci.com.

**Comment by BenJam** [comment]
If anyone relates to, disagrees with or has specific use case that are well/poorly catered to please feel free to comment below. If you'd like to give us some *props* then there's also #224 ;)

**Comment by BenJam** [comment]
from @bengourley 

>just got your ping! I use it mainly to a) find node modules b) vet a module's dependencies c) vet the depth of a module’s dependency tree. I also have notifications on for some modules, but I don’t find that very useful

**Comment by voltronik** [comment]
I'm a _Searcher_. I use it to find repos that I wouldn't normally know about as they aren't available through Bower or the WordPress.org plugin repo.

**Comment by ldodds** [comment]
I'm a *Searcher* but am also occasionally working on products so am also a *Producer*.

**Comment by epower** [comment]
I fall into the Producer, Extender and the Overlord buckets. I'm already a user of dependencyci.com. :)

**Comment by M-Zuber** [comment]
I'd say I am a _maintainer_ with some _searcher_ and _producer_ thrown in for flavour

**Comment by obestwalter** [comment]
* Searcher
* Producer
* Maintainer

**Comment by BenJam** [comment]
thanks everyone for you input. Though I think I should have asked the open rather than closed question from the off. This decision may haunt me for years to come 😬

**Comment by andrew** [comment]
Fixed by librariesio/documentation#44
