### ISSUE TITLE
Dangerise libraries.io

### ISSUE THREAD

**Issue by BenJam** [librariesio/libraries.io#1164]
Placeholder ticket for the point at which we think using [danger](https://github.com/danger/danger) as a tool to guide contributors would be useful.

**Comment by orta** [comment]
Hah, what about:

* "Put libraries.io in Danger?"
* "Add some Danger to libraries.io"
* "⚠️ Danger Ahead"

**Comment by BenJam** [comment]
You forgot the soundtrack: https://soundcloud.com/2emedanger

**Comment by orta** [comment]
No joke, there is literally a soundtrack for Danger: http://danger.systems/guides/faq.html#danger-keeps-getting-refered-to-as-quot-her-she-quot-what-gives

**Comment by andrew** [comment]
I will play this whilst merging: https://www.youtube.com/watch?v=EVr__5Addjw

**Comment by andrew** [comment]
Moving this to the [Backlog](https://github.com/librariesio/libraries.io/blob/master/Backlog.md) as we'd still like to implement it but can't see that happening in the near future.
