### ISSUE TITLE
Refactor Repository conditionals

### ISSUE THREAD

**Issue by andrew** [librariesio/libraries.io#1173]
Currently we have a lot of conditionals in the `Repository` class that look like this:

```ruby
  def update_from_repository(token = nil)
    case host_type
    when 'GitHub'
      update_from_github(token)
    when 'GitLab'
      update_from_gitlab(token)
    when 'Bitbucket'
      update_from_bitbucket(token)
    end
  end
```

They can be refactored out into a single function that knows which type of repo it is and which function to call.

**Comment by maclover7** [comment]
Opened #1188 to try and solve this :)
