### ISSUE TITLE
Gather moar data to support use case production

### ISSUE THREAD

**Issue by BenJam** [librariesio/libraries.io#1183]
Following from #1127 and #1177 it would be good to gather a lot more data from analytics to support/dispute some of the assumptions we make of our users. This will involve 

- [x] Review available data from analytics
- [x] Set up some dashboard
- [x] Add some event tracking (if completely necessary)

**Comment by BenJam** [comment]
right, now that #1184 is done...

**Comment by BenJam** [comment]
@andrew measuring scroll depth on a lot of current pages would be useful using https://github.com/robflaherty/jquery-scrolldepth or https://github.com/leighmcculloch/gascrolldepth.js. Any aversion to my adding these?

**Comment by andrew** [comment]
No aversions here!
