### ISSUE TITLE
Add privacy policy

### ISSUE THREAD

**Issue by BenJam** [librariesio/libraries.io#1184]
Add a privacy policy 🙈 

Should inc. information on 

* Whether we care (we do)
* What information is tracked (inc. files and expiry)
* Where it is held
* What it is used for

Good examples: 

* https://www.gov.uk/help/privacy-policy
* https://www.mysociety.org/privacy/

**Comment by BenJam** [comment]
@andrew just to check here we use:

* Cookies (I'll need some scout some details here)
* Google Analytics
* Google AdSense
* IP Monitoring
* Databases outside of the UK (specifically in the EU in France and the Ireland AWS Region)

**Comment by andrew** [comment]
@BenJam all databases are in France but some code does run in Ireland
