### ISSUE TITLE
Use the meteor package api directly to get more information

### ISSUE THREAD

**Issue by andrew** [librariesio/libraries.io#120]
https://github.com/meteor/docs/blob/master/long-form/package-server-api.md

**Comment by andrew** [comment]
`https://atmospherejs.com/a/packages` is gone so this is higher priority now

**Comment by andrew** [comment]
Paging @olizilla 😘

**Comment by olizilla** [comment]
ooh laa laa. Meteor now uses both a `package.json` for npm deps and a `.meteor/versions` file for atmosphere packages. The general direction is to pull much of core meteor functionality into npm packages.

https://github.com/meteor/meteor/blob/907e1d91833eace7e40cc1d796cc7f9d171ceab1/Roadmap.md#full-transition-to-npm

**Comment by andrew** [comment]
The main problem here is getting the list of packages from at atmospherejs.com as they removed the way I was using before, instead pulling them directly from packages.meteor.com over DDP

**Comment by olizilla** [comment]
roger roger. I'm up for wiring that up but it'll be a few weeks before I get any free time.

**Comment by andrew** [comment]
🙆

**Comment by BenJam** [comment]
Would be nice, given atmospherejs' api has been pulled...

**Comment by andrew** [comment]
Moving this to the [Backlog](https://github.com/librariesio/libraries.io/blob/master/Backlog.md) as we'd still like to implement it but can't see that happening in the near future.
