### ISSUE TITLE
False error: This repository has been removed and cannot be used anymore.

### ISSUE THREAD

**Issue by pratikborsadiya** [librariesio/libraries.io#1211]
When I visit https://libraries.io/github/pratikborsadiya/vali-admin, it says that the repository is not available while in-fact it is available at https://github.com/pratikborsadiya/vali-admin. Please update it.

![screenshot](https://cloud.githubusercontent.com/assets/7806891/23328592/28017de8-fb4b-11e6-9042-a540f4724028.png)

**Comment by andrew** [comment]
Fixed at for you, thanks for letting me know

**Comment by pratikborsadiya** [comment]
@andrew Thanks :clap: for the update.
