### ISSUE TITLE
Add feature to request for more than one package from the api

### ISSUE THREAD

**Issue by BrainMaestro** [librariesio/libraries.io#1214]
## Enhancements and Features

Before submitting an enhancement or feature request:

- [x] Check that the enhancement is not already [in our issue tracker](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+org%3Alibrariesio), they should be labelled 'enhancement'., 
- [x] For large feature requests, check that your request aligns with our strategy http://docs.libraries.io/strategy.
 
I think it would be a good enhancement to be able to request multiple packages at once from the api. My suggestion would be `GET https://libraries.io/api/:platform/:name1,:name2,:name3,:name4?api_key=YOUR_API_KEY`. A different delimiter can be used instead of a comma. [Stackexchange api](https://api.stackexchange.com/docs/questions-by-ids) uses semicolons.

This would return an array of the responses that you would typically get from calling `GET https://libraries.io/api/:platform/:name?api_key=YOUR_API_KEY` multiple times. 

Due to the nature of the existing endpoint, this new one would be limited to returning multiple packages that belong to one platform. Example: `GET https://libraries.io/api/npm/grunt,webpack,react?api_key=YOUR_API_KEY` 

The major benefit would be reducing the number of HTTP trips required to request a certain number of packages. 

I would be willing to work on this if you point me to the right place. I'm new to Rails though.

Thanks

**Comment by andrew** [comment]
@BrainMaestro we do actually have this feature, it's just not documented yet, there are some details over here: https://github.com/librariesio/libraries.io/issues/844#issuecomment-269963905

**Comment by andrew** [comment]
Also, https://github.com/BrainMaestro/packagehub looks awesome 🎉

**Comment by BrainMaestro** [comment]
@andrew Oh okay. Thanks! 😊 

I was planning to use it for that extension, but the endpoint actually requires an API Key which is tough. Anyway thanks for the response. Should I close this?

**Comment by andrew** [comment]
@BrainMaestro I think we'll be able to remove the api key restriction once I've upgraded our elasticsearch cluster, it's there mostly because it can't handle large amounts of traffic right now.

**Comment by BrainMaestro** [comment]
Okay. I'll wait until then

**Comment by BrainMaestro** [comment]
Hey @andrew. Sorry to bother, but any headway with this? Making multiple requests sometimes leads to a bad experience for the plugin users. Thanks for the awesome api again.
