### ISSUE TITLE
SourceRank score says license is missing, but it isn't

### ISSUE THREAD

**Issue by JonasT** [librariesio/libraries.io#1217]
SourceRank score says license is missing, but it isn't: https://libraries.io/github/ChiCraft/stdlib/sourcerank ("License present? 0") -> https://github.com/ChiCraft/stdlib/blob/master/LICENSE.md

**Comment by andrew** [comment]
I've updated that for you now, the problem was that GitHub doesn't recognize your LICENSE.md as a standard license format so it didn't get picked up automatically.

**Comment by JonasT** [comment]
My main repo is on gitlab where this isn't a problem, so I didn't notice. Interesting! Maybe it would be worth reporting that to Github?

**Comment by andrew** [comment]
@JonasT github are using this gem for their license detection: https://github.com/benbalter/licensee might be worth opening a issue there

**Comment by JonasT** [comment]
I just tested licensee in the latest version, and it seems to detect the license file just fine. Maybe github is using an ancient version of this?
