### ISSUE TITLE
SourceRank detail computation says "Total: 2" at the bottom, but the project page shows "SourceRank: 0" in overview table

### ISSUE THREAD

**Issue by JonasT** [librariesio/libraries.io#1219]
SourceRank detail computation says "Total: 2" at the bottom, but the project page shows "Sourcerank 0" in overview table. The source rank detail page which shows a total score of 2: https://libraries.io/github/ChiCraft/stdlib/sourcerank and the corresponding project page which for me shows "Sourcerank 0" in the table on the right: https://libraries.io/github/ChiCraft/stdlib

**Comment by andrew** [comment]
I've just deployed a fix for that and updated the source rank for you project, thanks for reporting!

**Comment by wrobell** [comment]
Similar issue for https://libraries.io/pypi/atimer.

SourceRank in top-right corner of the page says 0. Click the "0" link and the total says 6.
