### ISSUE TITLE
SourceRank should probably incorporate some basic code qualiy criteria, like at least comments to code line ratio

### ISSUE THREAD

**Issue by JonasT** [librariesio/libraries.io#1221]
The SourceRank should probably incorporate some very basic code qualiy criteria, like at least comments to code line ratio. While I don't suggest a directly linear point distribution according to the comment to line ratio to avoid encouraging people to spam comments into their repos, it could be a hard criteria: if there are barely comments 0 points are provided and otherwise 1-2 points or something.

Dependent on https://github.com/librariesio/libraries.io/issues/78

**Comment by andrew** [comment]
We've got a related issue open for this, quite a big job but definitely worth it 👍  https://github.com/librariesio/libraries.io/issues/78

**Comment by andrew** [comment]
Moving this to the [Backlog](https://github.com/librariesio/libraries.io/blob/master/Backlog.md) as we'd still like to implement it but can't see that happening in the near future.
