### ISSUE TITLE
Add support for SourceForge repositories

### ISSUE THREAD

**Issue by andrew** [librariesio/libraries.io#1222]
Now that we have refactored out all the github specific bits into RepositoryHosts, it should be much easier to add support for SourceForge repos, assuming they have all the correct API endpoints.

**Comment by BenJam** [comment]
Emailed.

**Comment by andrew** [comment]
Omniauth Strategy for enabling "login with sourceforge" in progress over here: https://github.com/librariesio/omniauth-sourceforge believe it's working by the SF endpoint throws 500 errors atm.

**Comment by andrew** [comment]
Moving this to the [Backlog](https://github.com/librariesio/libraries.io/blob/master/Backlog.md) as we'd still like to implement it but can't see that happening in the near future.
