### ISSUE TITLE
Multimitros

### ISSUE THREAD

**Issue by mitrostziavarasgr** [librariesio/libraries.io#1224]
Multimitros  @Mitros1973 @mitrostziavaras 

![img_1867](https://cloud.githubusercontent.com/assets/13299130/23473733/ef4c45ec-feb9-11e6-87b1-6bf360e7db98.GIF)
Thanks for taking the time to raise an issue. This template should guide you through the process of submitting a bug, enhancement or feature request. Please erase any part of this template that is not relevant to your issue. 

#4 

- [x] Bugs

Before submitting a bug report:

- [x] Double-check that the bug is persistent,
- [x] Double-check the bug hasn't already been reported [on our issue tracker](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+org%3Alibrariesio), they *should* be labelled `bug` or `bugsnag`.
#1171 #828 
If you have completed those steps then please replace this section with a description of the steps taken to recreate the bug, the expected behavior and the observed behavior.
#627 #mitrostziavarasgr #542 
## Enhancements and Features

Before submitting an enhancement or feature request:

- [x] Check that the enhancement is not already [in our issue tracker](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+org%3Alibrariesio), they should be labelled 'enhancement'., 
- [x] For large feature requests, check that your request aligns with our strategy http://docs.libraries.io/strategy.
 
If you have complete the above step then please replace this section with a description of your proposed enhancement or feature, the motivation for it, an approach and any alternative approaches considered, and whether you are willing and able to create a pull request for it. Note that we may close this issue if it's not something we're planning on working on.

**Comment by andrew** [comment]
Looks like spam to me
