### ISSUE TITLE
https://libraries.io/github/bgildea/sonorplex-gsk

### ISSUE THREAD

**Issue by bgildea** [librariesio/libraries.io#1238]
Please remove this page from your site.
I have deleted my account.

https://libraries.io/github/bgildea/sonorplex-gsk

Thanks for taking the time to raise an issue. This template should guide you through the process of submitting a bug, enhancement or feature request. Please erase any part of this template that is not relevant to your issue. 

## Bugs
Before submitting a bug report:

- [ ] Double-check that the bug is persistent,
- [ ] Double-check the bug hasn't already been reported [on our issue tracker](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+org%3Alibrariesio), they *should* be labelled `bug` or `bugsnag`.

If you have completed those steps then please replace this section with a description of the steps taken to recreate the bug, the expected behavior and the observed behavior.

## Enhancements and Features

Before submitting an enhancement or feature request:

- [ ] Check that the enhancement is not already [in our issue tracker](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+org%3Alibrariesio), they should be labelled 'enhancement'., 
- [ ] For large feature requests, check that your request aligns with our strategy http://docs.libraries.io/strategy.
 
If you have complete the above step then please replace this section with a description of your proposed enhancement or feature, the motivation for it, an approach and any alternative approaches considered, and whether you are willing and able to create a pull request for it. Note that we may close this issue if it's not something we're planning on working on.

**Comment by andrew** [comment]
I've removed that for you now, thanks for letting me know
