### ISSUE TITLE
Include packages from ForgeBox.io the CFML package manager

### ISSUE THREAD

**Issue by bdw429s** [librariesio/libraries.io#1242]
forgebox.io is a package repository (used with CommandBox CLI package manager) for CFML developers. Please consider including these packages on libraries.io.

https://www.forgebox.io/
I've attached a PDF export of our REST API.  I can provide it in a Swagger format, etc if you need.  The endpoint you'd probably be interested in is `/entries`

[forgebox-api-export.pdf](https://github.com/librariesio/libraries.io/files/814588/forgebox-api-export.pdf)

**Comment by andrew** [comment]
Thanks for the suggestion and the api docs @bdw429s, will definitely get this added soon

**Comment by bdw429s** [comment]
@andrew Thx for the quick reply.  I'm the lead developer of CommandBox and part of team ForgeBox as well so please feel free to ask any questions you have.

**Comment by andrew** [comment]
Moving this to the [Backlog](https://github.com/librariesio/libraries.io/blob/master/Backlog.md) as we'd still like to implement it but can't see that happening in the near future.

**Comment by bdw429s** [comment]
Sorry to hear that @andrew, let me know if there's anything I can do to help.
