### ISSUE TITLE
npm packages are incorrectly listed as deprecated

### ISSUE THREAD

**Issue by lukechilds** [librariesio/libraries.io#1247]
One of my packages [browser-env](https://libraries.io/npm/browser-env) is being incorrectly listed as deprecated. I have previously deprecated specific versions with bugs to warn people to update. It seems like maybe this is being incorrectly interpreted as the package being deprecated forever.

Related: https://github.com/librariesio/libraries.io/issues/408 https://github.com/librariesio/libraries.io/issues/475

Also, I think maybe dependencyci.com use your API? Because people are also getting warnings from dependencyci.com that browser-env is deprecated: https://github.com/lukechilds/browser-env/issues/35

**Comment by andrew** [comment]
I've fixed that for you, thanks for letting me know

**Comment by lukechilds** [comment]
Thanks @andrew 

Do you know what caused it to be listed as deprecated? Was it the deprecation of a previous version?

**Comment by andrew** [comment]
@lukechilds yeah I think the previous deprecation caused a false positive, just that version should have been deprecated, it's on my todo list to investigate further

**Comment by lukechilds** [comment]
Perfect 👌
