### ISSUE TITLE
Fold lib2issues and lib2slack into the main service

### ISSUE THREAD

**Issue by andrew** [librariesio/libraries.io#1251]
Most people don't want to run their own instances of [lib2issues](https://github.com/librariesio/lib2issues) and [lib2slack](https://github.com/librariesio/lib2slack) to get new version notifications on GitHub issues/Slack, we should fold the services into Libraries.io and provide ways for users to enable them directly from the UI

Plucked from @tombh's homepage issue: https://github.com/librariesio/libraries.io/issues/1246

**Comment by samjacobclift** [comment]
woop https://github.com/librariesio/libraries.io/pull/1419

**Comment by andrew** [comment]
Moving this to the [Backlog](https://github.com/librariesio/libraries.io/blob/master/Backlog.md) as we'd still like to implement it but can't see that happening in the near future.
