### ISSUE TITLE
Add "sort by" dropdown to dependents and dependent-repositories

### ISSUE THREAD

**Issue by JamieMason** [librariesio/libraries.io#1255]
## Enhancements and Features

> description of proposed enhancement or feature

Have the [dependents](https://libraries.io/npm/lodash/dependents) and [dependent-repositories](https://libraries.io/npm/lodash/dependent-repositories) views show the "sort by" dropdown as seen on [search results](https://libraries.io/search?q=lodash&sort=).

> motivation for it

Like in search results, it can be useful to bring the more popular projects to the front when reading long lists of them.

> approach and any alternative approaches considered

The name of the project at the top could be put into a two column layout, with the dropdown in the right hand column – similar to how the search results header is displayed. 

> whether you are willing and able to create a pull request for it

I know JS, HTML, and CSS – but have no credible Ruby or Database experience.

**Comment by andrewpros** [comment]
@JamieMason 

Any input on this?

I've read the about text "Helping you make more informed decisions about the software you use. "

Sadly, but i really can't make more informed decision without this kind of sorting, i wanted to search for most popular projects/repos that are dependent on the target framework i will be using.

Well it shows me that, but in NO PARTICULAR order, so it is kinda pointless.

I could try using the api, but it really would be nice to have this.

**Comment by JamieMason** [comment]
> Any input on this?

Nothing more to add from me @andrewpros, thanks.

**Comment by andrew** [comment]
Moving this to the [Backlog](https://github.com/librariesio/libraries.io/blob/master/Backlog.md) as we'd still like to implement it but can't see that happening in the near future.

**Comment by andrewpros** [comment]
@andrew Really, this can't be done in months? What is the reason, even a simple sorting by stars can't be done?

**Comment by JamieMason** [comment]
No problem at all @andrew, appreciate you're busy 👍
