### ISSUE TITLE
Add EULA to API 

### ISSUE THREAD

**Issue by BenJam** [librariesio/libraries.io#1269]
for to clarify the terms under which the API may be used.

**Comment by andrew** [comment]
👍

**Comment by BenJam** [comment]
## Main points

### Agreements (things you agree to)
Storing your data
Monitoring usage
Sharing your information if legally obliged to do so

### Provisions (things you must do)
Must be able to export a user content
Must provide a means to remove user content
Must credit Libraries.io as a source in any service or publication using the API

### Restrictions (things you must not do)
Caching: do not keep longer than the cache header
Malicious use
Do not sub-licence or share keys
Do not share private content 
Do not make representations (ownership, partnership, sponsorship or endorsement)
Compliance with local laws (re. privacy and data protection)

### Acceptance (how to accept these things)
Individual
Entity

### Usage (how to use the service)
Registration
Providing a valid email address
Rate limiting
Increasing rate limits

### Warranties
Limitation of liability
Indemnification
Third party content
No guarantee of correctness
No guarantee of availability

### Modifications
We may change these terms, by updating this page
We may change the API by changing the API page

### Communication
May contact you regarding changes to these terms 
May contact you regarding changes to the api
May contact you regarding 

### Termination
May terminate usage without notice
Keep/destroy cached or saved content
How this relates to provisions (continuing)

### Feedback
Bugs and errors
Support

**Comment by BenJam** [comment]
there are a number of questions that arise form this:

#### Do we want to allow people to hammer the API in order to copy the database (to whatever degree that is possible)?

My answer would be no, as we'll be publishing the data on a regular basis elsewhere. I think it would be good to limit the storage of the data according to the cache header (which is the least friction for us to bind to). If the answer *is* yes then we need to ensure provisions regarding access to and removal of data from third parties are preserved.

**Comment by andrew** [comment]
The main question that arises for me around the "Keep/destroy cached or saved content" is what license is the data available under, if it's a free license (some form of creative commons) then that line goes against the open source principles.

**Comment by BenJam** [comment]
> If it's a free license (some form of creative commons) then that line goes against the open source principles.

I agree with that. I've not seen an example where the EULA references a separate data licensing agreement but it would certainly be possible. I'll add.

>The main question that arises for me around the "Keep/destroy cached or saved content"

As I say that line is more about encouraging people to use the download rather than hammering the API. If it's incompatible with the separate license on the data then we'll remove it.

**Comment by BenJam** [comment]
Right, I've put the data licence up top. @andrew @ldodds any questions/comments before I begin drafting in long form?

**Comment by andrew** [comment]
> Do not sub-licence or share keys

That means don't sublicense the keys, rather than do not sublicense the data or share the keys, in otherwords "The keys should not be sub-licenced or shared"?

**Comment by BenJam** [comment]
sub licensing is a restriction on CC so I've removed it, sharing keys is just trying to encourage proper use!
