### ISSUE TITLE
Use smaller examples in API Documentation

### ISSUE THREAD

**Issue by BenJam** [librariesio/libraries.io#1274]
The API documentation includes excessively lengthly examples that distract from the documentation itself. We should either hide example implementation on load, attach a navigation t the viewport or use smaller examples.

**Comment by andrew** [comment]
👍

**Comment by AlexandreDecan** [comment]
I would also add that the link that is displayed to test the API is not the same than the one that is encoded in the ``href`` attribute., and also differs from the results. 

For instance, the second link is  https://libraries.io/api/npm/grunt/latest/dependencies?api_key=047fd3038d6efad25fa4d7cca5ff92fc, which targets https://libraries.io/api/rubygems/rails/4.2.4/dependencies?api_key=047fd3038d6efad25fa4d7cca5ff92fc, and the results display information for ``base62``.

**Comment by andrew** [comment]
I think @BenJam fixed this
