### ISSUE TITLE
Distinction between dependency kinds in API response

### ISSUE THREAD

**Issue by AlexandreDecan** [librariesio/libraries.io#1288]
It would be very interesting to make a distinction between "classical" dependencies and "development" (or other kind of) dependencies when using the API. 

For instance, consider Mocha which has 11 dependencies and 23 development dependencies: 
https://libraries.io/npm/mocha

The API returns a list of all 34 dependencies, but there is no way to distinguish which ones are considered as development dependencies, and which ones aren't:
https://libraries.io/api/npm/mocha/3.2.0/dependencies?api_key=YOUR_API_KEY_HERE

Here's the resulting JSON: 
http://pastebin.com/PWQAgGFQ

We can see there's a field called "kind", but its single value is "null"...

**Comment by andrew** [comment]
@AlexandreDecan thanks for reporting, that's definitely a bug in the API, kind should have "runtime", "development" or other values as is shown on the project page.

**Comment by AlexandreDecan** [comment]
Any approximate ETA for a fix? It's a pity I can't help on that (I don't know Ruby) :(

**Comment by andrew** [comment]
@AlexandreDecan I should be able to pick this up on Monday next week

**Comment by AlexandreDecan** [comment]
That's a good news! Thank you!

**Comment by andrew** [comment]
@AlexandreDecan just deploying a fix for this now
