### ISSUE TITLE
500s when posting to the api/check/ endpoint

### ISSUE THREAD

**Issue by pketh** [librariesio/libraries.io#1296]
Hi Andrew,

I'm trying to use the check multiple packages endpoint in https://github.com/librariesio/libraries.io/issues/844 . But posting to https://libraries.io/api/check?api_key=[my-api-key] returns a 500 error. I'm not sure if it's because the data i'm posting is malformed or because of something else?

thx!

**Comment by pketh** [comment]
here's what the data I'm posting looks like:
```
[{"projects":[{"name":"express","platform":"npm"},{"name":"unique-random-array","platform":"npm"},{"name":"cli-color","platform":"npm"},{"name":"hello","platform":"npm"}]}]
```

**Comment by andrew** [comment]
Just looking into this in bugsnag, the data looks correct but is coming through very strangly on the rails app:

```ruby
{
  "{\"projects\":": {
    "{\"name\":\"express\",\"platform\":\"npm\"},{\"name\":\"unique-random-array\",\"platform\":\"npm\"},{\"name\":\"cli-color\",\"platform\":\"npm\"},{\"name\":\"hello\",\"platform\":\"npm\"}": {
      "}": null
    }
  },
  "api_key": "XXX",
  "controller": "api/status",
  "action": "check"
}
```

Do you have an example of the Javascript(?) code you're using to post to the service? Rails should decode the json if it sees the correct `application/json` headers.

**Comment by pketh** [comment]
in coffeescript form my code looks like 
```coffeescript
    checkForPackages: (packages, versions) ->
      packages = JSON.stringify packages
      check = "https://libraries.io/api/check?api_key=#{API_KEY}"
      console.log packages # {"projects":[{"name":"express","platform":"npm"}]}
      post(check, packages)
      .then (result) ->
        console.log "🚒", result
```

the code I'm using to do the actual post request is just a wrapper around the jquery [post](https://api.jquery.com/jquery.post/) method
```coffeescript
  post = (options, data) ->
    new Promise (resolve, reject) ->
      $.post(options, data).then(resolve, reject)
```

**Comment by andrew** [comment]
I think you'll need to pass the data and content types in `$.post`:

    dataType: "json",
    contentType: "application/json",

Alternatively don't stringify the `packages` and I suspect jquery will set them for you, so:

```coffescript
   checkForPackages: (packages, versions) ->
      check = "https://libraries.io/api/check?api_key=#{API_KEY}"
      post(check, packages)
      .then (result) ->
        console.log "🚒", result
```

**Comment by andrew** [comment]
Also 💯  for the 🔥 🚚

**Comment by pketh** [comment]
haha emojis are the only way to debug 🥇 

I was getting the same issues without the stringify so I tried writing it all out explicitly with $.ajax

```coffeescript
  post = (url, data) ->
    new Promise (resolve, reject) ->
      $.ajax
        url: url
        type: "POST"
        data: data
        dataType: "json"
        contentType: "application/json"
      .then(resolve, reject)
```

but now the url (https://libraries.io/api/check?api_key=[key]) returns a 404

I'm also running the request from localhost on dev at http://10.1.1.93:8000 and getting back a cors error that may not be related: 

```No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://10.1.1.93:8000' is therefore not allowed access. The response had HTTP status code 404.```

**Comment by andrew** [comment]
I had success with this js in the browser console:

```js
$.ajax({
   type: "POST",
   url: "https://libraries.io/api/check?api_key=XXX",
   contentType: "application/json",
   success: function (msg) {
    console.log(msg)
   },
   data: JSON.stringify({"projects":[{"name":"express","platform":"npm"}]})
});
```

**Comment by pketh** [comment]
so weird, I just changed the api_key, and I still get a 404

<img width="1013" alt="screen shot 2017-03-23 at 12 58 48 pm" src="https://cloud.githubusercontent.com/assets/877072/24259927/ab34d854-0fc8-11e7-864c-b279378cf8e5.png">

ran this from glitch.com

**Comment by andrew** [comment]
Ah yeah, it does that for me too (ran it from a console opened on a libraries.io page), that's a bug, although you realise you'll be leaking your API key to everyone if you do that in the browser?

**Comment by andrew** [comment]
@pketh I'm upgrading the cors handling in the api controller as it currently doesn't support "preflight requests" in the form of `OPTION` requests, will post back here when it's deployed

**Comment by andrew** [comment]
🚢

**Comment by pketh** [comment]
awesometown, looks like it works now
<img width="128" alt="screen shot 2017-03-23 at 1 53 58 pm" src="https://cloud.githubusercontent.com/assets/877072/24262375/34349d68-0fd0-11e7-8685-3927cb9fcf19.png">

thx!
