### ISSUE TITLE
No email about Django 1.11

### ISSUE THREAD

**Issue by andreymal** [librariesio/libraries.io#1341]
(I sent this message to support@libraries.io few days ago, but I did not get an answer.)

Few days ago I received 3 messages about Django versions:

![](https://i.imgur.com/CPdBCMi.png)

- Django 1.8.18 (14:23:45 UTC)
- Django 1.10.7 (14:37:43 UTC)
- Django 1.9.13 (14:39:04 UTC)

But not about Django 1.11!

![](https://i.imgur.com/tD9ssDx.png)

"Spam" and "Trash" folders are empty.

I don't know how to reproduce it, but maybe can you check logs? Is message really not sent or this is my local problem? Because if there are no notifications, then libraries.io is useless for me.

**Comment by andrew** [comment]
Sorry about that, I believe it was an error on our end, I've recently made some improvements to the Python importer that should squish the bug
