### ISSUE TITLE
Denormalize repository_id onto repository dependencies

### ISSUE THREAD

**Issue by andrew** [librariesio/libraries.io#1348]
Writing this down so I don't forget it.

One of the most valuable queries  we have is also one of the worst performers, getting the repositories that depend on a project:

```sql
SELECT  "repositories".* FROM "repositories" 
INNER JOIN "manifests" ON "repositories"."id" = "manifests"."repository_id" 
INNER JOIN "repository_dependencies" ON "manifests"."id" = "repository_dependencies"."manifest_id" 
WHERE "repository_dependencies"."project_id" = ? AND "repositories"."private" = ? 
GROUP BY repositories.id 
ORDER BY repositories.stargazers_count DESC 
LIMIT ?
```

We currently are joining across both the `manifests` and `repository_dependencies` tables. If we add `repository_id` to `repository_dependencies` we can skip joining the `mainfests` table for many of the queries, which should make for a much more efficient lookup.

**Comment by abrophy** [comment]
I've been looking at this problem and denormalizing the id initially is easy enough, but I could use some input as to how best to update the repository_dependencies with updated manifests.

For instance this method in the repository model
` 
def repository_dependencies
    manifests.latest.includes({repository_dependencies: {project: :versions}}).map(&:repository_dependencies).flatten.uniq
  end
`
shows that the relationship should only exist for dependencies listed on the latest manifest for that repository, which makes sense. But means that the denormalized ID will have to be updated every time there is a new/change made to the manifest for that repo.

The approach I'm thinking of using is having an update method in an after_save callback on the manifest model that clears any existing repository_id's for dependencies of the linked repo then regenerating/saving them based on the new manifest. Using similar logic to the above query.

I have two concerns:

- the performance of that callback. Considering it will be called on every new manifest linking every repository_dependency on migration, and then again on each new manifest, and manifest update.
- not sure if this callback is firing in the correct place, as I'm not sure where in the life repository_dependencies themselves are created for manifest, my callback could fire too early

I'll keep digging on my own but I'm going to push up a PR with what I have so far so I can get some feedback

**Comment by abrophy** [comment]
see #1532

Also question:
Should I create an index for repository_id field being denormalized here

**Comment by andrew** [comment]
I'm finally getting round to tackling this, sorry for the silence @abrophy!

I've deployed a migration and am currently backfilling the field on all existing records.

`manifests.latest` is a bit of a legacy hack, hoping to remove that in the process of completing this

**Comment by andrew** [comment]
Before:
```sql
SELECT  "repositories".* FROM "repositories" 
INNER JOIN "manifests" ON "repositories"."id" = "manifests"."repository_id" 
INNER JOIN "repository_dependencies" ON "manifests"."id" = "repository_dependencies"."manifest_id" 
WHERE "repository_dependencies"."project_id" = ? AND "repositories"."private" = ? 
GROUP BY repositories.id 
ORDER BY repositories.stargazers_count DESC 
LIMIT ?
```

After:
```sql
SELECT "repositories".* FROM "repositories" 
INNER JOIN "repository_dependencies" ON "repositories"."id" = "repository_dependencies"."repository_id" 
WHERE "repository_dependencies"."project_id" = $1 
GROUP BY repositories.id 
ORDER BY repositories.rank DESC NULLS LAST, repositories.stargazers_count DESC
```
