### ISSUE TITLE
/:project/latest/dependecies gives different results to :project/<latest-tag>/dependencies [bug]

### ISSUE THREAD

**Issue by Crashthatch** [librariesio/libraries.io#1359]
The [API docs](https://libraries.io/api#project-dependencies) state that you may pass "latest" as the version to get the dependencies for the latest published version of the project, but this gives different results to when I put the version string in the URL directly:

Compare https://libraries.io/api/npm/d3/latest/dependencies ([returns json with 3 dependencies](https://gist.github.com/Crashthatch/93082822bce9f0aefcd763c18def4eb5))

With: https://libraries.io/api/npm/d3/4.8.0/dependencies ([correctly returns json with 38 dependencies](https://gist.github.com/Crashthatch/69935ad892177c7486f2931c286278a2))

Both correctly appear to resolve the current version to 4.8.0 in their JSON:

```
"latest_release_published_at": "2017-04-15T05:36:07.846Z",
"latest_release_number": "4.8.0",

"latest_stable_release": {
"number": "4.8.0",
"published_at": "2017-04-15T05:36:07.846Z"
},
```

**Comment by andrew** [comment]
🚢  should be fixed in production now
