### ISSUE TITLE
nulls returned in API /tree dependencies when libraries does not know version

### ISSUE THREAD

**Issue by Crashthatch** [librariesio/libraries.io#1360]
To reproduce:
Call https://libraries.io/api/npm/egg/0.12.0/dependencies, note that there are 55 items in the "dependencies" array, 31 of which are kind: "runtime".
https://libraries.io/api/npm/egg/tree, there are 31 "first level" elements in the dependencies array, but that 4 of them are "null".

![image](https://cloud.githubusercontent.com/assets/186067/25066431/14ca5f6c-221d-11e7-8116-48df1288af2d.png)

By comparing the two calls, I believe the ones that are missing are those for which the "requirements" are later than libraries' known "latest" repository. Presumably then it can't resolve the semver to a known revision and so leaves a null instead of a tree of dependencies:

```
{
"project_name": "egg-development",
"name": "egg-development",
"platform": "NPM",
"requirements": "^1.2.0",
"latest_stable": "1.0.2",
"latest": "1.0.2",
"deprecated": false,
"outdated": false,
"filepath": null,
"kind": "runtime"
},
```

This particular repo 1.2.0 was published 3 months ago, so it's not just that libraries is slow to catch up.

The [HTML /tree page](https://libraries.io/npm/egg/1.0.0-rc.3/tree) doesn't seem to ever finish loading - it spins forever "Generating dependency tree". Perhaps that is caused by the unexpected nulls?

It's not limited to first-level dependencies. Ctrl+F for "null" on that API /tree page and you'll see missing dependencies nested inside the tree too.

I saw the same thing with the d3 repo, d3-brush was not appearing in d3/tree. I manually clicked the "resync project" and libraries has since fetched the latest version of d3-brush and d3/dependencies no longer shows "requirements" as ahead of "latest". d3/tree is still showing the nulls, but I think that is a cached response.

I'm not sure if this counts as a bug, more a lack of data, but it's definitely an issue as it can mean that /tree is missing out dependencies (in some cases, more than half) which makes it a lot less useful. Imagine a project where its largest dependency is missing, that could be a good % of the tree! Perhaps /tree could default to the latest known version of the dependency in this case, so at least /tree is returning all of the correct dependencies, if not the correct versions? (The API call already seems to ignore the version given in the URL, and just returns for latest_stable so maybe all child dependencies could also do that?)

It might also make sense to schedule a refresh of the unknown version's data from the package manager? A dependency on a version of a package later than the current known latest seems like a pretty good hint that a later version has been released? (Maybe there are rate-limit issues with doing this?)

- [ x ] Double-check that the bug is persistent,
- [ x ] Double-check the bug hasn't already been reported [on our issue tracker](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+org%3Alibrariesio), they *should* be labelled `bug` or `bugsnag`.

**Comment by andrew** [comment]
Yeah looks like missing data and a poor response when it can't find what it's looking for, you're the first person that I know of using the tree API (it's undocumented atm because it's a bit intensive on the server).

The HTML version probably isn't loading due to a backed up sidekiq queue.

I'm going to dig into this now and see if I can work out some steps to fix the tree for this version, then what to do for all trees.
