### ISSUE TITLE
Send pull request to upgrade my dependency

### ISSUE THREAD

**Issue by bramp** [librariesio/libraries.io#1365]
## Enhancements and Features

For my open source projects, could libraries.io send a pull request to upgrade my dependency, instead of sending a email to tell me a new one is available.

This of course may not be possible/easy for all projects, but would save me a lot of time. Typically my projects use Travis CI (or similar) so any pull request would automatically get tested, and it would turn the upgrade process into a simple click of a "Accept PR" button.

**Comment by andrew** [comment]
Moving this to the [Backlog](https://github.com/librariesio/libraries.io/blob/master/Backlog.md) as we'd still like to implement it but can't see that happening in the near future.
