### ISSUE TITLE
Danger Plugin API

### ISSUE THREAD

**Issue by andrew** [librariesio/libraries.io#1367]
@orta tweeted yesterday about using the Libraries API for getting information about projects for Danger: https://twitter.com/orta/status/854110094476406784, related github issue: https://github.com/danger/danger-js/pull/227#issuecomment-294618329

@orta has already got a stats API for cocoapods: https://cocoadocs-api-cocoapods-org.herokuapp.com/pods/FDBarGuage/stats, going to break down the bits we have and the bits we don't (but could have) availabe via the API.

On a side note, this information is also useful for the Chrome extension I'm working on: https://github.com/librariesio/extension

|Attribute| Data available in the API | 
|-|-|
|Very Popular| ✅  SourceRank, dependents and stars if on Github |
|Popular| ✅  SourceRank, dependents and stars if on Github |
|Supports Swift Package Manager| 🏗  we have the manifest file like Swift.package but not currently available via the API  |
|Great Documentation| ⏲  not currently known but possible to add once we store the source code for each library |
|Documentation| ⏲  not currently known but possible to add once we store the source code for each library |
|Badly Documented| ⏲  not currently known but possible to add once we store the source code for each library |
|Great README| 🏗  we have readme contents but not currently in the API |
|Minimal README| 🏗  we have readme contents but not currently in the API |
|Empty README| 🏗  we have readme contents but not currently in the API |
|Has a CHANGELOG| ✅  has the path to changelog/history/changes file on GH/GL/BB |
|Built in Swift| ✅  We have the main language if the repo is hosted on GH/BB |
|Built in Objective-C++| ✅  We have the main language if the repo is hosted on GH/BB |
|Uses GPL| ✅  We have the licenses that the project and repo is available under |
|Uses WTFPL| ✅  We have the licenses that the project and repo is available under |
|Has Tests| ⏲  not currently known but possible to add once we store the source code for each library |
|Test Expectations / Line of Code| ⏲  not currently known but possible to add although very language specific |
|Install size|⏲  not currently known but possible to add once we store the source code for each library |
|Lines of Code / File|⏲  not currently known but possible to add once we store the source code for each library |
|Verified Owner| ⏲  not currently known but possible to add, different for each package manager |
|Post-1.0.0| ✅  We have the version numbers |
|Is Deprecated| ✅  We have the status |
|Lots of open issues| ✅  We have the open issue counts if hosted on GH |

On another side note, the Cocoapods quality metrics (https://guides.cocoapods.org/making/quality-indexes.html) are very GitHub centric at the moment, we can definitely help them break free of the monoculture now that we have support for GitLab and Bitbucket.

**Comment by orta** [comment]
Yeah, there's definitely some super-CP focused points inside the results - but yeah, I can definitely use a bunch of this, woooooo

**Comment by KrauseFx** [comment]
That's awesome 🚀

**Comment by andrew** [comment]
Moving this to the [Backlog](https://github.com/librariesio/libraries.io/blob/master/Backlog.md) as we'd still like to implement it but can't see that happening in the near future.
