### ISSUE TITLE
Find repos for top cii projects

### ISSUE THREAD

**Issue by andrew** [librariesio/libraries.io#1370]
- [x] https://libraries.io/Pypi/Jinja2
- [x] https://libraries.io/Maven/javax.servlet:servlet-api
- [x] https://libraries.io/Maven/commons-io:commons-io
- [x] https://libraries.io/Pypi/Werkzeug
- [x] https://libraries.io/Pypi/psycopg2
- [x] https://libraries.io/NuGet/Microsoft.AspNet.Razor
- [x] https://libraries.io/Pypi/gunicorn
- [x] https://libraries.io/Maven/javax.servlet:javax.servlet-api
- [ ] https://libraries.io/Pypi/wsgiref (ERR!) https://github.com/librariesio/libraries.io/issues/1372
- [x] https://libraries.io/Pypi/Sphinx
- [x] https://libraries.io/Maven/ch.qos.logback:logback-classic
- [x] https://libraries.io/Pypi/pytest
- [x] https://libraries.io/Rubygems/Rack
- [x] https://libraries.io/Pypi/PyYAML
- [x] https://libraries.io/Pypi/numpy
- [ ] https://libraries.io/Maven/org.apache.commons:commons-lang3
- [ ] https://libraries.io/NuGet/Microsoft.Web.Infrastructure !!!
- [x] https://libraries.io/Pypi/pytz
- [x] https://libraries.io/Rubygems/unicorn
- [x] https://libraries.io/Maven/org.apache.httpcomponents:httpclient
- [x] https://libraries.io/Pypi/python-dateutil
- [x] https://libraries.io/NuGet/Modernizr
- [ ] https://libraries.io/NuGet/Microsoft.AspNet.WebPages
- [x] https://libraries.io/Maven/org.mockito:mockito-all
- [ ] https://libraries.io/NuGet/Microsoft.AspNet.Web.Optimization
- [ ] https://libraries.io/NuGet/Microsoft.AspNet.WebApi.Client
- [x] https://libraries.io/Maven/commons-lang:commons-lang
- [x] https://libraries.io/Pypi/Pillow
- [x] https://libraries.io/Pypi/SQLAlchemy
- [x] https://libraries.io/Maven/org.codehaus.jackson:jackson-mapper-asl
- [ ] https://libraries.io/Maven/javax.servlet.jsp:jsp-api
- [ ] https://libraries.io/NuGet/Microsoft.AspNet.WebApi.Core
- [ ] https://libraries.io/NuGet/Microsoft.AspNet.WebApi
- [x] https://libraries.io/NuGet/WebGrease
- [x] https://libraries.io/Rubygems/kgio
- [x] https://libraries.io/Maven/commons-codec:commons-codec
- [x] https://libraries.io/Maven/commons-logging:commons-logging
- [x] https://libraries.io/Pypi/lxml
- [x] https://libraries.io/Pypi/wheel
- [x] https://libraries.io/Maven/commons-dbcp:commons-dbcp
- [x] https://libraries.io/Maven/org.aspectj:aspectjrt
- [x] https://libraries.io/NuGet/Microsoft.Owin
- [ ] https://libraries.io/NuGet/Microsoft.AspNet.WebApi.WebHost
- [ ] https://libraries.io/NuGet/Microsoft.jQuery.Unobtrusive.Validation
- [ ] https://libraries.io/Rubygems/abstract
- [x] https://libraries.io/Maven/org.mockito:mockito-core
- [ ] https://libraries.io/Maven/org.aspectj:aspectjweaver
- [x] https://libraries.io/NuGet/jQuery.Validation
- [x] https://libraries.io/Pypi/ipython
- [ ] https://libraries.io/NuGet/Microsoft.Owin.Host.SystemWeb
- [x] https://libraries.io/Pypi/beautifulsoup4
- [ ] https://libraries.io/NuGet/Microsoft.Net.Http
- [x] https://libraries.io/Pypi/Pygments
- [x] https://libraries.io/Rubygems/shellany
- [x] https://libraries.io/Maven/jstl:jstl
- [x] https://libraries.io/Maven/javax.inject:javax.inject
- [x] https://libraries.io/NPM/bcrypt-nodejs !!!
- [x] https://libraries.io/Maven/javax.mail:mail
- [ ] https://libraries.io/NuGet/Microsoft.Owin.Security.Cookies
- [x] https://libraries.io/Pypi/tornado
- [x] https://libraries.io/Pypi/South
- [ ] https://libraries.io/NuGet/Microsoft.AspNet.Identity.EntityFramework

**Comment by andrew** [comment]
CII deps with no known license:

- [ ] https://libraries.io/Maven/javax.servlet:servlet-api
- [ ] https://libraries.io/NuGet/Microsoft.AspNet.Razor
- [ ] https://libraries.io/Rubygems/Rack
- [ ] https://libraries.io/NuGet/Microsoft.Web.Infrastructure
- [ ] https://libraries.io/NuGet/Modernizr
- [ ] https://libraries.io/NuGet/Microsoft.AspNet.WebPages
- [ ] https://libraries.io/NuGet/Microsoft.AspNet.Web.Optimization
- [ ] https://libraries.io/NuGet/Microsoft.AspNet.WebApi.Client
- [ ] https://libraries.io/NuGet/Microsoft.AspNet.WebApi.Core
- [ ] https://libraries.io/NuGet/Microsoft.AspNet.WebApi
- [ ] https://libraries.io/NuGet/WebGrease
- [ ] https://libraries.io/NuGet/Microsoft.Owin
- [ ] https://libraries.io/NuGet/Microsoft.AspNet.WebApi.WebHost
- [ ] https://libraries.io/NuGet/Microsoft.jQuery.Unobtrusive.Validation
- [ ] https://libraries.io/Rubygems/abstract
- [ ] https://libraries.io/NuGet/jQuery.Validation
- [ ] https://libraries.io/NuGet/Microsoft.Owin.Host.SystemWeb
- [ ] https://libraries.io/NuGet/Microsoft.Net.Http
- [ ] https://libraries.io/Maven/jstl:jstl
- [ ] https://libraries.io/NPM/bcrypt-nodejs
- [ ] https://libraries.io/NuGet/Microsoft.Owin.Security.Cookies
- [ ] https://libraries.io/NuGet/Microsoft.AspNet.Identity.EntityFramework

**Comment by BenJam** [comment]
@andrew updated these now, one library req. a dual licence flag which I cannot add in admin. Should be okay to run analysis whenever.
