### ISSUE TITLE
Some NuGet Packages missing repo despite having (correct) GH URI

### ISSUE THREAD

**Issue by BenJam** [librariesio/libraries.io#1371]
There seem to be a number of projects distributed through NuGet that have picked up the correct GitHub URL for homepage but have failed to find the corresponding repo. Examples (which I've now updated) include:

https://libraries.io/nuget/Microsoft.Owin

**Comment by andrew** [comment]
Fixed the bug that was causing this and have kicked of a resync of approx 25,000 packages that may have been affected by it since the bug was introduced a couple months ago
