### ISSUE TITLE
Look at how to track projects where source is a part of a larger project

### ISSUE THREAD

**Issue by BenJam** [librariesio/libraries.io#1372]
https://libraries.io/pypi/wsgiref is distributed through PyPi independently of python, where the source lives https://github.com/python/cpython/tree/master/Lib/wsgiref.

**Comment by andrew** [comment]
Moving this to the [Backlog](https://github.com/librariesio/libraries.io/blob/master/Backlog.md) as we'd still like to implement it but can't see that happening in the near future.
