### ISSUE TITLE
Wrong License

### ISSUE THREAD

**Issue by tom8941** [librariesio/libraries.io#1426]
Hello,

I have noticed a wrong license for : https://libraries.io/github/tom8941/ioc_log_search
It should be GPL 3 and not LGPL3 as it is the case in : https://github.com/tom8941/ioc_log_search

Can you please check that ?

Thanks.

**Comment by andrew** [comment]
@tom8941, I've fixed that for you now, thanks for letting us know

**Comment by tom8941** [comment]
Thanks a lot !
