### ISSUE TITLE
Remove duplicate index on repositories table

### ISSUE THREAD

**Issue by andrew** [librariesio/libraries.io#1428]
Looks like we have an extra full_name index on the `repositories` table: `index_repositories_on_full_name`, when we have `index_repositories_on_host_type_and_full_name` already.

All instances of `find_by_full_name(full_name)` will need to be changed for `where('lower(full_name) = ?, full_name.downcase)` in the code as well.

**Comment by abrophy** [comment]
Hey Andrew I don't see the index_repositories_on_full_name index in the schema, must have been removed already.

As for the find_by_full_name instances, are you saying that you want to have those changed to where () calls instead?
