### ISSUE TITLE
Only bower.json dependencies shown for a Maven project

### ISSUE THREAD

**Issue by ctron** [librariesio/libraries.io#1449]
Steps done:

* Create new account with GitHub
* Navigate to repositories
* Select one repository with a Java/Maven project

Expected behavior:

* Maven dependencies shown

Actual behavior:

* 'bower.json' dependencies shown for a different project on GitHub

**Comment by andrew** [comment]
This is my fault, will get it fixed up this afternoon

**Comment by andrew** [comment]
@ctron just deployed a fix for this

**Comment by ctron** [comment]
Looks better. Thanks.
