### ISSUE TITLE
Add copyright info to .ABOUT files (enhancement)

### ISSUE THREAD

**Issue by maxbrito** [librariesio/libraries.io#1451]
Hello,

The function to export the information about a library as an .ABOUT file is very useful as any person without third-party tools can download these files with the information needed for cataloging their libraries.

However, one detail that I noticed is the lack of a copyright field. For example, on the case of JQuery the outputted .ABOUT file does not report who is the owner of that software. Right now this field is being done by hand after investigation, perhaps exists a manner for Libraries.io to automagically fill the copyright field?

In terms of relevance and using JQuery as example, we would know that the copyright holder is the JQuery foundation so this information would likely be more relevant than having just the names of individual committers. Ideally, the organization name would appear first, followed by these committers.

If you see this possible, would certainly mean the world for increasing the adoption of .ABOUT files to describe what is being used by a given project.

Many thanks.

**Comment by andrew** [comment]
Moving this to the [Backlog](https://github.com/librariesio/libraries.io/blob/master/Backlog.md) as we'd still like to implement it but can't see that happening in the near future.
