### ISSUE TITLE
Sync between libraries.io and github is not working

### ISSUE THREAD

**Issue by diwakarpuri** [librariesio/libraries.io#1453]
## Bugs
Sync is not working for my repositories

Repository One:
https://libraries.io/github/diwakarpuri/angular2
https://github.com/diwakarpuri/angular2
(ReadMe file is not syncing) 

Repository Two:
https://libraries.io/github/diwakarpuri/anugular2
https://github.com/diwakarpuri/anugular2
(ReadMe file is not syncing)

**Comment by abrophy** [comment]
I can't find the listed repositories on github, also considering further info or follow up, I think this issue is safe to close @andrew

**Comment by andrew** [comment]
Thanks @abrophy
