### ISSUE TITLE
MetaCPAN old API being depreciated soon

### ISSUE THREAD

**Issue by ranguard** [librariesio/libraries.io#1470]
You are currently hitting the old (soon to be discontinued) version of the metacpan API:

E.g.:
```
x.x.x.x [30/May/2017:02:36:02 +0100] "GET /v0/release/_search?q=status:latest&fields=distribution&sort=date:desc&size=100 HTTP/1.1" 200 5485 "-" "Libraries.io Watcher" 326573103 0.029 443 api.metacpan.org 0.029
```

Please see this announcement and update accordingly:

https://github.com/metacpan/metacpan-api/wiki/MetaCPAN-V1-announcement-and-migration-plan

We can be found on #metacpan - irc.perl.org if you need any help

**Comment by andrew** [comment]
@ranguard thanks for the heads up, I've updated the code to use the new domain, just deploying it now.
