### ISSUE TITLE
This project has no dependencies.

### ISSUE THREAD

**Issue by szabolcsdombi** [librariesio/libraries.io#1504]
Dependencies are listed for my project however those are dependencies of the examples **only**.

The dependencies only appear on [https://libraries.io/github/cprogrammer1994/ModernGL](https://libraries.io/github/cprogrammer1994/ModernGL). ❌
The pypi version [https://libraries.io/pypi/ModernGL](https://libraries.io/pypi/ModernGL) detects no dependencies. ✔️

- The correct value is `Dependencies 0`

![image](https://user-images.githubusercontent.com/11232402/27173202-2580056c-51b8-11e7-863e-f0b67a52e65d.png)

## Bugs
Before submitting a bug report:

- [x] Double-check that the bug is persistent,
- [x] Double-check the bug hasn't already been reported [on our issue tracker](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+org%3Alibrariesio), they *should* be labelled `bug` or `bugsnag`.

### For python projects

- detect the dependencies from the requirement.txt in the root directory
- detect the dependencies from the requirement.txt next to the setup.py (same as above)
- detect the dependencies from the setup.py (install_requires=...)

Not sure if there are more.

**Comment by brainwane** [comment]
Not sure whether this is now fixed? https://libraries.io/pypi/moderngl doesn't seem to detect any dependencies.

**Comment by brainwane** [comment]
And https://libraries.io/github/cprogrammer1994/ModernGL now gives a 404.

**Comment by cprogrammer1994** [comment]
https://libraries.io/github/moderngl/moderngl

![image](https://user-images.githubusercontent.com/11232402/61606700-436da400-ac54-11e9-8b25-b2f6242229f1.png)
