### ISSUE TITLE
Add page of metrics for supporters 

### ISSUE THREAD

**Issue by BenJam** [librariesio/libraries.io#1541]
Add a page tracking/graphing useful stats for supporters and extenders tracking:

- visits to Libraries.io (analytics)
- number of registered users 
- number of subscriptions (tracked repositories)
- contributions to libraries.io (github)
- repositories monitored
- updates processed

May actually be worth pushing all the `/admin` page content out publicly. There's nothing in there that's individually identifiable.

**Comment by andrew** [comment]
Moving this to the [Backlog](https://github.com/librariesio/libraries.io/blob/master/Backlog.md) as we'd still like to implement it but can't see that happening in the near future.
