### ISSUE TITLE
Allow emails to be turned off by package manager type

### ISSUE THREAD

**Issue by kpfefferle** [librariesio/libraries.io#1543]
It would be nice to be able to enable/disable email notifications for specific package managers. For example, I have [a Javascript project](https://libraries.io/github/kpfefferle/ember-octicons) where the source code contains 1 dependency in `bower.json` and ~20 dependencies in `package.json`. Libraries.io is tracking 806(!) dependencies for this project, the vast majority of which are being pulled from the `yarn.lock` file as transitive dependencies.

While I find the emails regarding updates to my direct dependencies to be extremely useful, email notifications for these several hundred transitive dependencies are much less so. If I could turn off email notifications from libraries.io for Yarn while leaving them enabled for Bower and NPM, then the signal to noise ratio for these emails would dramatically increase for me.

I propose adding the ability to turn emails on/off by package manager, as this seems like the clearest line to draw for common use cases such as NPM/Yarn.

**Comment by andrew** [comment]
Moving this to the [Backlog](https://github.com/librariesio/libraries.io/blob/master/Backlog.md) as we'd still like to implement it but can't see that happening in the near future.
