### ISSUE TITLE
Internal Server Error with GitHub

### ISSUE THREAD

**Issue by AlexanderNeumann** [librariesio/libraries.io#1545]
I can't tell more since 

"500 Internal Server Error
If you are the administrator of this website, then please read this web application's log file and/or the web server's log file to find out what went wrong." 

is all what I see when I visit libraries.io 

This only happens when I am logged in with my GitHub account.

**Comment by andrew** [comment]
@AlexanderNeumann which url are you getting that error on?

**Comment by AlexanderNeumann** [comment]
![ftzrfyecqg2kp_pkgrpeha](https://user-images.githubusercontent.com/10010710/27646432-e336f62c-5c28-11e7-8550-bf74db9a433e.png)

**Comment by AlexanderNeumann** [comment]
Any updates ? 😬

**Comment by McPringle** [comment]
I'm logged in with GitHub, too and https://libraries.io works, https://libraries.io/repositories works, but when I click on the `Monitor` button next to an unmonitored public repository to activate monitoring, https://libraries.io/watch/25868593 responds with `HTTP/2.0 500`.

**Comment by andrew** [comment]
Sorry for the delays

@AlexanderNeumann @pietroalbini I believe I've pinpointed the issue you've been having, just deployed a fix for it now

@McPringle would you be able to open a separate for your bug as I believe it's unrelated to this one?

**Comment by pietroalbini** [comment]
Thank you @andrew! It works now. There is #1617 which seems to be related to this bugfix though.

**Comment by andrew** [comment]
@pietroalbini will get that fixed up shortly
