### ISSUE TITLE
Graph: LOC vs Issues + PRs, controlled by Github Stars

### ISSUE THREAD

**Issue by nateberkopec** [librariesio/libraries.io#1561]
I was told to do this!

Controlling for GH stars, what would a graph of the lines-of-code of a project versus the number of its pull requests and issues look like?

I assume you have this data so that's why I asked you :D

**Comment by andrew** [comment]
Moving this to the [Backlog](https://github.com/librariesio/libraries.io/blob/master/Backlog.md) as we'd still like to implement it but can't see that happening in the near future.
