### ISSUE TITLE
Thanks, but not works for me....

### ISSUE THREAD

**Issue by MatiasGandolfo** [librariesio/libraries.io#1585]
Thanks for your works... 
For my not works... say invalid token... i tray all...

Any idea?

**Comment by andrew** [comment]
Can you provide more details?

**Comment by MatiasGandolfo** [comment]
Thanks!!!! For your anser….

i install the workflow

put

t:token 34506cf4e9c065aff3f2a9df2e5e75961bce2e75


and alfre says invalid token….

i tray a new token but nothing….


Saludos.

______________________________________________________________
[image: Actors Studio Teatro™] <http://www.actors-studio.org>
*Matias Gandolfo* <teatro@actors-studio.org>  Director General

Av. Díaz Vélez 3842 - CABA - ARGENTINA - (54) 11 - 4983-9883 -
WhatsApp +5491137993204
De Lunes a Viernes, menos los Miécoles de 17 a 20 hs.
[image: Facebook] <http://facebook.com/matias.gandolfo> [image: Twitter]
<http://twitter.com/matiasgandolfo/>   * ESTUDIO DE CARLOS GANDOLFO PARA LA
PREPARACIÓN DEL ACTOR *
* ACTORS STUDIO TEATRO™   *
[image: Like] *Recomendación del mes Julio | Humberto Maturana
<http://www.actors-studio.org/web/videos/varios/55-humberto-maturana-i.html>
*













De: Andrew Nesbitt <notifications@github.com> <notifications@github.com>
Responder: librariesio/libraries.io
<reply@reply.github.com>
<reply@reply.github.com>
Fecha: 12 de julio de 2017 at 16:49:39
Para: librariesio/libraries.io <libraries.io@noreply.github.com>
<libraries.io@noreply.github.com>
CC: MatiasGandolfo <gandolfomatias@gmail.com> <gandolfomatias@gmail.com>,
Author <author@noreply.github.com> <author@noreply.github.com>
Asunto:  Re: [librariesio/libraries.io] Thanks, but not works for me....
(#1585)

Can you provide more details?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/librariesio/libraries.io/issues/1585#issuecomment-314877244>,
or mute the thread

**Comment by andrew** [comment]
I'm not sure what "alfre" is?

**Comment by MatiasGandolfo** [comment]
You create workflow TODOIST for ALFRED?


Saludos.

______________________________________________________________
[image: Actors Studio Teatro™] <http://www.actors-studio.org>
*Matias Gandolfo* <teatro@actors-studio.org>  Director General

Av. Díaz Vélez 3842 - CABA - ARGENTINA - (54) 11 - 4983-9883 -
WhatsApp +5491137993204
De Lunes a Viernes, menos los Miécoles de 17 a 20 hs.
[image: Facebook] <http://facebook.com/matias.gandolfo> [image: Twitter]
<http://twitter.com/matiasgandolfo/>   * ESTUDIO DE CARLOS GANDOLFO PARA LA
PREPARACIÓN DEL ACTOR *
* ACTORS STUDIO TEATRO™   *
[image: Like] *Recomendación del mes Julio | Humberto Maturana
<http://www.actors-studio.org/web/videos/varios/55-humberto-maturana-i.html>
*













De: Andrew Nesbitt <notifications@github.com> <notifications@github.com>
Responder: librariesio/libraries.io
<reply@reply.github.com>
<reply@reply.github.com>
Fecha: 12 de julio de 2017 at 16:57:02
Para: librariesio/libraries.io <libraries.io@noreply.github.com>
<libraries.io@noreply.github.com>
CC: MatiasGandolfo <gandolfomatias@gmail.com> <gandolfomatias@gmail.com>,
Author <author@noreply.github.com> <author@noreply.github.com>
Asunto:  Re: [librariesio/libraries.io] Thanks, but not works for me....
(#1585)

I'm not sure what "alfre" is?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/librariesio/libraries.io/issues/1585#issuecomment-314879117>,
or mute the thread

**Comment by andrew** [comment]
I think you're reporting this on the wrong repository, is this what you're looking for https://github.com/moranje/alfred-workflow-todoist
