### ISSUE TITLE
Add lightweight 'autocomplete' API endpoint

### ISSUE THREAD

**Issue by BenJam** [librariesio/libraries.io#1616]
Use case: I am amending a package manifest in my favourite text-editor/IDE. I'd like to autocomplete the name and perhaps see a little information about the package if multiple options exist. 

To enable someone to add this we might want a very small, fast API endpoint that returns an array of matched packages that can include a set of additional fields (a la the [cdnjs API](https://cdnjs.com/api)).

**Comment by andrew** [comment]
👍  Related to https://github.com/librariesio/libraries.io/issues/124

**Comment by andrew** [comment]
Moving this to the [Backlog](https://github.com/librariesio/libraries.io/blob/master/Backlog.md) as we'd still like to implement it but can't see that happening in the near future.
