### ISSUE TITLE
?size=40 displayed instead of the avatar

### ISSUE THREAD

**Issue by pietroalbini** [librariesio/libraries.io#1617]
After fixing #1545 I'm able to access the website again, but it's showing `?size=40` instead of the avatar on the right side of the navbar. It's strange, because I have an avatar here on GitHub and I can't seem to find a place to upload a custom one for libraries.io...

![screenshot at 17-59-47](https://user-images.githubusercontent.com/2299951/28471733-67dc9360-6e3e-11e7-9ddd-f8adbbeaa240.png)

**Comment by andrew** [comment]
@pietroalbini have deployed a fix for that, are you still seeing `?size=40`?

**Comment by pietroalbini** [comment]
Nope, it's fixed now!
Thank you for making this useful service :)

**Comment by andrew** [comment]
👍
