### ISSUE TITLE
NPM Packages Showing Incorrect Contributors

### ISSUE THREAD

**Issue by Swivelgames** [librariesio/libraries.io#1644]
After checking to see what types of search results showed for some of my NPM packages, to hopefully improve SEO, I came across their listening on `libraries.io`.

I was a bit worried when I noticed that ***none of them*** were attributed to me! Now, these are open source projects, and part of making them so is to contribute them to the overall community in the hopes that, as a community, we can improve the world of developers in the long term. After all, Open Sourcing is in some ways a selfless move. However, proper attribution is only fair, and I was a bit perplexed when I initially noticed this.

I was approached by @andrew to throw this up as a bug, but if this is the wrong repo, I'll gladly move it to the appropriate repo.

## Bugs

As of composing this, these two in particular were incorrectly (presumably automatically) attributed to other authors:

* [`nui`](https://libraries.io/npm/nui) (incorrectly attributed to [`Trimeego`](https://libraries.io/github/Trimeego))
* [`nui-simple`](https://libraries.io/npm/nui-simple) (incorrectly attributed to [`silviot`](https://libraries.io/github/))

Additionally, `nui-simple` appears to have a link to `Python` under its heading, which has me curious if it was incorrectly categorized in the wrong language, albeit not as serious as an issue imho.

I'm not here to stir up trouble, be dramatic, or cause a scene, but I will say I was pretty disappointed to see the misattribution. I hope there's understanding and that this will be resolved soon. Especially given that this site comes up under search results for my packages, I'm actually planning on pushing the public announcement and "campaigning" for its release, albeit only temporarily, because I'd much rather not have people land on your site only to question my integrity related to authorship of these packages.

As a developer, though, I totally understand that bugs arise in every application, some a little more perplexing than others! At the end of the day, we're all developers hoping to build great applications, and I wish you all the best in doing so! `Libraries.io` looks like a pretty intriguing site that I may be interested in utilizing in the future.

**Comment by Swivelgames** [comment]
@andrew This is the ticket you requested.

**Comment by andrew** [comment]
@Swivelgames thanks for reporting, this is definitely a bug and a slightly weird one, investigating now, it seems that the npm packages have picked up a link to a github repo rather than a gitlab repo, hence the wrong contributors and language.

**Comment by andrew** [comment]
Quick update, looks like a bug in the gitlab api client we were using caused some double escaping in generated urls, which explains some of the weirdness, I've removed the incorrect data, just fixing up the readmes. We don't currently have support for showing the commiters to gitlab projects yet so no-one will show up on those pages as authors.

**Comment by andrew** [comment]
Readmes are showing again now too

**Comment by Swivelgames** [comment]
Awesome! Thanks a lot for taking a look at this @andrew !
