### ISSUE TITLE
"This repository has been removed" error

### ISSUE THREAD

**Issue by alorence** [librariesio/libraries.io#1647]
Hi,

I just noticed [one of my repositories](https://libraries.io/github/alorence/django-modern-rpc) displays the error:

> This repository has been removed and cannot be used anymore.

Actually, [it was not](https://github.com/alorence/django-modern-rpc). I triggered a resync, but same error message is displayed. In addition, button "Monitor dependencies" land to an error 500.

Can you help?

**Comment by andrew** [comment]
@alorence I'll look into this for you

**Comment by alorence** [comment]
Thanks 👍

**Comment by andrew** [comment]
@alorence it's no longer marked as removed, I've made a not to investigate why it got marked that way, thanks for reporting it.
