### ISSUE TITLE
videorecording with logo

### ISSUE THREAD

**Issue by srin1969** [librariesio/libraries.io#1660]
Thanks for taking the time to raise an issue. This template should guide you through the process of submitting a bug, enhancement or feature request. Please erase any part of this template that is not relevant to your issue. 

## Bugs
Before submitting a bug report:

- [ ] Double-check that the bug is persistent,
- [ ] Double-check the bug hasn't already been reported [on our issue tracker](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+org%3Alibrariesio), they *should* be labelled `bug` or `bugsnag`.

If you have completed those steps then please replace this section with a description of the steps taken to recreate the bug, the expected behavior and the observed behavior.

## Enhancements and Features

Before submitting an enhancement or feature request:

- [ ] Check that the enhancement is not already [in our issue tracker](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+org%3Alibrariesio), they should be labelled 'enhancement'., 
- [ ] For large feature requests, check that your request aligns with our strategy http://docs.libraries.io/strategy.
 
If you have complete the above step then please replace this section with a description of your proposed enhancement or feature, the motivation for it, an approach and any alternative approaches considered, and whether you are willing and able to create a pull request for it. Note that we may close this issue if it's not something we're planning on working on.

**Comment by andrew** [comment]
Can you provide more details and follow the issue template @srin1969

**Comment by srin1969** [comment]
/*
*  Copyright (c) 2015 The WebRTC project authors. All Rights Reserved.
*
*  Use of this source code is governed by a BSD-style license
*  that can be found in the LICENSE file in the root of the source
*  tree.
*/

// This code is adapted from
// https://rawgit.com/Miguelao/demos/master/mediarecorder.html

'use strict';

/* globals MediaRecorder */

var mediaSource = new MediaSource();
mediaSource.addEventListener('sourceopen', handleSourceOpen, false);
var mediaRecorder;
var recordedBlobs;
var sourceBuffer;
var recordedoverBlobs;
var frames = [];
var stream;
var recordedtime;

var gumVideo = document.querySelector('video#gum');
var recordedVideo = document.querySelector('video#recorded');
var timer = document.querySelector('h3#timer');
var recordButton = document.querySelector('button#record');
//var overlaylogoButton = document.querySelector('button#overlaylogo');
var playButton = document.querySelector('button#play');
var downloadButton = document.querySelector('button#download');
recordButton.onclick = toggleRecording;
//overlaylogoButton.onclick = overlaylogoRec;
playButton.onclick = play;
downloadButton.onclick = download;

// window.isSecureContext could be used for Chrome
var isSecureOrigin = location.protocol === 'https:' ||
location.hostname === 'localhost';
if (!isSecureOrigin) {
  alert('getUserMedia() must be run from a secure origin: HTTPS or localhost.' +
    '\n\nChanging protocol to HTTPS');
  location.protocol = 'HTTPS';
}

var constraints = {
  audio: true,
  video: true
};

function handleSuccess(stream) {
  recordButton.disabled = false;
  console.log('getUserMedia() got stream: ', stream);
  window.stream = stream;
  if (window.URL) {
    gumVideo.src = window.URL.createObjectURL(stream);
  } else {
    gumVideo.src = stream;
  }
}

function handleError(error) {
  console.log('navigator.getUserMedia error: ', error);
}

navigator.mediaDevices.getUserMedia(constraints).
    then(handleSuccess).catch(handleError);

function handleSourceOpen(event) {
  console.log('MediaSource opened');
  sourceBuffer = mediaSource.addSourceBuffer('video/webm; codecs="vp9"');
  console.log('Source buffer: ', sourceBuffer);
}

recordedVideo.addEventListener('error', function(ev) {
  console.error('MediaRecording.recordedMedia.error()');
  alert('Your browser can not play\n\n' + recordedVideo.src
    + '\n\n media clip. event: ' + JSON.stringify(ev));
}, true);

function handleDataAvailable(event) {
  if (event.data && event.data.size > 0) {
    recordedBlobs.push(event.data);
	//console.log('event.data',event.data);
  }
}

function handleStop(event) {
  console.log('Recorder stopped: ', event);
}
var seconds = 0, updateTimer = function(){
                    $('#timer').text(seconds < 10 ? '0' + seconds : seconds);
                };
                
				/* timer = setInterval(function () {
                    seconds++; updateTimer();
				}, 1000); */
               
/* var seconds = 0, updateTimer = function(){
                    $('#timer').text(seconds < 10 ? '0' + seconds : seconds);
                };
                timer = setInterval(function () {
                    seconds++;
					localStorage.setItem("seconds",seconds);
                    updateTimer();
					if(seconds==timersecondlimit){
				console.log(seconds);
				$('#stopBtn').trigger('click');
				
				}
                }, 1000);
                updateTimer(); */
function toggleRecording() {
  if (recordButton.textContent === 'Start Recording') {
    startRecording();
	
  } else {
    stopRecording();
    recordButton.textContent = 'Start Recording';
    playButton.disabled = false;
	//overlaylogoButton.disabled = false;
    downloadButton.disabled = false;
	//mp4conv();
  }
}

function startRecording() {
  recordedBlobs = [];
  var options = {mimeType: 'video/webm;codecs=vp9'};
  if (!MediaRecorder.isTypeSupported(options.mimeType)) {
    console.log(options.mimeType + ' is not Supported');
    options = {mimeType: 'video/webm;codecs=vp8'};
    if (!MediaRecorder.isTypeSupported(options.mimeType)) {
      console.log(options.mimeType + ' is not Supported');
      options = {mimeType: 'video/webm'};
      if (!MediaRecorder.isTypeSupported(options.mimeType)) {
        console.log(options.mimeType + ' is not Supported');
        options = {mimeType: ''};
      }
    }
  }
  try {
    mediaRecorder = new MediaRecorder(window.stream, options);
  } catch (e) {
    console.error('Exception while creating MediaRecorder: ' + e);
    alert('Exception while creating MediaRecorder: '
      + e + '. mimeType: ' + options.mimeType);
    return;
  }
  console.log('Created MediaRecorder', mediaRecorder, 'with options', options);
  recordButton.textContent = 'Stop Recording';
  playButton.disabled = true;
  //overlaylogoButton.disabled = true;
  downloadButton.disabled = true;
  mediaRecorder.onstop = handleStop;
  mediaRecorder.ondataavailable = handleDataAvailable;
  mediaRecorder.start(10); // collect 10ms of data
  console.log('MediaRecorder started', mediaRecorder);
  timer = setInterval(function () {
                    seconds++; updateTimer();
				}, 1000);
}

function stopRecording() {
  mediaRecorder.stop();
  console.log('Recorded Blobs: ', recordedBlobs);
  recordedVideo.controls = true;
  clearInterval(timer);
 
  overlaylogoRec();
 
}

/* function toggleoverlay() {
  if (overlaylogoButton.textContent === 'logooverlay') {
		
	} else {
    stopRecording();
    overlaylogoButton.textContent = 'logo Over Lay';
	recordButton.disabled = false;
    playButton.disabled = false;
	overlaylogoButton.disabled = false;
    downloadButton.disabled = false;
  }
} */
var arrayBuffer;
/* function mp4conv(){
	/* var superBuffer = new Blob(recordedBlobs, {type: 'video/webm'});
	arrayBuffer = new ArrayBuffer(superBuffer); */
	/* initWorker();
  videosample(); */
  
//runCommand("-i input.webm -vf showinfo -strict -2 output.mp4");} 

function overlaylogoRec()
{
	recordedtime=seconds;
  console.log(recordedtime);
	seconds=0;
	var superBuffer = new Blob(recordedBlobs, {type: 'video/webm'});
		console.log('superbuffer', superBuffer);
		logooverlay(superBuffer);
	//var url1 = window.URL.createObjectURL(superBuffer);
	
 // recordedVideo.src = window.URL.createObjectURL(superBuffer);
	console.log('overlay recording')
}

function play() {
	//mp4conv();
  var superBuffer = new Blob(recordedBlobs, {type: 'video/webm'});
  recordedVideo.src = window.URL.createObjectURL(superBuffer);
}

function download() {
  var blob = new Blob(recordedBlobs, {type: 'video/webm'});
  var url = window.URL.createObjectURL(blob);
  var a = document.createElement('a');
  a.style.display = 'none';
  a.href = url;
  a.download = 'test.webm';
  document.body.appendChild(a);
  a.click();
  setTimeout(function() {
    document.body.removeChild(a);
    window.URL.revokeObjectURL(url);
  }, 100);
}
	
	
	var video = document.createElement('video');
	//var audioStream;
	//var videoPreview = document.getElementById('video-preview');
	// overlay image
	var logoImage = document.getElementById('logo-image');
	var waitImage = document.getElementById('wait-image');
	// canvas
	var canvas = document.createElement('canvas');
	
	var audioCtx = new AudioContext();
  // create a stream from our AudioContext
  //var dest = audioCtx.createMediaStreamDestination(canvas);
  //audioStream = dest.stream;
    var context = canvas.getContext('2d');
	// absolute position of canvas
	canvas.style = 'position: absolute; top: 0; left: 0; opacity: 0;';
    document.body.appendChild(canvas);
	
	// caputuring of canvas stream MediaStream = canvas.captureStream(frameRate);
	var canvasStream = canvas.captureStream(25);
	// second step: either use captureStream or WebAudio or getUserMedia
var audioStream = audioCtx.createMediaStreamDestination(stream);
	
	
	//canvasStream.getAudioTracks();
	//canvasStream.addTrack(audioStream.getAudioTracks());
	// last step: merge both audio/video tracks into single MediaStream
	var finalStream = new MediaStream();
		canvasStream.getVideoTracks().forEach(function(track) {
			finalStream.addTrack(track);
		});
		audioStream.getAudioTracks().forEach(function(track) {
			finalStream.addTrack(track);
			});

	
	
	console.log('created media recorder', finalStream);
	//stream=canvasStream;
	var recorder = new MediaRecorder(finalStream, {type : 'video/webm'});
	function handleoverSuccess(superBuffer) {
	console.log('getUserMedia() got stream: ', superBuffer);
  	video.src=window.URL.createObjectURL(superBuffer);
	}	
	
	function handleoverError(error) {
	console.log('navigator.getUserMedia error: ', error);
	}
	
	function handleoverSourceOpen(event) {
	  console.log('MediaSource opened');
	  sourceBuffer = mediaSource.addSourceBuffer('video/webm; codecs="vp8"');
	  console.log('Source buffer: ', sourceBuffer);
	}

	video.addEventListener('error', function(ev) {
	  console.error('MediaRecording.recordedMedia.error()');
	  alert('Your browser can not play\n\n' + video.src
		+ '\n\n media clip. event: ' + JSON.stringify(ev));
	}, true);

	function handleoverDataAvailable(event) {
	  if (event.data && event.data.size > 0) {
		recordedoverBlobs.push(event.data);
		//console.log('event.data',event.data);
	  }
	}
	
	function handleoverStop(event) {
	  console.log('Recorder stopped: ', event);
	}
	
	/* function playover()
	{
	videoPreview.controls = true;
	var superBuffer = new Blob(recordedoverBlobs, {type: 'video/webm'});
    videoPreview.src = window.URL.createObjectURL(superBuffer);
    videoPreview.play();
	videoPreview.controls = true;
	} */
	
	function stoprecorder() {
	recorder.stop();
	console.log('Recorded over Blobs: ', recordedoverBlobs);
	//videoPreview.controls = true;
	recordButton.disabled = false;
	playButton.disabled = false;
	//overlaylogoButton.disabled = false;
	downloadButton.disabled = false;
	//videoPreview.controls = true;
	//playover();
	recordedBlobs=recordedoverBlobs;
	console.log('record overlay to recordblobs', recordedBlobs);
	}
		
function logooverlay(superBuffer){
	//stream=superBuffer;
	recordedoverBlobs = [];
	//intializing of preview
	
	var constraints = {
		  audio: true,
		  video: true
		};
	
	navigator.mediaDevices.getUserMedia(constraints).
    then(handleoverSuccess).catch(handleoverError);
	recordButton.disabled = true;
	playButton.disabled = true;
	//overlaylogoButton.disabled = true;
	downloadButton.disabled = true;
	recorder.onstop = handleoverStop;
	recorder.ondataavailable = handleoverDataAvailable;
	recorder.start(10); // collect 10ms of data
	console.log('MediaoverRecorder started', recorder);
	//var looper= new loopover();
	looper();
	var tries=0;
	function looper()
	{ 
	// creating a canvas writing loop
	setTimeout(function(){
			//if(recorder) return false;
			
			tries += 10;
			canvas.width = 640;
			canvas.height = 480;
			// show logo.png for one second
			context.drawImage(video, 0, 0, canvas.width, canvas.height);
				// context.drawImage(logoImage, parseInt(canvas.width / 2) - parseInt(logoImage.width / 2), canvas.height - logoImage.height - 10);
				// context.drawImage(logoImage, parseInt(canvas.width / 2) - parseInt(32 / 2), canvas.height - 32 - 10, 32, 32);
			context.drawImage(logoImage, 410, 430, 200, 36);
			//repeat (looper)
			//console.log(tries);
			if(tries < (recordedtime*1000))
			{
				looper();
				console.log(tries);
			}
			if(recorder.ended || tries==(recordedtime*1000)) {
		stoprecorder(); console.log('looper stopped at tries=nsec');}
			console.log(tries);			
			},10) 
	}
	 

	
	
	
	/*  var tries = 0;
    (function looper() {
       if(!recorder){stoprecorder(); console.log('looper stop at no recording');}  // ignore/skip on stop-recording
	//frames = []; // clear existing frames;
		tries += 10;
        canvas.width = 640;
        canvas.height = 480;
        // show logo.png for one second
        if(tries>0) {
    context.drawImage(video, 0, 0, canvas.width, canvas.height);
            // context.drawImage(logoImage, parseInt(canvas.width / 2) - parseInt(logoImage.width / 2), canvas.height - logoImage.height - 10);
            // context.drawImage(logoImage, parseInt(canvas.width / 2) - parseInt(32 / 2), canvas.height - 32 - 10, 32, 32);
    context.drawImage(logoImage, 410, 430, 200, 36);
		}
		else
		{
			context.drawImage(waitImage, 0, 0, canvas.width, canvas.height);
		   console.log('no video', tries);
		}
    
		if(tries==10000) {
		stoprecorder(); console.log('looper stopped at tries=10000');} 
        //repeat (looper)
        setTimeout(looper, 10);
		console.log(tries);
	})();  */
	}

**Comment by srin1969** [comment]
unable to get the audio after overlaying of png
