### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by GemmaKateRooney** [librariesio/libraries.io#1742]
Thanks for taking the time to raise an issue. This template should guide you through the process of submitting a bug, enhancement or feature request. Please erase any part of this template that is not relevant to your issue. 

## Bugs
Before submitting a bug report:

- [ ] Double-check that the bug is persistent,
- [ ] Double-check the bug hasn't already been reported [on our issue tracker](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+org%3Alibrariesio), they *should* be labelled `bug` or `bugsnag`.

If you have completed those steps then please replace this section with a description of the steps taken to recreate the bug, the expected behavior and the observed behavior.

## Enhancements and Features

Before submitting an enhancement or feature request:

- [ ] Check that the enhancement is not already [in our issue tracker](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+org%3Alibrariesio), they should be labelled 'enhancement'., 
- [ ] For large feature requests, check that your request aligns with our strategy http://docs.libraries.io/strategy.
 
If you have complete the above step then please replace this section with a description of your proposed enhancement or feature, the motivation for it, an approach and any alternative approaches considered, and whether you are willing and able to create a pull request for it. Note that we may close this issue if it's not something we're planning on working on.

**Comment by GemmaKateRooney** [comment]
Thank you for creating this great tool. I was wondering if it was possible for you to create an "oracle" feature, similar to the one they have on Gedmatch? 
Regards
Gemma Kate Rooney

**Comment by andrew** [comment]
@GemmaKateRooney can you provide more information?

**Comment by GemmaKateRooney** [comment]
@Andrew 
The Gedmatch site appears to be down today, but when using the calculators they also have "oracle " options to refine the results further. 
The oracle function at Gedmatch calculates your results to provide a result with the group you most closely resemble. 
Oracle will list your admixture results, then something called Single Population sharing, and finally Mixed Mode Population Sharing.

Single Population Sharing attempts to pinpoint a specific, single population that your DNA most closely matches, with a list of the top 20. The distance will tell you how closely you match each group, so the smaller the distance number is, the more closely you match. It is assuming your ancestors all came from the same area/population.
Mixed Mode Population Sharing will show you your top 20 of two specific, combined populations in order of how closely you match those populations. It is assuming your ancestors came from more than one location/population. Again, the distance will tell you how closely you match this combo of populations, while the percentage will tell you how much of your DNA matched which population. 

Oracle 4
Oracle 4 is essentially the same as Oracle, except it expands on it by providing combinations of 3 and 4 specific populations. The single and double combinations can be different from original Oracle though, so don’t bypass Oracle thinking you’ll get that and more with Oracle 4, it’s best to examine both.

Using 1 population approximation works the same as Single Population Sharing in Oracle, but I’ve noticed the results are sometimes different, so they’re obviously using a slightly different calculation. Reading the results work the same though: they are showing you a list of specific populations you most closely match, with the distant showing you just how closely you match.
Using 2 population approximation also works the same as Mixed Mode Population Sharing but again, results may vary, and for some reason only lists your top 1 result instead of the top 20.
Using 3 population approximation works the same as 2, but with a combination of 3 populations instead. It only lists one result. You may sometimes find two of the three populations are the same.
Using 4 population approximation obviously uses a combination of 4 specific populations you most closely match and lists your top 20 combos. This was designed especially for people who have 4 grandparents from 4 different places but it can also work well if most of your ancestry is mainly from 4 different places/populations.

Be aware that the results from Oracle and Oracle 4 will vary depending on what admixture calculator you used, which is why they are found on the admixture results page, and not as a separate calculator. Also keep in mind the results are speculative, but I have found they do often make some sense, and in some cases, can be remarkably accurate. 
Thank you for your help. 
Gemma

**Comment by GemmaKateRooney** [comment]
@Andrew
As described here-
http://genealogical-musings.blogspot.co.uk/2017/04/finally-gedmatch-admixture-guide.html?m=1

**Comment by GemmaKateRooney** [comment]
Hi Andrew, 
Thank you for your reply. 

The Gedmatch site appears to be down today, but when using the calculators they also have "oracle " options to refine the results further.
The oracle function at Gedmatch calculates your results to provide a result with the group you most closely resemble.


Oracle will list your admixture results, then something called Single Population sharing, and finally Mixed Mode Population Sharing.

Single Population Sharing attempts to pinpoint a specific, single population that your DNA most closely matches, with a list of the top 20. The distance will tell you how closely you match each group, so the smaller the distance number is, the more closely you match. It is assuming your ancestors all came from the same area/population.
Mixed Mode Population Sharing will show you your top 20 of two specific, combined populations in order of how closely you match those populations. It is assuming your ancestors came from more than one location/population. Again, the distance will tell you how closely you match this combo of populations, while the percentage will tell you how much of your DNA matched which population.

Oracle 4
Oracle 4 is essentially the same as Oracle, except it expands on it by providing combinations of 3 and 4 specific populations. The single and double combinations can be different from original Oracle though, so don’t bypass Oracle thinking you’ll get that and more with Oracle 4, it’s best to examine both.

Using 1 population approximation works the same as Single Population Sharing in Oracle, but I’ve noticed the results are sometimes different, so they’re obviously using a slightly different calculation. Reading the results work the same though: they are showing you a list of specific populations you most closely match, with the distant showing you just how closely you match.
Using 2 population approximation also works the same as Mixed Mode Population Sharing but again, results may vary, and for some reason only lists your top 1 result instead of the top 20.
Using 3 population approximation works the same as 2, but with a combination of 3 populations instead. It only lists one result. You may sometimes find two of the three populations are the same.
Using 4 population approximation obviously uses a combination of 4 specific populations you most closely match and lists your top 20 combos. This was designed especially for people who have 4 grandparents from 4 different places but it can also work well if most of your ancestry is mainly from 4 different places/populations.

Be aware that the results from Oracle and Oracle 4 will vary depending on what admixture calculator you used, which is why they are found on the admixture results page, and not as a separate calculator. Also keep in mind the results are speculative, but I have found they do often make some sense, and in some cases, can be remarkably accurate.
Thank you for your help.
Gemma

http://genealogical-musings.blogspot.co.uk/2017/04/finally-gedmatch-admixture-guide.html?m=1
