### ISSUE TITLE
Subscribing to a project using the API doesn't work

### ISSUE THREAD

**Issue by vincealdrin** [librariesio/libraries.io#1743]
Requesting a POST method, for example on https://libraries.io/api/subscriptions/npm/express returns only this: 
`{
    "include_prerelease": true,
    "created_at": null,
    "updated_at": null,
    "project": null
}`

**Comment by andrew** [comment]
@vincealdrin I'm just deploying a fix for this now, should be live in a few minutes

**Comment by vincealdrin** [comment]
@andrew is it live already? I still get the same thing

**Comment by andrew** [comment]
@vincealdrin yeah it was deployed, are you getting exactly the same response?

**Comment by vincealdrin** [comment]
@andrew yes, or am I doing something wrong?
![image](https://user-images.githubusercontent.com/12383137/31130278-879fdd58-a889-11e7-9a24-7349c2a97bdb.png)

**Comment by vincealdrin** [comment]
@andrew any updates about the fix?

**Comment by isuruf** [comment]
Same here. Doesn't work

**Comment by andrew** [comment]
Just deploying @isuruf's fix from #2087 now

**Comment by isuruf** [comment]
It works. Thanks @andrew
