### ISSUE TITLE
UX Suggestion "Subscribe to releases" button

### ISSUE THREAD

**Issue by mablae** [librariesio/libraries.io#1752]
The subscription button currently only changes by one letter, when subscribing to a package: 

![image](https://user-images.githubusercontent.com/389360/31306848-3ff4f5a2-ab58-11e7-89a7-48c7bfc0ca89.png)

Subscribe**d** to releases: 
![image](https://user-images.githubusercontent.com/389360/31306851-4e3618d0-ab58-11e7-9dd6-64a8241beab2.png)

This change is very subtle and I was not sure right away, if the subscription succeed.
One could also change the color, but I am not sure in which direction. Red seems to be to appropriate here.

Better: 
![image](https://user-images.githubusercontent.com/389360/31306853-59e216a2-ab58-11e7-9da5-8141042c12e4.png)

**Comment by andrew** [comment]
Agreed 👍
