### ISSUE TITLE
Unsubscribe from prereleases button doesn't work

### ISSUE THREAD

**Issue by andys8** [librariesio/libraries.io#1760]
Hopefully this isn't a duplicate issue (I checked) or a mistake as a user, but I'm not able to unsubscribe from prereleases.

##### Steps to reproduce the issue

1.  Login
2. Unsubscribe from the submenu 
![image](https://user-images.githubusercontent.com/13085980/31353237-045679fe-ad32-11e7-922e-58a9896b6ffb.png)
3. Reload the page
4. The checkbox will be enabled again
![image](https://user-images.githubusercontent.com/13085980/31353258-1de9b7be-ad32-11e7-970e-227b774f3dae.png)

E-mails for each release candidate are bothering me while the release notifications are a great feature. Is this a known issue?

**Comment by andrew** [comment]
That looks like a bug to me

**Comment by denarced** [comment]
I have now seen this as well.

**Comment by legopin** [comment]
Are there any updates to this issue?
Still experiencing this bug.

**Comment by andrew** [comment]
Just deploying a fix for that now.
