### ISSUE TITLE
Some libraries without a license in fact specify a license

### ISSUE THREAD

**Issue by kernc** [librariesio/libraries.io#1770]
## Bugs

Some libraries you list as having a non-detectable/Other license, e.g. Python packages [keyring](https://libraries.io/pypi/keyring) and [chardet](https://libraries.io/pypi/keyring), actually clearly mention their license in the README/LICENSE, e.g. [keyring license](https://github.com/jaraco/keyring/search?utf8=%E2%9C%93&q=license&type=), [chardet license](https://github.com/chardet/chardet/blob/master/LICENSE).

**Comment by katzj** [comment]
This should be a lot better as we parse the pypi license classifiers
