### ISSUE TITLE
[Question] "Follows Semver" result of 0

### ISSUE THREAD

**Issue by gep13** [librariesio/libraries.io#1799]
I have a question about the "Follows Semver" score on this project:

https://libraries.io/nuget/Cake/sourcerank

To the best of my knowledge, Cake follows Semver on all of it's packages, so I wondering why we get a score of 0.

Any ideas on what is going on here?

**Comment by katzj** [comment]
The first release was 0.0.0.1-alpha which isn't a valid semver version

**Comment by gep13** [comment]
I have looked at these version numbers a few times, and I honestly didn’t spot that! I think my eyes must have read it as a 3 part version number. Thanks!

**Comment by filips123** [comment]
@katzj
What should I do if there are some old versions of my project that don't follow SemVer?
Is it possible to rename them? How?
What else can I do?

**Comment by gep13** [comment]
@filips123 I had thought that unlisting the package version would have been enough to "fix" the problem, but looks like this would also need to be removed from the libraries database as well.

**Comment by filips123** [comment]
What else could be done if I don't want to delete them? Is it possible to rename them and somehow update libraries database?

---

What is problem with my package [filips123/config-writer ](https://libraries.io/packagist/filips123%2Fconfig-writer)? All [versions](https://github.com/filips123/ConfigWriter/tags) follow SemVer. The only diffreant versions are `v1.x-dev` and `v2.x-dev` but they are added by Packagist so it is not possible to change them.
