### ISSUE TITLE
Add support for Racket packages

### ISSUE THREAD

**Issue by samth** [librariesio/libraries.io#1820]
Racket packages are listed here: https://pkgs.racket-lang.org/

A list of all packages is available at https://pkgs.racket-lang.org/pkgs

All the package metadata is here: https://pkgs.racket-lang.org/pkgs-all

Note that those two URLs return Racket s-expressions, but at least the first is trivial to parse.

**Comment by andrew** [comment]
I don't suppose there's a JSON or XML api on https://pkgs.racket-lang.org/ is there?

**Comment by samth** [comment]
The list of all packages is: https://pkgs.racket-lang.org/pkgs.json

The full data is: http://pkgs.racket-lang.org/pkgs-all.json.gz

**Comment by andrew** [comment]
Oh this was already added by @aelaa! https://libraries.io/racket
