### ISSUE TITLE
The Soundcloud Rubygem page is showing details from another project

### ISSUE THREAD

**Issue by sstarr** [librariesio/libraries.io#1826]
## Steps to reproduce

1. Visit the page for the `soundcloud` Ruby gem: https://libraries.io/rubygems/soundcloud

#### Expected behaviour

- Documentation from `github.com/soundcloud/soundcloud-ruby` is shown

#### Actual behaviour

- Documentation from `gitlab.com/dautovri/TensorFlow-Tutorials` is shown instead

![image](https://user-images.githubusercontent.com/18957/32858934-fab419b2-ca44-11e7-85b9-e76d28d7ac9e.png)

## Further details

- The **contributors** link goes to the committers page for the TensorFlow repo: https://libraries.io/gitlab/dautovri/TensorFlow-Tutorials/contributors
- The committers shown on that page are actually the committers from the `soundcloud` gem repo: https://github.com/soundcloud/soundcloud-ruby/graphs/contributors
- The actual Libraries.io page for the `TensorFlow-Tutorials` repo shows the correct documentation but has many details from the `soundcloud` gem: https://libraries.io/gitlab/dautovri/TensorFlow-Tutorials

## Attempted fix and wild speculation

- Logging in and resyncing https://libraries.io/rubygems/soundcloud made no difference
- Could the issue be caused by cached partials and a clash of ids between GitHub/Rubygems and GitLab?

**Comment by mellisio** [comment]
This doesn't look like it's still a problem.
