### ISSUE TITLE
No results for search 'mockito-java8'

### ISSUE THREAD

**Issue by szpak** [librariesio/libraries.io#1865]
[mockito-java8](https://github.com/szpak/mockito-java8/), a project deployed to [Maven Central](https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22info.solidsoft.mockito%22%20AND%20a%3A%22mockito-java8%22) (aka The Maven Repository) is not found. The last release took place 2017-10-07.

**Comment by mellisio** [comment]
This doesn't look like it's still a problem
