### ISSUE TITLE
Wrong path on index page

### ISSUE THREAD

**Issue by fridde** [librariesio/libraries.io#1875]
I found a minor mistake in the view for the index page:
```<%= link_to 'language'.html_safe, licenses_path %>``` is an obvious error. Can someone with more insight correct that? I guess it should be ```languages_path``` instead of ```licenses_path```.

https://github.com/librariesio/libraries.io/blob/12e7d819f0bbda7cea0fa63bd6f030ba6d9e3ae1/app/views/projects/index.html.erb#L27

**Comment by andrew** [comment]
Thanks for reporting, I've fixed this and it will be deployed by tomorrow
