### ISSUE TITLE
No results on libraries.io

### ISSUE THREAD

**Issue by zuhito** [librariesio/libraries.io#1894]
There aren't some results about the following npm packages. Could you add them into libraries.io?

https://www.npmjs.com/package/node-red-contrib-tplink-smarthome
https://www.npmjs.com/package/node-red-contrib-senseway
https://www.npmjs.com/package/node-red-contrib-json-db
https://www.npmjs.com/package/node-red-contrib-powerbi
https://www.npmjs.com/package/node-red-contrib-onem2m
https://www.npmjs.com/package/node-red-contrib-msg-router
https://www.npmjs.com/package/node-red-contrib-actionflows
https://www.npmjs.com/package/node-red-contrib-udmx
https://www.npmjs.com/package/node-red-contrib-viseo-amazon

**Comment by mellisio** [comment]
This doesn't look like it's still a problem.
