### ISSUE TITLE
No results for search library 'node-red-contrib-iiot-jwt'

### ISSUE THREAD

**Issue by biancode** [librariesio/libraries.io#1913]
Thanks for taking the time to raise an issue. This template should guide you through the process of submitting a bug, enhancement or feature request. Please erase any part of this template that is not relevant to your issue. 

## Bugs
Before submitting a bug report:

- [ x] Double-check that the bug is persistent,
- [x ] Double-check the bug hasn't already been reported [on our issue tracker](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+org%3Alibrariesio), they *should* be labelled `bug` or `bugsnag`.

The Repository is to find via search but not the NPM library.

**Comment by mellisio** [comment]
This doesn't look like it's still a problem.
