### ISSUE TITLE
Stop requiring a user to provide a email

### ISSUE THREAD

**Issue by KOLANICH** [librariesio/libraries.io#1917]
For now when I try to auth it requires a email. I revoke that permission and auth fails.
So we need
1 Make it not to require a email
2 Make 2 signin buttons, one for the ones wiling to provide a email, one for the ones unwiling.

**Comment by andrew** [comment]
The main use case for people signing into Libraries.io is to get emails about their dependency updates, adding 2 buttons would just confuse things.

If you'd like to remove your email after logging in, you can change it to foo@bar.com in the settings: https://libraries.io/account
