### ISSUE TITLE
Support setup.cfg

### ISSUE THREAD

**Issue by KOLANICH** [librariesio/libraries.io#1918]
[setup.cfg is a declarative format for metadata.](https://setuptools.readthedocs.io/en/latest/setuptools.html#configuring-setup-using-setup-cfg-files), no code executiin from setup.py involved to get metadata. There is a parser for it in setuptools.

**Comment by andrew** [comment]
👍 the repository where the parsing action happens is https://github.com/librariesio/bibliothecary

**Comment by brainwane** [comment]
@KOLANICH I suggest you close this issue in favor of https://github.com/librariesio/bibliothecary/issues/459 .
