### ISSUE TITLE
Support pyproject.toml and flit

### ISSUE THREAD

**Issue by KOLANICH** [librariesio/libraries.io#1919]
Another declarative formats.

https://www.python.org/dev/peps/pep-0518/
https://github.com/takluyver/flit

**Comment by andrew** [comment]
👍 the repository where the parsing action happens is https://github.com/librariesio/bibliothecary

**Comment by brainwane** [comment]
@KOLANICH I suggest you close this issue, and open an issue in the bibliothecary repo or use https://github.com/librariesio/bibliothecary/issues/415 .
