### ISSUE TITLE
Expose dependents_count and dependent_repos_count in /api/:platform/:name

### ISSUE THREAD

**Issue by jpopelka** [librariesio/libraries.io#1935]
Hello,

first, let me thank you for wonderful service/software.

I'd like to suggest an enhancement of the API.
The `GET /api/:platform/:name` endpoint does not return all Project's fields that are stored in database.
For example `dependents_count` and `dependent_repos_count` are missing, even they are exposed via web (as `Dependent projects` and `Dependent repositories`).
Other way how to get the counts would be to count all entries in `/api/:platform/:name/dependents` and `/api/:platform/:name/dependent_repositories`, which as you can imagine would take eternity.

**Comment by andrew** [comment]
Good catch, will get that deployed shortly
