### ISSUE TITLE
Open Data link appears to be broken

### ISSUE THREAD

**Issue by jayfk** [librariesio/libraries.io#1947]
The latest Open Data link on https://libraries.io/data appears to be broken.

The page links to https://zenodo.org/record/1068916/files/Libraries.io-open-data-1.1.0.tar.gz which isn'
t available.

It looks like this is the right URL (`1.1.1.tar.gz` instead of `1.1.0.tar.gz`: https://zenodo.org/record/1068916/files/Libraries.io-open-data-1.1.1.tar.gz

**Comment by andrew** [comment]
Thanks for reporting, I've just deployed a fix for it
