### ISSUE TITLE
Repository Monitoring Page Always "currently syncing"

### ISSUE THREAD

**Issue by alunduil** [librariesio/libraries.io#1963]
## Bugs
Before submitting a bug report:

- [x] Double-check that the bug is persistent,
- [ ] Double-check the bug hasn't already been reported [on our issue tracker](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+org%3Alibrariesio), they *should* be labelled `bug` or `bugsnag`.

I'm not sure how I ended up in this state but when I go to my `/repositories` page nothing is up to date and the page is marked as "currently syncing."  Problem is that it's been in that state for over a week with no change.  Not sure if it's something I did in github with permissions (don't think I've touched this) but would love to see it get out of syncing and have up to date information.

If any other information would be helpful, let me know and I'll get it ASAP.

**Comment by uda** [comment]
+1

**Comment by katzj** [comment]
Kicked both of your users into syncing again manually so should be better (as well as updating a bunch of other users that were in a stuck state)

**Comment by librariesio-notifications** [comment]
Hi, I'm also affected by the behavior described above. I've already tried with 2 different GitHub users.

The situation is that the initial sync does not work, I have not yet seen any repositories in my list at `/repositories`, just "Currently syncing" is displayed (and never changes).

**Comment by JamesInDenver** [comment]
Sorry for posting to a closed issue, but I'm seeing this too.  Any way I can un-stuck myself?
