### ISSUE TITLE
Licence inaccuracy : pygal (GPL-3.0 instead of LGPL-3.0)

### ISSUE THREAD

**Issue by camillem** [librariesio/libraries.io#1984]
Hi, 
I have 
- [X] Double-checked that the bug is persistent,
- [X] Double-checked the bug hasn't already been reported 

## Steps to reproduce : 
1) Go to https://libraries.io/pypi/pygal/2.4.0
2) Read iicense field 

## Expected result : 
LGPL-3.0+ (see : 
https://github.com/Kozea/pygal#license
https://pypi.python.org/pypi/pygal/2.4.0
https://github.com/Kozea/pygal/blob/master/COPYING )

## Actual résult : 

GPL-3.0

Thanks, 
Camille

**Comment by andrew** [comment]
Just fixed the bug in https://github.com/librariesio/spdx, deploying it now

**Comment by andrew** [comment]
Fixed!
![screen shot 2018-02-26 at 13 19 15](https://user-images.githubusercontent.com/1060/36672575-ac95dd34-1af7-11e8-8399-1622acf593a9.png)
