### ISSUE TITLE
Curate/group related repo's into 'ecosystems'

### ISSUE THREAD

**Issue by andrew** [librariesio/libraries.io#20]
Group related repos together, i.e. nodebots, not really sure how to do this automatically, most likely community curated.

**Comment by BenJam** [comment]
Possibly best to start with #76

**Comment by andrew** [comment]
Moving this to the [Backlog](https://github.com/librariesio/libraries.io/blob/master/Backlog.md) as we'd still like to implement it but can't see that happening in the near future.
