### ISSUE TITLE
Dependent count differs between GitHub and Libraries.io

### ISSUE THREAD

**Issue by zeke** [librariesio/libraries.io#2005]
GitHub says `electron` has 34,000 dependent repos+. Libraries.io says closer to 12,000. Any idea what might be the cause of this difference, @andrew?

- https://github.com/electron/electron/network/dependents
- https://libraries.io/npm/electron

<img width="608" alt="screen shot 2018-03-03 at 10 38 50 pm" src="https://user-images.githubusercontent.com/2289/36942906-d01461dc-1f33-11e8-8219-bc1362c7ba88.png">

<img width="1203" alt="screen shot 2018-03-03 at 10 39 29 pm" src="https://user-images.githubusercontent.com/2289/36942907-d938133a-1f33-11e8-8083-beda979ecf0d.png">

**Comment by andrew** [comment]
I don't have much visibility on how the dependency counting works in GitHub but we don't check dependencies for forks, any idea of GitHub considered dependencies of forks?
