### ISSUE TITLE
looking forward to the upcoming open data release

### ISSUE THREAD

**Issue by zeke** [librariesio/libraries.io#2011]
Hi people!

Just curious what the timeline is for new data on https://libraries.io/data

<img width="400" alt="screen shot 2018-03-06 at 5 53 57 pm" src="https://user-images.githubusercontent.com/2289/37069265-78e7003c-2167-11e8-8aa7-cd05fbfb6ca1.png">

This data holds answers to questions that GitHub's API cannot yet answer. 🙏

**Comment by andrew** [comment]
Next open data release is coming tomorrow, sorry for the delay!

**Comment by zeke** [comment]
Yayay!

**Comment by andrew** [comment]
🚢 https://zenodo.org/record/1196312/

**Comment by zeke** [comment]
🙏
