### ISSUE TITLE
Cocopods self.project_names method seems do not work

### ISSUE THREAD

**Issue by newthis** [librariesio/libraries.io#2015]
In the app/models/package_manager/cocoa_pods.rb
，the method self.project_names can not fetch the result, it seems that
the url of http://cocoapods.libraries.io/pods.json is down.

**Comment by andrew** [comment]
@newthis is this still unaccessible to you? It's loading for me

**Comment by newthis** [comment]
No, it is unaccessible, I can not fetch the data with either the browser or postman tool.
This is the test result of postman tool. And the location is beijing.
![tyu](https://user-images.githubusercontent.com/9391505/37318116-9431f338-26a3-11e8-93d5-609cc73eaf96.JPG)

**Comment by newthis** [comment]
So is there another way to get the data ?

**Comment by andrew** [comment]
Do you have the status code response or the kind of error that you get?

**Comment by andrew** [comment]
The code for that service is open source over here if you'd like to run it yourself https://github.com/librariesio/cocoapods-api

**Comment by newthis** [comment]
ok, thanks a lot !
