### ISSUE TITLE
Heads-up about the new PyPI

### ISSUE THREAD

**Issue by brainwane** [librariesio/libraries.io#2024]
Hi. I'm the project manager for the new Python Package Index (Warehouse), which is currently in pre-production at http://pypi.org/ . Your code, e.g., https://github.com/librariesio/bibliothecary/issues/76#issuecomment-360407733 , hits the old PyPI API, so I wanted to make sure you knew that, on [the Warehouse roadmap](https://wiki.python.org/psf/WarehouseRoadmap), it looks like the full switch will happen sometime in April. Here's a heads-up about why we're switching, what's changed, and what to expect.

The legacy PyPI site at https://pypi.python.org started in the early 2000s. In recent years, users faced outages, malicious packages, and spam attacks, and the legacy codebase made it hard to maintain and even harder to develop new features.

The new PyPI has a far more modern look, and is up-to-date under the hood as well; a proper web framework (Pyramid), 100% backend test coverage, and a Docker-based development environment, make it easier for current and new developers to maintain it and add features.

Thanks to [Mozilla's Open Source Support funding](https://pyfound.blogspot.com/2017/11/the-psf-awarded-moss-grant-pypi.html), developers have added many new features, overhauled infrastructure, and made steady progress towards redirecting traffic to the new site and shutting down the old one. As of the middle of last year, package releases must go through the new PyPI, and as of late February, new user account registration is only available on the new site. The full switch will include redirecting browser and `pip install` traffic from the old site; then, sometime in late April or early May, the legacy site will be entirely shut down.

Your site/service will probably be able to seamlessly switch to the new site, and thanks to redirects, may not have to change anything immediately. [Here's a migration guide.](https://warehouse.readthedocs.io/api-reference/integration-guide/#migrating-to-the-new-pypi) And [here's the reference for the updated APIs.](https://warehouse.readthedocs.io/api-reference/)

Some new PyPI features:

* mobile-responsive UI
* easy-to-read project activity journal for project maintainers
* support for multiple project URLs (e.g., [for a homepage and a repo](https://packaging.python.org/tutorials/distributing-packages/#project-urls))
* no need to "register" a project before initial upload

Things that are going away, or already have (sometimes for policy or spam-fighting reasons), include:

* pythonhosted.com documentation hosting (pypa/warehouse#582)
* [download counts visible in the API](https://warehouse.readthedocs.io/api-reference/xml-rpc/#changes-to-legacy-api) (instead, use [the Google BigQuery service](https://packaging.python.org/guides/analyzing-pypi-package-downloads/))
* package maintainers being able to upload a new release via the web UI (instead, the recommended command-line tool is [Twine](http://twine.readthedocs.io/))
* package maintainers being able to log in and update release descriptions via the web UI (to update release metadata, they need to upload a new release; see [distutils-sig discussion](https://mail.python.org/pipermail/distutils-sig/2017-December/031826.html))
* users being able to upload a package without verifying their email address with PyPI first
* [HTTP access to APIs; now it's HTTPS-only](https://mail.python.org/pipermail/distutils-sig/2017-October/031712.html)

And in the works:

* [PEP 541](https://www.python.org/dev/peps/pep-0541/) will enable more timely package takeovers, as people get package names transferred to them after conflict resolution
* Now that PEP 566 has been approved, [developers are working to get Markdown supported for README files on PyPI](https://github.com/pypa/warehouse/issues/869#issuecomment-340928703)

You can subscribe to [this announcements list](https://mail.python.org/mm3/mailman3/lists/pypi-announce.python.org/) to get a heads-up when the big changes are about to happen.

Thank you for integrating with PyPI, and please [let us know](https://github.com/pypa/warehouse/issues/new) if you have any questions or problems with the new site!

**Comment by andrew** [comment]
@brainwane thanks for the heads up, I've got a PR open to switch everything over here: https://github.com/librariesio/libraries.io/pull/2026

The only thing that doesn't appear to be working correctly are the rss feeds:

- https://pypi.org/rss/updates.xml
- https://pypi.org/rss/packages.xml

Which I expected the contents to match the old ones but currently don't:

- https://pypi.python.org/pypi?%3Aaction=rss
- https://pypi.python.org/pypi?%3Aaction=packages_rss

Is that a known issue or expected new behaviour?

**Comment by brainwane** [comment]
@andrew Thank you for the heads-up. That is, to me, unexpected behaviour. I'll open an issue within Warehouse for that. Please do speak up, here or in the Warehouse repo, if you see any more such surprises!

**Comment by andrew** [comment]
@brainwane just merged and deployed #2026, all links on Libraries.io now point to the warehouse and talk with the warehouse API 🎉
