### ISSUE TITLE
Upgrade request_store to version 1.4.1

### ISSUE THREAD

**Issue by andrew** [librariesio/libraries.io#2033]
Libraries.io has found that there is a newer version of request_store that this project depends on.

More info: https://libraries.io/rubygems/request_store/1.4.1

**Comment by breakfast1** [comment]
You need to update `Gemfile.lock`. Run `bundle install` and then push it.

**Comment by andrew** [comment]
@breakfast1 a `bundle update` fixed this, these issues are opened automatically whenever an update to a dependency is released

**Comment by breakfast1** [comment]
Wow I didn't know that. My mistake then.
