### ISSUE TITLE
Shows different Tags than Github does

### ISSUE THREAD

**Issue by KingSora** [librariesio/libraries.io#2037]
The Libraries.io link is: https://libraries.io/github/KingSora/OverlayScrollbars
This are my tags on Github: https://i.imgur.com/gt6oYRb.png
And this are my tags on Libraries.io: https://i.imgur.com/C2aHzj6.png

The same issue with the bower version: [here](https://libraries.io/bower/overlayScrollbars)

As you can see, the last tag (v1.4.0) shows up twice and the last tag (v1.0) is deleted on Github but is still present in Libraries.io.

**Comment by andrew** [comment]
@KingSora I've resynced the repos tags, all looks correct now, thanks for reporting
