### ISSUE TITLE
Add new Libraries.io logo

### ISSUE THREAD

**Issue by BenJam** [librariesio/libraries.io#2060]
- [x] logo on libraries.io domain
- [x] logo on the assets project github.com/librariesio/assets
- [ ] favicon

part of #2059

**Comment by laurenhanford** [comment]
@BenJam I pushed these PRs up .. now what happens with this issue? Git guidance, plz :)

**Comment by laurenhanford** [comment]
closed by #2078

**Comment by andrew** [comment]
I'll update the favicons with one of those online generators
