### ISSUE TITLE
Redesign home page

### ISSUE THREAD

**Issue by BenJam** [librariesio/libraries.io#2061]
To focus primarily on driving search (in the knowledge that 90+% of users enter through Google to a project page). Secondarily pointing to 'search as a service' and 'use our data in your research'. 

Likely that this will creep into search results pages too, with a dependency upon #1916. Part of #2059

**Comment by amyeastment** [comment]
Two different ideas based on conversations with @andrew, @BenJam, and @laurenhanford. (cc: @havocp) 

[Libraries.io Homepage Redesign v3.pdf](https://github.com/librariesio/libraries.io/files/1860775/Libraries.io.Homepage.Redesign.v3.pdf)

**Comment by andrew** [comment]
Inlining some screenshots from @amyeastment's pdf:

![screen shot 2018-03-29 at 16 38 01](https://user-images.githubusercontent.com/1060/38098322-a90e449a-336f-11e8-92ff-ba4e6f309b08.png)

![screen shot 2018-03-29 at 16 38 17](https://user-images.githubusercontent.com/1060/38098326-ab000e6e-336f-11e8-8a21-edd6a15c77be.png)

![screen shot 2018-03-29 at 16 38 31](https://user-images.githubusercontent.com/1060/38098331-ae3e9a46-336f-11e8-88f5-eff97a7e4fff.png)

![screen shot 2018-03-29 at 16 38 40](https://user-images.githubusercontent.com/1060/38098336-b683cdac-336f-11e8-8146-b3d3770228ab.png)

**Comment by andrew** [comment]
And @BenJam's mockup:

![1](https://user-images.githubusercontent.com/1060/38098372-cfd63b14-336f-11e8-8090-1137f94ce728.png)

**Comment by katzj** [comment]
Closing this out for now
