### ISSUE TITLE
Upgrade dependencies through depfu?

### ISSUE THREAD

**Issue by PragTob** [librariesio/libraries.io#2075]
:wave: 

Saw issues like #2074 and #2071 - which seem to be an automated feature from libraries.io - cool.

However, that only creates issues and needs manual work. [depfu is free for open source](https://depfu.com/for-open-source) and creates pull requests with the gem update, a changelog and everything which makes dependency updates a lot easier. With that it's often a matter of seeing the CI results, checking the change log and hitting merge. We happily use it at work.

Now I'm unsure/couldn't find anything with a first look if there is a plan to add the same to libraries.io and you'd rather "dogfood" it - or would you like to use an external service?

**Comment by andrew** [comment]
I’m actually a fan of leaving them open as good first issues for people to make their first contributions to open source, rather than having it all done automatically
