### ISSUE TITLE
Size is wrong for npm packages

### ISSUE THREAD

**Issue by styfle** [librariesio/libraries.io#2101]
Before submitting a bug report:

- [x] Double-check that the bug is persistent,
- [x] Double-check the bug hasn't already been reported [on our issue tracker](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+org%3Alibrariesio), they *should* be labelled `bug` or `bugsnag`.
----

1. Visit https://libraries.io/npm/copee/1.0.3
2. Notice the size shows **77.1 KB**
3. [npm install --save copee@1.0.3](https://packagephobia.now.sh/result?p=copee@1.0.3) reports **12.8 kB**

This can be reproduced with the following:

```
mkdir example
cd example
npm install --save copee@1.0.3
```

![size](https://user-images.githubusercontent.com/229881/38681601-11d0591a-3e37-11e8-8d5d-9129ae3bc7af.png)

Why is libraries.io showing the size is so much larger?

**Comment by andrew** [comment]
That size is actually the size of the repository on GitHub according to the API, I'll update the label to say "Repository Size" instead.

**Comment by styfle** [comment]
Thanks for the clarification!

Would you be interested in listing the publish size or install size?

**Comment by andrew** [comment]
@styfle showing the package size for each version is on the roadmap already 👍 

PR for fix over here: https://github.com/librariesio/libraries.io/pull/2102

**Comment by andrew** [comment]
Just deploying that change now, thanks for reporting

**Comment by styfle** [comment]
> showing the package size for each version is on the roadmap already

Are there issues I can subscribe to to know when this is being developed?

I have a tool that has mostly solved this problem here: https://github.com/styfle/packagephobia

**Comment by andrew** [comment]
https://github.com/librariesio/libraries.io/issues/475 is probably the best issue to subscribe to, the challenge is adding support for the 36 different package managers that we support, not all of them make as easy as npm does!
