### ISSUE TITLE
Subscriptions: Can't turn off "Include prereleases"

### ISSUE THREAD

**Issue by ThatGuySam** [librariesio/libraries.io#2142]
Thank you for making this project

## Context:

- macOS 10.13.4
- Chrome & Safari

## Steps to reproduce:

1. Log in
2. Go to library(ex: https://libraries.io/npm/next)
3. Click "Subscribe to Releases"
4. Click Arrow next to "Already Subscribed"
5. Uncheck or Click "Include prereleases"
6. Refresh page
7. Click Arrow next to "Already Subscribed"

"Include prereleases" should still be checked. 

Example:
https://www.youtube.com/watch?v=7mdLJJNldAw&feature=youtu.be

**Comment by andrew** [comment]
Looks like the javascript that enabled that silently stopped working at some point, I'm just deploying a fix for that now
