### ISSUE TITLE
No results for search 'thymeleaf-extras-springsecurity4'

### ISSUE THREAD

**Issue by fapdash** [librariesio/libraries.io#2147]
Maven: https://search.maven.org/#search%7Cga%7C1%7Ca%3A%22thymeleaf-extras-springsecurity4%22

**Comment by movermeyer** [comment]
FWIW: it is available on libraries.io: https://libraries.io/maven/org.thymeleaf.extras:thymeleaf-extras-springsecurity4

Not sure why the search isn't finding it.

**Comment by katzj** [comment]
This will get fixed as the current reindex of maven packages finishes
