### ISSUE TITLE
No results for search 'spring-boot-email-core'

### ISSUE THREAD

**Issue by fapdash** [librariesio/libraries.io#2148]
Maven: https://search.maven.org/#search%7Cga%7C1%7Cspring-boot-email-core

**Comment by movermeyer** [comment]
FWIW: it is available on libraries.io: https://libraries.io/maven/it.ozimov:spring-boot-email-core.

I'm not sure why the search doesn't find it.

**Comment by katzj** [comment]
This will get fixed as the current reindex of maven packages finishes
