### ISSUE TITLE
Missing github link in a Pypi package

### ISSUE THREAD

**Issue by gpotter2** [librariesio/libraries.io#2171]
## Bugs
Before submitting a bug report:

- [x] Double-check that the bug is persistent,
- [x] Double-check the bug hasn't already been reported [on our issue tracker](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+org%3Alibrariesio), they *should* be labelled `bug` or `bugsnag`.

Hello, small issue: 

https://libraries.io/pypi/scapy

Should be linked to

https://github.com/secdev/scapy

I asked on the slack, and was told to post an issue here

> jeremy 21 h 20, 6 of june
> @gpotter2 Generally they should get crawled automatically. If something doesn’t, can you file an issue at https://github.com/librariesio/libraries.io/issues and we can take a look

Thanks in advance for spending some of your time helping me

**Comment by katzj** [comment]
All fixed now.

**Comment by gpotter2** [comment]
Thanks a lot !!
