### ISSUE TITLE
Chrome is giving an invalid manifest error

### ISSUE THREAD

**Issue by KhurrumMahmood** [librariesio/libraries.io#2184]
It seems that finally, after all these years... The extension has died / vanished.

Where it doesn't show up in search for the chrome web store, you can still find it at the link:

https://chrome.google.com/webstore/detail/dossier/hohaaljbjhjodnncjbeeilfdloeinfbh

But, it won't reinstall because of the error.

**Comment by katzj** [comment]
Hi -- it looks like you're referencing a tool which just has information cached on libraries.io from the github repo as opposed to a libraries.io project. You'll need to reach out to the creator of the chrome extension with any problems you're having.
