### ISSUE TITLE
No results for search '@opendxl/node-red-contrib-dxl'

### ISSUE THREAD

**Issue by chrissmith-mcafee** [librariesio/libraries.io#2211]
The '@opendxl/node-red-contrib-dxl' package is not showing up in libraries.io. 

However, it is available via NPM: https://www.npmjs.com/package/@opendxl/node-red-contrib-dxl

Is has been available for over a week. Other packages from the @opendxl/ organization are showing in libraries.io, so not entirely sure why it is not listed.

Any help is greatly appreciated, thanks!

**Comment by katzj** [comment]
It's been crawled now
