### ISSUE TITLE
bootstrap-select information out of date

### ISSUE THREAD

**Issue by caseyjhol** [librariesio/libraries.io#2216]
If you go to https://libraries.io/github/snapappointments/bootstrap-select, you'll see only 54 tags, despite there actually being 58. The latest available version is v1.13.0-alpha, even though we're on v1.13.2.

The same issue is occurring for bower: https://libraries.io/bower/bootstrap-select.

**Comment by katzj** [comment]
Looks like it might have just been a little behind in crawling as it's updated now

**Comment by caseyjhol** [comment]
@katzj This issue has only partially been resolved. Can you reopen it?

**Comment by caseyjhol** [comment]
@katzj NuGet and bower information for bootstrap-select is still incorrect/out-of-date. Any idea how to fix this?

**Comment by caseyjhol** [comment]
@katzj NuGet information now appears to be correct. However, Bower information is still outdated.

See:
- https://libraries.io/bower/bootstrap-select
- https://github.com/snapappointments/bootstrap-select/blob/v1.13.0-dev/bower.json

The description, homepage, and keywords are all extremely outdated.
