### ISSUE TITLE
Maven Central synchronization seems broken

### ISSUE THREAD

**Issue by tmortagne** [librariesio/libraries.io#2225]
Seems like synchronization with Maven Central does not work anymore (changed were probably made to the API along with the new UI).

For example https://libraries.io/maven/org.apache.commons:commons-collections4 is missing a version (4.2).

`Resync Project` does not have any effect.

**Comment by katzj** [comment]
The version for that package is there now and looks like it was created after you did resync project (queue might have been a little long at that point)

Looking to see more generally what's going on

**Comment by tmortagne** [comment]
> it was created after you did resync project

OK thanks, I did not understood from the UI that it as added in a queue.

I checked a lots of packages while moving my artifact-listener.org (which is pretty much dead) list to libraries.io and both had the same missing versions which seems to match the big UI change in Maven central.

**Comment by katzj** [comment]
Found something where things weren't properly watching the feed of changes in maven and fixed that up yesterday. So that should fix going forward. And I've kicked off a job to recrawl to pick things up that were missed
