### ISSUE TITLE
Gwiddle is closing

### ISSUE THREAD

**Issue by jrobison** [librariesio/libraries.io#2226]
Gwiddle foundation is closing: https://host.gwiddlefoundation.org.uk/were-closing

I recommend removing the Gwiddle link and adding this additional resource for a list of free student hosting: https://www.whatsthehost.com/web-hosting-for-students/

**Comment by katzj** [comment]
The information about gwiddle is in a readme from github so will need to get updated there and then we'll recrawl the change
