### ISSUE TITLE
Add testimonials to the site

### ISSUE THREAD

**Issue by andrew** [librariesio/libraries.io#224]
@Keithamus: 

> Building a modular codebase with npm has always been a double edged sword. Managing dependencies at any scale quickly becomes a hassle, without even realising you can get into the 1000s of modules. Vetting the quality of dependencies for even simple metrics like license information is such a chore.
> 
> Libraries.io is unbelievably effortless. At a glance I can see license info for every dependency, see any deprecation notices. With a few clicks I now get emails tracking dependency updates, complete with which of my packages depend on these. The API and WebHooks let me and my colleagues develop some awesome tooling to fit our exact use cases. Time saver would be an understatement.

@thenickcox:

> Managing npm dependencies for a even a medium-sized application is non-trivial. Just last week, I was caught in dependency hell. This week, I was looking for easier ways to keep from getting behind on the overwhelming pace of dependency and subdependency updates. Within just a few seconds (literally), I was able to get visibility on a complex dependency tree that would've taken an unknown amount of time Googling and grepping – on a per-dependency basis, along with the corresponding headaches – to track down manually. Its value will only continue to increase as it alerts me of updates via email. Goodbye, headaches!

**Comment by BenJam** [comment]
We should consider putting a call out to collect testimonials from users right here in comments. Easiest way to collect them IMO.

**Comment by stefanbc** [comment]
I pity my past self before he discovered libraries.io because I remember a time when keeping tabs on dependencies was a bigger headache then trying to figure out what JS framework to use. If it wasn't for @andrew and his brilliant implementation of this service we would still live in a world where you would have to do everything by hand.

**Comment by M-Zuber** [comment]
libraries.io is an amazing service. It enables me to quickly find projects that depend on things I wrote/maintain, which enables me to make more informed decisions about changes.

**Comment by andrew** [comment]
Moving this to the [Backlog](https://github.com/librariesio/libraries.io/blob/master/Backlog.md) as we'd still like to implement it but can't see that happening in the near future.
