### ISSUE TITLE
Translate scm:git:git@github repo urls

### ISSUE THREAD

**Issue by katzj** [librariesio/libraries.io#2245]
Some maven projects have a repository url in their pom.xml that looks like `scm:git:git@github.com:sbt/junit-interface.git`. We should translate those to be `https://github.com` urls

**Comment by AgonIdrizi** [comment]
Hey,
Can i contribute, to correct those urls.
Thnx

**Comment by katzj** [comment]
Will get fixed up as we update maven packages
