### ISSUE TITLE
Github login redirects to localhost

### ISSUE THREAD

**Issue by guanzo** [librariesio/libraries.io#2256]
When I try to login with Github, it redirects me to `http://localhost:3000/auth/github/callback?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch&state=260973333a9efeca9fdc4032cd90d632e1574fe3df939dd7`

**Comment by katzj** [comment]
Apologies, fixed up

**Comment by volans-** [comment]
This is happening to me as of now.
