### ISSUE TITLE
PyPI: license parsing errors

### ISSUE THREAD

**Issue by lazka** [librariesio/libraries.io#2266]
* https://libraries.io/pypi/mutagen states GPL-3.0-only but the package has a GPLv2 classifier
* https://libraries.io/pypi/PyGObject states GPL-3.0-only but the package has a LGPLv2+ classifier

**Comment by katzj** [comment]
Fixed with https://github.com/librariesio/spdx/commit/eda131f5a6b8a388f49f6b07372bed7676b401d4 and updating the packages in question now

**Comment by lazka** [comment]
Thanks!

For the record, here are the official values for PyPI: https://pypi.org/pypi?%3Aaction=list_classifiers

**Comment by katzj** [comment]
The thing that was tripping up the classifier wasn't the trove classifiers but instead the license data info (`info`.`license` from https://pypi.org/pypi/mutagen/json for example) which is more free-form

**Comment by lazka** [comment]
Ah, I totally forgot about that, thanks :)
