### ISSUE TITLE
Release 1.3.0 of Libraries.io Open Data

### ISSUE THREAD

**Issue by AlexandreDecan** [librariesio/libraries.io#2273]
https://libraries.io/data indicates the next expected release of Libraries.io open data is planned for June 2018. I know that many things changed with Tidelift, but can we expect the new data to be released soon?

**Comment by katzj** [comment]
I had cut a data release before we started the server migration but unfortunately found some problems in the data that made it not the most useful. Now that we've finished migrating to the new infrastructure, I will try to kick off an export over the slow holidays

**Comment by AlexandreDecan** [comment]
👍 Thanks!

**Comment by katzj** [comment]
Shipped a new version (it's 1.4.0... 1.3.0 never made it out). The /data page will have the link shortly

**Comment by AlexandreDecan** [comment]
Great, thank you very much!! ;-)
