### ISSUE TITLE
Overview of licence warnings

### ISSUE THREAD

**Issue by andrew** [librariesio/libraries.io#23]
Show warnings about:
- lack of license
- conflicting licenses between package and source
- unknown license
- conflicting dependency licenses

**Comment by BenJam** [comment]
Note: this is an overview of warnings at a library level, not individually.

**Comment by andrew** [comment]
Moving this to the [Backlog](https://github.com/librariesio/libraries.io/blob/master/Backlog.md) as we'd still like to implement it but can't see that happening in the near future.
