### ISSUE TITLE
Remove the following repos

### ISSUE THREAD

**Issue by ejelome** [librariesio/libraries.io#2315]
Please remove the following repos since I already removed them from my repo:

* https://libraries.io/github/ejelome/gitbookwrapper
* https://libraries.io/github/ejelome/dotfiles
* https://libraries.io/github/ejelome/demos
* https://libraries.io/github/ejelome/notes

... or if you can simply wipe all the repos within my namespace, then that will make your deletion easier.

Thanks in advance :)

**Comment by katzj** [comment]
Removed

**Comment by ejelome** [comment]
Hello @katzj, thanks!

However, I can still access: https://libraries.io/github/ejelome/notes

Would be great if you also remove this, TIA!

**Comment by katzj** [comment]
Done

**Comment by ejelome** [comment]
Vielen dank!
