### ISSUE TITLE
SourceRank shows "0" even though the rank is higher

### ISSUE THREAD

**Issue by alexdlaird** [librariesio/libraries.io#2324]
## Bugs
Before submitting a bug report:

- [x] Double-check that the bug is persistent,
- [x] Double-check the bug hasn't already been reported [on our issue tracker](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+org%3Alibrariesio), they *should* be labelled `bug` or `bugsnag`.

On this library (and many others I've seen), the SourceRank shown on the page itself does not actually reflect the total values added up: https://libraries.io/pypi/pyngrok. I've tried resyncing the package, updating it, etc., nothing seems to make it reflect the correct value.

**Comment by katzj** [comment]
Kicked pyngrok manually to update. Will probably wait until Monday to merge my change just to be able to not feel like I have to watch it over the weekend
