### ISSUE TITLE
libalize.a dont install

### ISSUE THREAD

**Issue by hananeam1991** [librariesio/libraries.io#2332]
I Want to install alize but when i run makein alize-core i following this error
Making all in src
make[1] : on entre dans le répertoire « /home/hanane/Bureau/PACK-ALIZE/LIA_RAL-master/alize-core/src »
make[1]: rien à faire pour « all ».
make[1] : on quitte le répertoire « /home/hanane/Bureau/PACK-ALIZE/LIA_RAL-master/alize-core/src »
make[1] : on entre dans le répertoire « /home/hanane/Bureau/PACK-ALIZE/LIA_RAL-master/alize-core »
make[1]: rien à faire pour « all-am ».
make[1] : on quitte le répertoire « /home/hanane/Bureau/PACK-ALIZE/LIA_RAL-master/alize-core »
mv src/libalize.a lib/libalize_Linux_x86_64.a

**Comment by katzj** [comment]
I think you want to file this against https://github.com/ALIZE-Speaker-Recognition/alize-core/issues

**Comment by hananeam1991** [comment]
But dont workk
