### ISSUE TITLE
Emails send for deleted repo

### ISSUE THREAD

**Issue by MGatner** [librariesio/libraries.io#2340]
I had a fork that I was following (https://libraries.io/github/MGatner/hotsapi) but deleted on GitHub after the PRs were complete. Libraries.io detects it as removed ("This repository has been removed and cannot be used anymore.") but it still sends me emails about packages in that repo and I can't turn them off because it doesn't show as a repository under the monitoring list (https://libraries.io/repositories).

**Comment by katzj** [comment]
Should be all set
