### ISSUE TITLE
Remove all my repos in libraries.io

### ISSUE THREAD

**Issue by ejelome** [librariesio/libraries.io#2350]
Kindly remove all repos I have (they're in no way useful since they don't exist any longer and it bugs me every time I see them in SERPs); going to https://libraries.io/repos/search?q=ejelome will list all of them.

They are 17 repos in total:

1. https://libraries.io/github/ejelome/mysys
2. https://libraries.io/github/ejelome/mysys
3. https://libraries.io/github/ejelome/rena
4. https://libraries.io/github/ejelome/archaic
5. https://libraries.io/github/ejelome/rea
6. https://libraries.io/github/ejelome/pyql
7. https://libraries.io/github/ejelome/pyenvwrapper
8. https://libraries.io/github/ejelome/tap
9. https://libraries.io/github/ejelome/litpro
10. https://libraries.io/github/ejelome/jinc
11. https://libraries.io/github/ejelome/renaftgu
12. https://libraries.io/github/ejelome/arch-linux-guide
13. https://libraries.io/github/ejelome/avgar-test 
14. https://libraries.io/github/ejelome/blog-clj
15. https://libraries.io/github/ejelome/lisp-hacker-roadmap
16. https://libraries.io/github/ejelome/virtualenvwrapper-rm
17. https://libraries.io/github/ejelome/reat

**Comment by lavelle** [comment]
I have a similar issue. Pretty sure it's illegal for them to host your content and not provide a way to take it down under GDPR!

**Comment by katzj** [comment]
Removed
