### ISSUE TITLE
Bug: user() API call doesn't return followers or following fields

### ISSUE THREAD

**Issue by discdiver** [librariesio/libraries.io#2357]
## Bug

To reproduce: Make a get request with a user with a platform host and user name. 
I used "github" and "discdiver". 
I received back the correct information except follower and following fields both show None. 
'followers': None, 'following': None

Those fields should show 18 for followers  and 6 for following.

**Comment by katzj** [comment]
These actually stopped being collected a while ago... we're trying to avoid capturing a lot of user data as people can just go to the repo host for the full info. So we're going to be removing those fields from the api at this time
