### ISSUE TITLE
Add calls to action for projects

### ISSUE THREAD

**Issue by andrew** [librariesio/libraries.io#24]
Show ways to improve your projects like:
- add a license
- add a homepage link
- fix warnings about deprecated/unmaintained/removed/conflicting dependencies

**Comment by BenJam** [comment]
👍  for this ticket, would be great to be able to pick up some standard labels like `first-pr` and `help wanted` and show 2-3 specific tickets alongside anything auto-magically generated.

**Comment by andrew** [comment]
Moving this to the [Backlog](https://github.com/librariesio/libraries.io/blob/master/Backlog.md) as we'd still like to implement it but can't see that happening in the near future.
