### ISSUE TITLE
More consistent wording: say "packages" rather than "repositories"?

### ISSUE THREAD

**Issue by brainwane** [librariesio/libraries.io#2404]
## Bugs
Before submitting a bug report:

- [x] Double-check that the bug is persistent,
- [x] Double-check the bug hasn't already been reported [on our issue tracker](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+org%3Alibrariesio), they *should* be labelled `bug` or `bugsnag`.

I was showing @JustinCappos [a sample page on libraries.io](https://libraries.io/pypi/twine/usage) and he noted: "_Repositories_ that depend on twine? Why 'repositories' and not 'packages'?" And indeed [that language is in a lot of templates on the site](https://github.com/librariesio/libraries.io/search?q=%22repositories+that%22&unscoped_q=%22repositories+that%22), while [the About page](https://libraries.io/about) talks about "packages" rather than "repositories". Could we clarify, and make the wording more consistent?

**Comment by katzj** [comment]
The usage page actually is about repositories and not packages -- we track usage by version for repositories so that things that aren't packaged in package managers (like end user webapps!) track the versions which are used.
