### ISSUE TITLE
No results for search 'org.apache.httpcomponents:httpcomponents-parent' (Maven)

### ISSUE THREAD

**Issue by decathorpe** [librariesio/libraries.io#2406]
## Bugs

- [x] Double-check that the bug is persistent,
- [x] Double-check the bug hasn't already been reported [on our issue tracker]

This maven artifact is not present on libraries.io:

    org.apache.httpcomponents:httpcomponents-parent

But it's present in Maven central:

https://search.maven.org/artifact/org.apache.httpcomponents/httpcomponents-parent/11/pom

**Comment by katzj** [comment]
Fixed
