### ISSUE TITLE
No results for search 'org.apache.logging:logging-parent' (Maven)

### ISSUE THREAD

**Issue by decathorpe** [librariesio/libraries.io#2407]
## Bugs

- [x] Double-check that the bug is persistent,
- [x] Double-check the bug hasn't already been reported [on our issue tracker]

This artifact cannot be found on libraries.io:

    org.apache.logging:logging-parent

But it's present in maven central:

https://mvnrepository.com/artifact/org.apache.logging/logging-parent

**Comment by katzj** [comment]
Fixed
