### ISSUE TITLE
Project statistics data is shown incorrectly

### ISSUE THREAD

**Issue by rpotter12** [librariesio/libraries.io#2417]
Thanks for taking the time to raise an issue. This template should guide you through the process of submitting a bug, enhancement or feature request. Please erase any part of this template that is not relevant to your issue. 

## Bugs
Before submitting a bug report:

- [x] Double-check that the bug is persistent,
- [x] Double-check the bug hasn't already been reported [on our issue tracker](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+org%3Alibrariesio), they *should* be labelled `bug` or `bugsnag`.

[rpotter12/whatsapp-play](https://libraries.io/github/rpotter12/whatsapp-play) in this repository the project statistics data is shown incorrectly. I have re-sync the project again but still all the data is shown incorrectly. Stars and forks are 11 and 6 but in this site only 2 are shown. Readme file is also not updated.

**Comment by katzj** [comment]
Looks like it's caught up and correct now
