### ISSUE TITLE
Source repository is not detected

### ISSUE THREAD

**Issue by techtonik** [librariesio/libraries.io#2425]
## Bugs

- [x] Double-check that the bug is persistent,
- [x] Double-check the bug hasn't already been reported [on our issue tracker](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+org%3Alibrariesio), they *should* be labelled `bug` or `bugsnag`.

For https://libraries.io/pypi/patch SourceRanks shows that source repository is not present:

![image](https://user-images.githubusercontent.com/515889/64154533-c11ef500-ce39-11e9-904f-7531a23966cd.png)

But that's not true. There are both home page and repository linking to the same GitHub repo.

**Comment by katzj** [comment]
Resynced the project to force an update and it picked it up.

**Comment by techtonik** [comment]
@katzj doesn't looks like a long solution.
