### ISSUE TITLE
Next release of libraries.io open data

### ISSUE THREAD

**Issue by AlexandreDecan** [librariesio/libraries.io#2430]
Hello,

Is there any plan to release a new version of libraries.io's dataset? The last dump is nearly one year old. 

Thank you!

**Comment by AlexandreDecan** [comment]
Hello, 

This data dump is very valuable for us as researchers ;) Any news on this @katzj  ? :) 

Thank you!! ;)

**Comment by econst** [comment]
Indeed, it would be useful to have an updated snapshot of the dataset!

**Comment by AlexandreDecan** [comment]
I'm sorry to insist, but can we expect an updated dump? @katzj @mikeyoung85 @kbarrette

**Comment by tommens** [comment]
I strongly support this request for an updated datadump of libraries.io, it can be most useful in gaining deeper empirical insights in the current state of the package dependency networks of the package managers targeted by libraries.io.

**Comment by MhDG7** [comment]
Its one the most important data source in my area of research and I really appreciate and support this request... Hope you do this favor in near future...

**Comment by DamienLegay** [comment]
As others have mentioned, a more recent dump of libraries.io would assist researchers greatly in analysing patterns of package dependency and other aspects of software engineering research.

**Comment by AlexandreDecan** [comment]
@johnbintz-tidelift I'm sorry to ping, but I'm trying to find someone from the team behind this wonderful project who could bring us some news for this issue. Thank you! ;)

**Comment by katzj** [comment]
Working on trying to get one... unfortunately, they take a long time to run and then need to do some manual verification to sanity check them so it's not a zero effort thing.

**Comment by AlexandreDecan** [comment]
Thanks a lot! Is there any way I (we?) can help you?

**Comment by katzj** [comment]
New version is now live

**Comment by AlexandreDecan** [comment]
Lot of thanks! I'm very grateful, this will help us a lot!

Thanks again!

**Comment by MhDG7** [comment]
The link is broken for me...

**Comment by AlexandreDecan** [comment]
The dump is available on zenodo, try this https://zenodo.org/record/3626071
