### ISSUE TITLE
REMOVE MY INFORMATION FROM YOUR SITE

### ISSUE THREAD

**Issue by mintyweazel** [librariesio/libraries.io#2431]
Remove any information on me including my profile and my repos from your site permanently and completely. I did not give any consent to use my data in this way.

**Comment by katzj** [comment]
Marked your user to not be shown

**Comment by mintyweazel** [comment]
My repositories are still on the your site.

https://libraries.io/npm/vlottz
https://libraries.io/npm/nativescript-oss-licenses

Remove them all.
