### ISSUE TITLE
Cran package versions outdated

### ISSUE THREAD

**Issue by dbast** [librariesio/libraries.io#2441]
Some cran packages versions seem to be outdated. One out of many more examples is:
* https://cran.r-project.org/web/packages/xfun/index.html (version 0.10)
* https://libraries.io/cran/xfun (version 0.8)
 
That means version 0.9 and and 0.10 are missing. 

Some other packages have pretty recent versions (from today) , e.g.:
* https://cran.r-project.org/web/packages/pegas/index.html
* https://libraries.io/cran/pegas

Any idea why there is such a discrepancy?

Thanks

**Comment by katzj** [comment]
Looks like it's been picked up. The watcher of recent cran releases may have missed an update

**Comment by dbast** [comment]
Other cran packages are still outdated e.g. https://libraries.io/cran/sparklyr ... not that important as we found a different way to check versions for conda-forge
