### ISSUE TITLE
No results for search 'glitch-questions'

### ISSUE THREAD

**Issue by tribakzero** [librariesio/libraries.io#2443]
## Bugs
Go to this URL: https://www.npmjs.com/package/glitch-questions
Then go to this URL: https://libraries.io/search?q=glitch-questions

As you can see, the one for libraries.io is not finding my package, I know it is new, but there's nothing that says that the indexing takes n hours to be done. I just found the link to this issues page.

## Enhancements and Features
This one is a small one, I just want this package to be shown on your search results, this way I can import my library into Glitch.

**Comment by katzj** [comment]
Looks like it has indexed now
