### ISSUE TITLE
Can't unsubscribe from hypothesis

### ISSUE THREAD

**Issue by arnau** [librariesio/libraries.io#2457]
Hi, I'm receiving updates for the Python library Hypothesis but I'm not subscribed.  The https://libraries.io/pypi/hypothesis/unsubscribe page is asking me to open an issue here.

Thanks,

**Comment by katzj** [comment]
I'm not seeing a subscription for that project on your user. Can you forward an email including all headers to support@libraries.io?

**Comment by arnau** [comment]
Done!

**Comment by arnau** [comment]
mmm, seems that it is a dependency of a project from an org I no longer belong to.

**Comment by katzj** [comment]
Fixed up for you!
