### ISSUE TITLE
Outdated readme after sync

### ISSUE THREAD

**Issue by bjorn3** [librariesio/libraries.io#2472]
# Steps to reproduce

Click sync link for https://libraries.io/github/bjorn3/rustc_codegen_cranelift

# Expected behaviour

Readme is updated

# Observed behaviour

Last pushed time is updated but readme is not.

- [ ] Double-check that the bug is persistent, (can't, sync button hidden after last sync)
- [x] Double-check the bug hasn't already been reported [on our issue tracker](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+org%3Alibrariesio), they *should* be labelled `bug` or `bugsnag`.

**Comment by katzj** [comment]
Resynced it

**Comment by bjorn3** [comment]
Thanks. The unimplemented section of the old readme is quite outdated.
