### ISSUE TITLE
Some projects on PyPI are listed twice on libraries.io

### ISSUE THREAD

**Issue by brechtm** [librariesio/libraries.io#2487]
Searching for my project "rinohtype" on libraries.io returns 3 projects of which two are the same, only differing in letter case:

<img width="383" alt="image" src="https://user-images.githubusercontent.com/652887/76105975-4300fe00-5fd6-11ea-8be5-7b82da19f498.png">

Note that the latest version for "RinohType" is 0.3.1, while "rinohtype" is at (the correct) version 0.4.0.

I did initially name the project "RinohType" but changed it to all-lowercase when releasing 0.2.0. PyPI doesn't consider case for project names, so "RinohType" and "rinohtype" are the same project, except that different versions of the package might have different letter case.

**Comment by katzj** [comment]
Should be fixed now
