### ISSUE TITLE
Repositories removal request

### ISSUE THREAD

**Issue by eidoriantan** [librariesio/libraries.io#2497]
I would like to request to remove all of my old deleted repositories on the site.

[StoneArtz/KeyLogger](https://libraries.io/github/StoneArtz/KeyLogger)
[eidoriantan/sudokues](https://libraries.io/github/eidoriantan/sudokues)
[StoneArtz/Quadratic-Equation](https://libraries.io/github/StoneArtz/Quadratic-Equation)
[StoneArtz/HTML-Project](https://libraries.io/github/StoneArtz/HTML-Project)
[StoneArtz/SimpleCalculator](https://libraries.io/github/StoneArtz/SimpleCalculator)
[StoneArtz/HTPASSWD-Generator](https://libraries.io/github/StoneArtz/HTPASSWD-Generator)
[StoneArtz/psychic-meme](https://libraries.io/github/StoneArtz/psychic-meme)
[StoneArtz/sample](https://libraries.io/github/StoneArtz/sample)
[StoneArtz/QuadraticEquation](https://libraries.io/github/StoneArtz/QuadraticEquation)
[StoneArtz/Windows-API](https://libraries.io/github/StoneArtz/Windows-API)
[StoneArtz/a](https://libraries.io/github/StoneArtz/a)
[StoneArtz/Key-Logger](https://libraries.io/github/StoneArtz/Key-Logger)
[eidoriantan/sudoku](https://libraries.io/github/eidoriantan/sudoku)

Thank you very much!

**Comment by katzj** [comment]
Removed
