### ISSUE TITLE
ethereum/go-ethereum tags not updated

### ISSUE THREAD

**Issue by adamschmideg** [librariesio/libraries.io#2498]
libraries.io shows [ethereum/go-ethereum](https://libraries.io/go/github.com%2Fethereum%2Fgo-ethereum) to have the last release on Apr 17, 2019 tagged v1.8.27. But https://github.com/ethereum/go-ethereum/tags shows the last release to be on March, 2020 tagged v1.9.12. I assume it's a bug

**Comment by katzj** [comment]
Forced a sync
