### ISSUE TITLE
Clarify expectations around package/project resync

### ISSUE THREAD

**Issue by brainwane** [librariesio/libraries.io#2501]
As a logged-in Libraries.io user, I can select "Resync Project" (e.g. https://libraries.io/pypi/readme_renderer/sync ) for any project.

Today, 2-3 hours ago, I clicked that button for several PyPI projects[0]. For each one, I saw the notification at the top of the page that the project had been queued for resync. Some of those projects have now, clearly, gotten processed in that queue (for instance, [pip](https://libraries.io/pypi/pip) is now marked as "Last synced: 2020-04-09 16:50:37 UTC"). Some have not gotten processed, such as [readme_renderer](https://libraries.io/pypi/readme_renderer). I filed #2500 about a different problem I encountered along the way.

I now see that https://libraries.io/pypi/pip and https://libraries.io/pypi/pipenv have resynced for the first times in several months, yet I believe their statistics on the usage pages are unchanged.

So I'm unsure of a few things and could use clarification:

* How fast should a project resync happen once I've clicked that button? (If nothing has happened within an hour, is it reasonable to click it again?)
* What info, metadata, metrics, etc. get refreshed with a project sync, and what doesn't?

I think some info about this should go in https://github.com/librariesio/documentation and there should be a link near the Project Resync button in the application.

[0] Examples: https://libraries.io/pypi/wheel , https://libraries.io/pypi/pipenv , https://libraries.io/pypi/readme_renderer , https://libraries.io/pypi/yolk3k , https://libraries.io/pypi/virtualenv , https://libraries.io/pypi/twine , https://libraries.io/pypi/pip , https://libraries.io/pypi/distlib

cc @pradyunsg @ei8fdb who found this with me today.

**Comment by katzj** [comment]
The resync is usually pretty quick (minutes) but occasionally there's a lot being synced and so it's slower. In the specific case of readmer_render, it looks like at some point it got saved as readme_renderer vs readme-renderer. I just fixed libraries to have the correct canonical name (which uses the `-` vs the `_`). Note that, unlike pypi, libraries doesn't currently do redirection on those (see #2202)

As far as when things update -- there's a lot of caching, especially for expensive things like usage by version. Some of those caches are a day, some are a week.

**Comment by brainwane** [comment]
Thank you for the explanation!

**Comment by brainwane** [comment]
I appreciate the explanation. I still think some info about this should go in https://github.com/librariesio/documentation and there should be a link near the Project Resync button in the application. What do you think?
