### ISSUE TITLE
Incorrect claim by sourcerank that a README is missing for a given .gem?

### ISSUE THREAD

**Issue by rubyFeedback** [librariesio/libraries.io#2503]
Hey there,

Consider the following gem:

https://libraries.io/rubygems/bioroebe/sourcerank

Ok, sourcerank reports some issues, understandably. But one in particular is confusing me.

Sourcerank states that it has no Readme ("Readme present?"). But the gem comes
with a README.md file.

May it be that sourcerank only checks the **content** of .gemspec? I may have setup my .gemspec incorrectly, but the README.md is 100% part of the gem release.

**Comment by katzj** [comment]
READMEs are only looked for in a repository and since there's not an associated repository, it's unable to find one.
