### ISSUE TITLE
No results for search 'jakarta.annotation:jakarta.annotation-api'

### ISSUE THREAD

**Issue by decathorpe** [librariesio/libraries.io#2516]
This maven artifact definitely exists: `jakarta.annotation:jakarta.annotation-api`

See: <https://mvnrepository.com/artifact/jakarta.annotation/jakarta.annotation-api>

It has been renamed from `javax.annotation:javax.annotation-api`, which is maybe causing this issue.

**Comment by katzj** [comment]
Synced it

**Comment by decathorpe** [comment]
Awesome, thank you!
