### ISSUE TITLE
What is this gem which add an argument 'anonymous_class' to 'has_many'? 

### ISSUE THREAD

**Issue by Yegorov** [librariesio/libraries.io#2520]
Hi guys! 
I walk by source code on this project and found some code [(app/models/user.rb)](https://github.com/librariesio/libraries.io/blob/master/app/models/user.rb):
```ruby
class User < ApplicationRecord
  include Recommendable
  include GithubIdentity
  include Monitoring

  has_many :identities, dependent: :destroy
  has_many :viewable_identities, -> { viewable }, anonymous_class: Identity
  has_many :repository_users, through: :identities
```
I'm interested in this line `has_many :viewable_identities, -> { viewable }, anonymous_class: Identity`.
What is this gem which add an argument `anonymous_class` to `has_many`? 

Have a nice day :rocket:

**Comment by tiegz** [comment]
Hey @Yegorov , this is an internal option in Rails for adhoc classes. It was renamed from `:class` a few years ago: https://github.com/rails/rails/commit/ac2b7a5c4d46b74c12ca8a67e73b803e7726e115 . Not sure why `anonymous_class` was used instead of `class_name` in this case though.

**Comment by Yegorov** [comment]
@tiegz  thanks, for answer!
I would not have guessed that this is an option from ActiveRecord.
I was confused that this option is not in the [doc](https://guides.rubyonrails.org/association_basics.html#options-for-has-many)
