### ISSUE TITLE
No results for search 'Azure.Messaging.ServiceBus'

### ISSUE THREAD

**Issue by SeanFeldman** [librariesio/libraries.io#2531]
Azure.Messaging.ServiceBus packages is not found

**Comment by katzj** [comment]
It's not showing up in the nuget registry for some reason (https://api.nuget.org/v3/registration5-semver1/azure.messaging.servicebus/index.json is a 404). Maybe because it's only pre-release versions that don't look semver compat?

**Comment by SeanFeldman** [comment]
> Maybe because it's only pre-release versions that don't look semver compat?

The package is pre-release package and is marked as a prerelease (7.0.0-preview.3). Why would it be not considered SemVer compatible?

Not familiar with the link you've shared, @katzj. Could you please elaborate on what is it?
