### ISSUE TITLE
Cant run this program: traj-dist

### ISSUE THREAD

**Issue by shaheerbakali** [librariesio/libraries.io#2533]
Hello,

Can someone please help me run the program located at: https://github.com/bguillouet/traj-dist

So I followed the instructions and did this:
1. Navigate to the folder where traj-dist is 
2. python setup.py install 
3. pip install .
4. After this I don't know how to proceed, I went into traj_dist folder and tried to run every python file, but I kept getting an error every time.

So if anyone can help me out here and help to run this python project, I would highly appreciate it.

**Comment by katzj** [comment]
You'll need to reach out to them to help. Libraries just collects metadata about software.
