### ISSUE TITLE
Update development-setup.md for later versions of elasticsearch

### ISSUE THREAD

**Issue by ftarlaci** [librariesio/libraries.io#2542]
Homebrew deleted `elasticsearch@2.4` and other versions of elasticsearch do not work when following the instructions on `development-setup.md`. I was not able to make the rails app work without the stated version of elasticsearch (I used other versions, such as @6 and @7.8.0. Changing the version in the provided `Gemfile` causes all kinds of other gem issues. If it is currently possible to make it work with another version of elasticsearch and with the existing Gemfile, which version should that be? 

Here is the output when I run `bundle exec rails s` and launch the localhost:

> Started GET "/" for ::1 at 2020-07-23 12:43:08 -0500
/Users/ft/Desktop/libraries.io/config/routes.rb:57: warning: already initialized constant PLATFORM_CONSTRAINT
/Users/ft/Desktop/libraries.io/config/routes.rb:57: warning: previous definition of PLATFORM_CONSTRAINT was here
/Users/ft/Desktop/libraries.io/config/routes.rb:58: warning: already initialized constant PROJECT_CONSTRAINT
/Users/ft/Desktop/libraries.io/config/routes.rb:58: warning: previous definition of PROJECT_CONSTRAINT was here
/Users/ft/Desktop/libraries.io/config/routes.rb:59: warning: already initialized constant VERSION_CONSTRAINT
/Users/ft/Desktop/libraries.io/config/routes.rb:59: warning: previous definition of VERSION_CONSTRAINT was here
   (0.8ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC /*application:Libraries*/
Processing by ProjectsController#index as HTML
ETHON: Libcurl initialized
ETHON: performed EASY effective_url=http://localhost:9200/projects-development/project/_search response_code=0 return_code=couldnt_connect total_time=0.006258
ETHON: performed EASY effective_url=http://localhost:9200/projects-development/project/_search response_code=0 return_code=couldnt_connect total_time=0.001048
ETHON: performed EASY effective_url=http://localhost:9200/projects-development/project/_search response_code=0 return_code=couldnt_connect total_time=0.000942
ETHON: performed EASY effective_url=http://localhost:9200/projects-development/project/_search response_code=0 return_code=couldnt_connect total_time=0.001553
Completed 500 Internal Server Error in 79ms (ActiveRecord: 2.3ms | SQL count: 2) 
Faraday::ConnectionFailed (Couldn't connect to server):
app/models/concerns/project_search.rb:78:in `block in facets'
app/models/concerns/project_search.rb:77:in `facets'
app/controllers/projects_controller.rb:30:in `index'

**Comment by katzj** [comment]
Unfortunately there's work required to update with newer elasticsearch so you'll have to get an old version to run libraries (or happy to review PRs to get things working with newer!)
