### ISSUE TITLE
Removing my repo/profile from libraries.io

### ISSUE THREAD

**Issue by LuchoTurtle** [librariesio/libraries.io#2543]
Hey there! 
Is it possible to remove my profile and my associated repos from libraries.io? The [repos that show up](https://libraries.io/github/LuchoTurtle) are now private and the profile has my real name associated, something that I removed a while ago from my Github account. It kind of bugs me out every time I see old, private repos and my name in SERPs.

Thank you! :)

**Comment by katzj** [comment]
Done
