### ISSUE TITLE
Remove removed versions

### ISSUE THREAD

**Issue by kuzmoyev** [librariesio/libraries.io#2581]
## Bugs

The versions that were removed from GitHub remain in the list of versions. Which leads to links that lead to 404 pages.

For example v0.1 in [gcsa library](https://libraries.io/github/kuzmoyev/google-calendar-simple-api).

**Comment by katzj** [comment]
Removed. In general, we leave the old ones there as someone could be using them.

**Comment by kuzmoyev** [comment]
Thank you for the swift reply.

The same issue goes for the [library](https://libraries.io/pypi/gcsa). If the version, i.e. [v0.1](https://libraries.io/pypi/gcsa/0.1), is removed from PyPI the `pip install gcsa==0.1` leads to `ERROR: No matching distribution found for gcsa==0.1`
