### ISSUE TITLE
Remove removed (from PyPI) version

### ISSUE THREAD

**Issue by kuzmoyev** [librariesio/libraries.io#2582]
## Bugs

Similar to ##2581, for the [library](https://libraries.io/pypi/gcsa). If the version, i.e. [v0.1](https://libraries.io/pypi/gcsa/0.1), is removed from PyPI the `pip install gcsa==0.1` leads to `ERROR: No matching distribution found for gcsa==0.1`.

**Comment by katzj** [comment]
Removed
