### ISSUE TITLE
Failure to read pyproject.toml (reading missing requirements.txt)

### ISSUE THREAD

**Issue by alunduil** [librariesio/libraries.io#2603]
## Bugs

1. Change Python project from requirements.txt to pyproject.toml managed by poetry.
2. Resync project on libraries.io (e.g., https://libraries.io/github/alunduil/zfs-replicate).
3. Note that libraries.io still reports dependencies from requirements.txt that is no longer present.

I would expect that the dependencies section would update to indicate it's reading pyproject.toml (where the dependencies are specified) and ensure the versions are up to date.

**Comment by RivenSkaye** [comment]
To add to this, if your Python project uses fully scriptless setup (e.g. any [PEP517](https://peps.python.org/pep-0517/) project), libraries.io just ends up not recognizing the dependency list _at all_.
E.g. [EnforceTypes](https://libraries.io/pypi/EnforceTypes/0.0.3) lists `typing_extensions` in `[project]` => `dependencies`, but it's listed as having 0 dependencies

**Comment by tiegz** [comment]
✅ a bug was fixed with pypi syncing, so zfs-replicate looks correct now 
✅ support for `[project]` in pyproject.toml has been added, so EnforceTypes now lists the correct deps
