### ISSUE TITLE
Remove the following repos

### ISSUE THREAD

**Issue by serhatcelik009** [librariesio/libraries.io#2608]
Please remove the following repos since I already removed them from my repo:

https://libraries.io/github/serhatcelik009/hARPy

https://libraries.io/github/serhatcelik009/AVsub

https://libraries.io/github/serhatcelik009/discord-bot

https://libraries.io/github/serhatcelik009/caesar13

... or if you can simply wipe all the repos within my namespace, then that will make your deletion easier.

Thanks in advance :)

**Comment by katzj** [comment]
Removed

**Comment by serhatcelik009** [comment]
Thank you, but this one is not closed, is it normal?

https://libraries.io/github/serhatcelik009/caesar13
