### ISSUE TITLE
Please remove the following repos

### ISSUE THREAD

**Issue by serhatcelik009** [librariesio/libraries.io#2609]
Please remove the following repos since I already removed them from my repo:

My linked GitHub: https://github.com/serhatcelik009
My PyPI: https://pypi.org/user/serhatcelik009/

https://libraries.io/pypi/cipher-caesar

https://libraries.io/pypi/harpy-project

https://libraries.io/pypi/project-harpy

Thanks in advance.

**Comment by katzj** [comment]
Removed
