### ISSUE TITLE
Please remove the following repos (I forgot the mention them in the last issue :(

### ISSUE THREAD

**Issue by serhatcelik009** [librariesio/libraries.io#2615]
I forgot the mention them in the last issue :( sorry
( https://github.com/librariesio/libraries.io/issues/2609)

Please remove the following repos, I already removed mine:

https://libraries.io/github/serhatcelik/caesar13
https://libraries.io/pypi/caesar13

(My linked GitHub: https://github.com/serhatcelik009
My PyPI: https://pypi.org/user/serhatcelik009/)

Thanks in advance :)

**Comment by katzj** [comment]
Removed
