### ISSUE TITLE
Horrendously Outdated QDirStat Page

### ISSUE THREAD

**Issue by shundhammer** [librariesio/libraries.io#2639]
If you really must copy & paste my texts, **please at least update them every few years**. Your page about QDirStat is **ancient**. Please update everything to be up to date or completely delete it.

https://libraries.io/github/shundhammer/qdirstat

> Updated: 2016-02-20
...
> ## Current Development Status
> Beta status -- V0.86 (Beta 1)
>
> **2016-02-06**

## WTF?!

We are in late 2020. QDirStat has now version 1.7, being continuously updated all the time. **Unlike your pages which just keep rotting away.**

## If you reap the results of other people's work, at least have the decency to keep the stuff up to date!

Do not just copy and paste stuff and leave it rotting away from there! Either automatically sync the pages or just set a hyperlink! Just copying stuff once and then leaving it to bit rot is by far the worst thing you can do!

## Current Version

https://github.com/shundhammer/qdirstat

**Comment by shundhammer** [comment]
> ## QDirStat Release History
> 
> - 2020-07-26 New stable release: 1.7
> 
>   - Closing the gap between sizes reported by QDirstat and sizes reported by
>     the `du` command: Now also taking the allocated size into account.
> 
>   - Now also displaying the allocated size where it makes sense.
> 
>   - New "Mounted Filesystems" window showing output similar to the `df` command
>     (but without the cruft).
> 
>   - New directory selection dialog showing all (real) filesystems.
> 
> 
> - 2020-02-13 New stable release: 1.6.1
> 
>   - Much better handling for "permission denied" errors while reading directories
> 
>   - Now showing the exact byte size (134 495 994 Bytes instead of 128.3 MB)
>     upon mouse click
> 
>   - New optional tree column "Oldest File" (not enabled by default)
> 
> 
> - 2019-07-22 New stable release: V1.6
> 
>   - New _packages_ view
> 
>   - New _unpackaged files_ view
> 
>   - Performance improvements while reading directories
> 
>   - Vast Performance improvement for huge directories
>     (100.000+ entries in a single directory)
> 
> 
> - 2018-11-07 New stable release: V1.5
> 
>   - New _details_ panel
> 
>   - Package manager support to show what software package a file belongs to
> 
>   - New _breadcrumbs_ navigation
> 
>   - Switchable tree layouts L1 / L2 / L3
> 
> 
> - 2017-06-04 New stable release: V1.4
> 
>   - New _file size statistics_ with histogram
> 
>   - Shading for empty space in the treemap for lots of very small files
> 
> 
> - 2017-03-05 New stable release: V1.3
> 
>   - New _file type_ view
> 
>   - Locate files of a certain type (filename extension) in the tree
> 
> 
> - 2017-01-03 New stable release: V1.2
> 
>   - Improved Btrfs subvolumes support
> 
> 
> - 2016-10-31 New stable release: V1.1-Pumpkin
> 
>   - Bug fixes
> 
>   - Split up the config file into several ones
> 
> 
> - 2016-05-16 First stable release: V1.0
> 
> - 2016-04-08 Beta 3 release

## ^^^^^ You are here ^^^^^

 
> - 2016-03-20 Beta 2 release
> 
> - 2016-02-06 Beta 1 release
> 
> - 2015-11-28 QDirStat project start: Ported from the old KDE 3 KDirStat

**Comment by katzj** [comment]
Resynced

**Comment by shundhammer** [comment]
Thanks!

**Comment by ftarlaci** [comment]
@katzj thank you for all the work you guys do for libraries.io and open source community. It enables many devs to discover and keep up to date with projects/dependencies. I appreciate the work you do.
