### ISSUE TITLE
Next release of libraries.io open data

### ISSUE THREAD

**Issue by bobbui** [librariesio/libraries.io#2744]
Hello,

Firstly, I really appreciate the work you guys had put into this dataset.
Just want to check is there any plan to release a new version of libraries.io's dataset? The last dataset is over one year old.

Thank you.

**Comment by hehao98** [comment]
Also want to ask the same question.

Libraries.io dataset has become one of the most important datasets in the academic field of software engineering and is being used in all kind of research topics related to software libraries. I would also really appreciate it if a new dump of your amazing work can be released.

Thank you.

**Comment by tommens** [comment]
Our software engineering team at the University of Mons is frequently using the libraries.io dataset. We have used, and cited, it in many of our recent publications. We would therefore also appreciate it *a lot* if a new datadump of libraries.io could be released, since you are doing amazing work. As you can see in the links below, libraries.io is a very popular and heavily cited dataset in the software engineering research community.
https://scholar.google.com/scholar?cites=14609549778511936468
https://scholar.google.com/scholar?cites=8299574943575694840

**Comment by MehdiGol** [comment]
@katzj  @tiegz  
I have the same request for releasing a new dump of the libraries.io dataset. My research on collaborative software development is making use of your precious dataset. I am convinced that many other researchers in the area of empirical software engineering and mining software repositories would benefit a lot from a new dump. 
Do you have any plans to release a new datadump in the near future?

**Comment by johanneswachs** [comment]
I am also very interested in another dump!

**Comment by AlexandreDecan** [comment]
I'm also crossing fingers for a new data dump :-)

**Comment by aaron-lohmann** [comment]
Also leaving a comment here indicating that I would also be highly interested in a new data dump. Your work is much appreciated!

**Comment by praveena0302** [comment]
@johanneswachs @AlexandreDecan @bobbui @hehao98 @tommens 
May I know where can I get the dump of the libraries.io dataset?

**Comment by AlexandreDecan** [comment]
Have a look at ecosystem.ms, I doubt libraries.io will be maintained anymore.

**Comment by praveena0302** [comment]
> Have a look at ecosystem.ms, I doubt libraries.io will be maintained anymore.

Thank you so much for your help but I couldn't be able to find ecosystem.ms.

**Comment by AlexandreDecan** [comment]
Sorry I misspelled it: ecosyste.ms

**Comment by ChillarAnand** [comment]
Any plans on releasing new data set?

**Comment by katzj** [comment]
We have no plans to release a new data set at this time.
