### ISSUE TITLE
Update no longer works properly

### ISSUE THREAD

**Issue by gansm** [librariesio/libraries.io#2810]
Since I changed my default branch from "master" to "main", everything is no longer updated correctly. On github in the highest tag 0.7.1 and on libraries.io 0.7.0.

https://github.com/gansm/finalcut/tags
https://libraries.io/github/gansm/finalcut

**Comment by tiegz** [comment]
Thanks @gansm , it should be updated now and moving forward.

**Comment by gansm** [comment]
Many thanks
