### ISSUE TITLE
Wrong repository scraped for keyvi

### ISSUE THREAD

**Issue by hendrikmuhs** [librariesio/libraries.io#2818]
https://libraries.io/pypi/keyvi uses a mixture of the old https://github.com/cliqz-oss/keyvi and new https://github.com/KeyviDev/keyvi location. 

While new releases are correctly detected, all links as well as the Documentation point to the old repository. The only correct location is https://github.com/KeyviDev/keyvi, all releases originate from there. The old location is decommissioned since at least 3 years.

Resync doesn't fix it, sending a "suggestion" does not get answered.

Can you please reset the page, or whatever is necessary to fix the wrong links and Documentation?
If there is anything I can fix on my site, please let me know.

**Comment by katzj** [comment]
Done

**Comment by hendrikmuhs** [comment]
@katzj The table on the upper right, below _SourceRank_ still links https://github.com/cliqz-oss/keyvi instead of https://github.com/KeyviDev/keyvi and hence uses wrong counts.
