### ISSUE TITLE
Subscribe button is missing

### ISSUE THREAD

**Issue by hudcap** [librariesio/libraries.io#2832]
## Bugs
Go to a package's page, which in my case is https://libraries.io/pypi/black
Check that you're logged in

Actual: There is no "subscribe" button

Expected: Some sort of "Subscribe to releases" button

**Comment by hudcap** [comment]
...and I just found #2828 
So apparently it's a feature, not a bug...
Is this temporary or permanent?

**Comment by jcea** [comment]
+1!

**Comment by hudcap** [comment]
@mellisio @jsonperl Can you please clarify if this is a permanent change to libraries.io?
Or temporary until something else is fixed?
Or something else?

Thanks in advance!

**Comment by sebix** [comment]
Sad to hear that. libraries.io was a perfect tool for release notifications. I respect your decision to remove this feature, but is there an alternative?

https://release-monitoring.org offers a similar service through Fedora Account Notifications, but that's not at all intuitive as easy to use as libraries.io.

P.S.: Although that question is somewhat off-topic for this repo, I hope that we can discuss alternatives to use.
