### ISSUE TITLE
Catchpoint migration

### ISSUE THREAD

**Issue by doffymingozzz** [librariesio/libraries.io#2858]
Hi! 

It’s Gleb from Catchpoint.com.

I've noticed that your website links to our old blog, which we’re currently migrating from a subdomain to the main domain. The reason I’m reaching out is to make sure you won’t have a 404 error on your website.

You have a link to our old blog on the following page: https://libraries.io/github/jdiazmx/pi-hole
I wonder if you’d be able to replace it with the new one: https://www.catchpoint.com/blog/ad-block-ios-impact

Thanks for linking to Catchpoint.com!

Please don’t hesitate to contact me if something comes up v-gkapusto@catchpoint.com!

Best, 
Gleb

**Comment by tiegz** [comment]
Hi Gleb, the link on Libraries is content from the original git repo https://github/jdiazmx/pi-hole, so you'll have to file an issue there if you want it updated.

**Comment by doffymingozzz** [comment]
Thank you for comment !
