### ISSUE TITLE
remove my profile and organization

### ISSUE THREAD

**Issue by simonify** [librariesio/libraries.io#2890]
I've removed my GH repos and NPM org/packages but they're still indexed on your service. Specifically:

https://libraries.io/github/simonify
https://libraries.io/github/treesnetwork
https://libraries.io/npm/@ttn%2Fcah
https://libraries.io/npm/@ttn%2Fbumps
https://libraries.io/npm/@ttn%2Fcard-game
https://libraries.io/npm/@ttn%2Ftokebot
https://libraries.io/npm/@ttn%2Fbot
https://libraries.io/npm/@ttn%2Fwdym

thank you!

**Comment by katzj** [comment]
Removed
