### ISSUE TITLE
Database corruption and wrong notifications

### ISSUE THREAD

**Issue by ssbarnea** [librariesio/libraries.io#2894]
Two days ago I noted wrong notifications about pypi releases with version 0.0.0 which happened like 8 years ago in reality or never happened.

This affected multiple projects and now I see duplicate notifications about releases being sent. Something went very bad...

flake8-docstrigs 0.0.0 -- see https://libraries.io/pypi/flake8-docstrings/0.0.0 and check its date, check it n pypi and surprise!

Some of the other packages affected (real list is clearly much longer)
pyyaml - 4-5 new releases
py
coverage
pylint
pyflakes

My inbox is now full of wrong notifications

**Comment by tiegz** [comment]
Hey @ssbarnea , apologies for the notifications! We accidentally re-checked some older Pypi packages 2 days ago. It looks like we picked up some older versions that we didn't have before and would have sent out notifications for them. The reason why some of the versions have an incorrect date looks to be an issue with older Pypi data, where the versions exposed don't have a published_at date ([example](https://pypi.org/pypi/flake8-docstrings/json)).
