### ISSUE TITLE
"New release" announcements sent for very old packages

### ISSUE THREAD

**Issue by reece** [librariesio/libraries.io#2895]
I occasionally receive new release announcements for very old packages. Here's a list of new releaes announcements I've received in the last 2.5 years. The announcements with red Xs are bogus (or at least I don't understand them).

![image](https://user-images.githubusercontent.com/109453/146610357-78db176c-dfa5-4c5f-aa1c-a52efd9e6b1d.png)

The libraries.io web site has a valid list of releases, which does not correspond to the above announcements.

![image](https://user-images.githubusercontent.com/109453/146610512-942527d7-3be9-4f46-a70e-91e2686b54f5.png)

**Comment by katzj** [comment]
Per #2894 -- `We accidentally re-checked some older Pypi packages 2 days ago. It looks like we picked up some older versions that we didn't have before and would have sent out notifications for them. The reason why some of the versions have an incorrect date looks to be an issue with older Pypi data, where the versions exposed don't have a published_at date (example).`
