### ISSUE TITLE
[Secret Problem]Is there a way to regenereate a new api_key?

### ISSUE THREAD

**Issue by xiao623** [librariesio/libraries.io#2920]
> Your private token is used to access application resources without authentication. Keep it secret!

If we accidentally expose the `api_key`, is there a way to regenereate a new api_key and invalidate the past api_key?
I didn't find the way.

**Comment by katzj** [comment]
We can invalidate one for you on the backend if you need

**Comment by xiao623** [comment]
> We can invalidate one for you on the backend if you need

Yes, please regenereate a new api_key and invalidate the past api_key.

Anyway, it is better that user can regenereate a new api_key if they want and need.
