### ISSUE TITLE
Outdated information for hackage package (after version schema changed)

### ISSUE THREAD

**Issue by DavHau** [librariesio/libraries.io#3015]
Information about some hackage packages seems to be outdated.
Example: https://libraries.io/hackage/hslogger

The most recent version displayed on libraries.io is `1.2.12` released on `2018-12`.
The most recent version displayed on hackage is `1.3.1.0` released on `2022-08`.

One thing that looks suspicious, is that the maintainer changed the versioning schema after `1.2.12` to contain 4 elements instead of 3.
At that exact point the data stopped being updated on libraries.io.

I'd guess the change in the schema triggered a bug.
Are there any public logs of the indexers that would allow me to confirm my suspicion? I'd like to help in getting that fixed.

**Comment by katzj** [comment]
It looks like it was in a stuck state thinking it was syncing. I just unstuck it and it picked up the new version
