### ISSUE TITLE
@beartype listing has been stale for nearly a year

### ISSUE THREAD

**Issue by leycec** [librariesio/libraries.io#3034]
Dear *wonderful* Libraries.io engineers who I adore,

@beartype's [Libraries.io listing](https://libraries.io/pypi/beartype) has been stale for nearly a year. I note [this similar recently resolved issue with another PyPI-hosted Python project](https://github.com/librariesio/libraries.io/issues/3022). Suspiciously, both listings for both projects went stale at a similar time: Q2 2022. I am thoughtfully tugging on my moustache.

It'd be grand if an update could be forced for @beartype. Our front-facing documentation links to Libraries.io, which isn't reflecting well on us at the moment. Sad Bengal cat is sad.:crying_cat_face: 

Oh – and did I mention I just *adore* this spectacular resource you maintain on behalf of the open-source community? Because I do. Libraries.io is superb stuff that I'm grateful I don't need to maintain myself. Long live Libraries.io!

**Comment by leycec** [comment]
@katzj: Wondrous @tidelift cofounder and CTO, @beartype summons thee!

![activate summoning](https://media.tenor.com/7iwicNso0FYAAAAS/kuma-kuma-kuma-bear-yuna.gif)

**Comment by ddnomad** [comment]
I shall join the wait.

![activate summoning](https://i.imgur.com/EtX8EAT.gif)

**Comment by leycec** [comment]
Even *Serial Experiments Lain* in bear hat form supports this issue. <sup>Slava Ukraini from Canada! :ukraine: :bear: :canada:</sup>

Sadly, Libraries.io has fallen down and cannot get back up here. I've reluctantly removed the link to [@beartype's Libraries.io listing](https://libraries.io/pypi/beartype) from our [official documentation hosted at Read The Docs (RTD)](https://beartype.readthedocs.io), which pains me. Getting analytics on reverse dependencies and downstream usage was so *guuud.* But all good things come to a merciless end. At least we still have ~~Arch~~ Gentoo Linux and anime!

**Comment by tiegz** [comment]
@papiro tracked down the core issue and deployed a fix for this, so the versions should be up-to-date now.

**Comment by leycec** [comment]
**Oh, frabjous!** Thanks so much for the rapid turnaround, @tiegz and @papiro. You are cultured gentlemen who deserve all the jaundiced thumbs up the Internet has to give.  :+1: :+1: :+1:

I'll restore @beartype's link to Libraries.io straight away. *Let's gooooooooo.*
