### ISSUE TITLE
Please remove this Package!

### ISSUE THREAD

**Issue by Sayad-Uddin-Tahsin** [librariesio/libraries.io#3058]
I've created https://libraries.io/pypi/sra-python in PyPI but by mistake while editing an issue, I've removed my project that caused to not able to use that anymore. I've created the new `sra-pylib` which is there https://libraries.io/pypi/sra-pylib.

Please remove the https://libraries.io/pypi/sra-python!

**Comment by tiegz** [comment]
Removed
