### ISSUE TITLE
Categorise projects

### ISSUE THREAD

**Issue by andrew** [librariesio/libraries.io#33]
Community organised categorization of projects, similar to https://www.ruby-toolbox.com/

**Comment by BenJam** [comment]
Closing in favour of #76

**Comment by BenJam** [comment]
Could be possible to use an approach like #445

**Comment by andrew** [comment]
Moving this to the [Backlog](https://github.com/librariesio/libraries.io/blob/master/Backlog.md) as we'd still like to implement it but can't see that happening in the near future.
