### ISSUE TITLE
Please remove my repositories

### ISSUE THREAD

**Issue by x3525** [librariesio/libraries.io#3431]
https://libraries.io/github/serhatcelik/avsub
https://libraries.io/github/serhatcelik/harpy
https://libraries.io/github/serhatcelik/sten
https://libraries.io/pypi/avsub
https://libraries.io/pypi/project.harpy
https://libraries.io/pypi/project.sten
https://libraries.io/pypi/sten-gui

**Comment by katzj** [comment]
Removed
