### ISSUE TITLE
Show version changelogs

### ISSUE THREAD

**Issue by andrew** [librariesio/libraries.io#38]
Show the changes in each release, either via a changelog file or pulling commits from the repo.

Depends on https://github.com/librariesio/libraries.io/issues/35

**Comment by BenJam** [comment]
+1 to this as it will become key to ensuring that contributors are able to search for existing features, enhancements and such like prior to creating an issue. We can make this into the PR template too.

**Comment by andrew** [comment]
@BenJam this was for recording version changelogs for each version of every library monitored, rather than for the libraries.io application

**Comment by BenJam** [comment]
Oh...

**Comment by andrew** [comment]
Moving this to the [Backlog](https://github.com/librariesio/libraries.io/blob/master/Backlog.md) as we'd still like to implement it but can't see that happening in the near future.
