### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by andrew** [librariesio/libraries.io#454]
- [x] Setup guide for new contributors
- [x] Contribution and pull request guidelines 
- [ ] Testing
- [ ] Roadmap

**Comment by BenJam** [comment]
I'm more than happy to handle the content/editing/writing side if you can outline the technical and process side that you'd like to use. Bullet points are all good.

**Comment by andrew** [comment]
Closing in favour of https://github.com/librariesio/documentation
