### ISSUE TITLE
Investigate using materialized views 

### ISSUE THREAD

**Issue by andrew** [librariesio/libraries.io#460]
http://www.sitepoint.com/speed-up-with-materialized-views-on-postgresql-and-rails/

https://medium.com/@WoloxEngineering/activerecord-postgresql-materialized-views-9a9ef56b5a8d#.3b5bhdfg3

https://github.com/thoughtbot/scenic

**Comment by neilmiddleton** [comment]
You're best off doing these in raw SQL based on triggers.  By doing this you're guaranteeing stuff will stay up to date, and without having to dump a load of extras into your rails app.

```
drop materialized view if exists thing_counts;
create materialized view things as
select
thing_id,
count(*)
from things
with data;

create or replace function update_my_things()
  returns trigger
  as $$
    begin
      refresh materialized view thing_counts;
      return null;
    end;
  $$
  language plpgsql
;

drop trigger if exists update_my_table_when_thing_created on things;
create trigger update_my_table_when_thing_created
after insert or delete or truncate on things
execute procedure update_my_things();
```

*ish*
