### ISSUE TITLE
Detect unmaintained repos from issue activity

### ISSUE THREAD

**Issue by andrew** [librariesio/libraries.io#473]
If the issue stats are particularly bad, i.e. average response time is 6+ months then mark the repos as effectively unmaintained, if the repos projects also haven't received any releases in a similar time frame then mark the project as unmaintained too.

Dependent upon https://github.com/librariesio/libraries.io/issues/472

**Comment by cdrnet** [comment]
Note that an inactive project is not necessarily unmaintained. For example, I do have a few projects which haven't had any activity nor release for years, but if someone would report a bug I'd likely investigate it rather quickly. An automatic detection would still be very helpful in most cases, but there may be a demand from maintainers to override it on case by case.

**Comment by andrew** [comment]
Agreed, a lack of issues/pull requests don't mean its inactive, but if users are reporting issues and no-one is responding that's a good signal that it's unmaintained, which also doesn't mean it's not working either.

**Comment by andrew** [comment]
Closing in favour of https://github.com/librariesio/libraries.io/issues/472
