### ISSUE TITLE
Source rank for repos

### ISSUE THREAD

**Issue by andrew** [librariesio/libraries.io#477]
A numeric ranking score based on quality and popularity metrics, similar to SourceRank on projects.
- [x] Rank calculator
  - [x] Dependent counts for referenced projects
  - [x] Nmber of contributors
  - [x] Presense of license, readme, contributing.md, code of conduct etc
- [ ] Calculate rank for every repository

**Comment by scottrobertson** [comment]
I

**Comment by andrew** [comment]
Deployed the first step, now to calculate the sourcerank for 16 million repositories 😆
