### ISSUE TITLE
CPAN module: doc is not from latest release

### ISSUE THREAD

**Issue by dolmen** [librariesio/libraries.io#487]
I'm the author of the [Term::Chrome CPAN module](https://libraries.io/cpan/Term-Chrome).
My latest release is 2.00 and is correctly indexed on Libraries.io.
However the documentation displayed at https://libraries.io/cpan/Term-Chrome is not the documentation of the 2.00 release. It seems that the documentation stayed at release 1.010 (2015-10-21). You can compare with the [rendering on MetaCPAN](https://metacpan.org/pod/Term::Chrome).

**Comment by andrew** [comment]
@dolmen I've updated that manually for you and added some hooks to ensure the readme is updated automatically in the future :+1:
