### ISSUE TITLE
Upgrade to rails 5

### ISSUE THREAD

**Issue by andrew** [librariesio/libraries.io#508]
It's not released yet but getting close, upgrade guide here: https://medium.com/@tair/how-to-upgrade-to-rails-5-657b3bfd83#.9q30xygkw

**Comment by connorshea** [comment]
@andrew I've been tracking a ton of information about upgrading GitLab here if it's still something you're interested in: https://gitlab.com/gitlab-org/gitlab-ce/issues/14286

**Comment by andrew** [comment]
@connorshea that's great, there's a pr for the upgrade here: https://github.com/librariesio/libraries.io/pull/584 the main thing holding it back is some gems that haven't been updated to work with rails 5 yet

**Comment by connorshea** [comment]
Ah, yeah Sinatra is also blocking us. Thankfully the maintainer has been awesome about making progress and keeping people updated.
