### ISSUE TITLE
Clicking the "monitor" button is slow!!

### ISSUE THREAD

**Issue by jamestalmage** [librariesio/libraries.io#512]
Clicking the monitor button takes a while and rewrites the page (I lose scroll position). 

Adding a hundred repos took longer than it should.

**Comment by andrew** [comment]
Agreed, that definitely should be made into an ajax button 👍

**Comment by andrew** [comment]
Moving this to the [Backlog](https://github.com/librariesio/libraries.io/blob/master/Backlog.md) as we'd still like to implement it but can't see that happening in the near future.
