### ISSUE TITLE
Start a weekly 'trending' newsletter

### ISSUE THREAD

**Issue by nealrs** [librariesio/libraries.io#550]
Per [this convo](https://twitter.com/teabass/status/722320546625687553), I think it'd be really need to start a weekly newsletter about trending repos / popular repos relating to a specific topic. Here's an [example that I wrote about RPG related repos](http://gitat.me/2016/04/07/RPG/), using Lio. 

newsletters are a great way to keep users engaged, and a weekly / biweekly cadence isn't super hard to maintain.

**Comment by nealrs** [comment]
^ bump. how can i help kickstart this?

**Comment by andrew** [comment]
Moving this to the [Backlog](https://github.com/librariesio/libraries.io/blob/master/Backlog.md) as we'd still like to implement it but can't see that happening in the near future.
