### ISSUE TITLE
SourceRank seems to ignore the 'Home Page' link on PyPi when looking for the GitHub repository

### ISSUE THREAD

**Issue by not-raspberry** [librariesio/libraries.io#557]
The 'Home Page' is a typical place on PyPi to store the repo URL in small projects. The project linked below follows that practice and as a result, its GitHub repo is undetected.

Compare:

- https://pypi.python.org/pypi/pytest-reorder - search for 'Home Page'
- https://libraries.io/pypi/pytest-reorder/sourcerank - repo undetected

**Comment by andrew** [comment]
@not-raspberry sorry about that, looks like the background worker failed to sync down the github repository correctly, I've updated that for you now: https://libraries.io/pypi/pytest-reorder

It would usually use the homepage field to check for github repositories as you mentioned, the code is here: https://github.com/librariesio/libraries.io/blob/master/app/models/repositories/pypi.rb#L37
