### ISSUE TITLE
Add support for conan

### ISSUE THREAD

**Issue by andrew** [librariesio/libraries.io#599]
C/C++ package manager

https://www.conan.io/

Manifest files are `conanfile.py` and `conanfile.txt` http://docs.conan.io/en/latest/conanfile_py.html

**Comment by Croydon** [comment]
Would be great to have :)

**Comment by andrew** [comment]
Moving this to the [Backlog](https://github.com/librariesio/libraries.io/blob/master/Backlog.md) as we'd still like to implement it but can't see that happening in the near future.

**Comment by kaidokert** [comment]
ping. Conan is making quite a lot of progress and getting traction

https://docs.conan.io/en/latest/changelog.html
