### ISSUE TITLE
Open Data Exports

### ISSUE THREAD

**Issue by andrew** [librariesio/libraries.io#609]
I want to make the data available in libraries more useful for research purposes starting with regular data dumps of the public data, most likely in sql dump form to s3 to begin with and perhaps pushing data into a google big query public dataset in future: https://cloud.google.com/bigquery/public-data/

**Comment by janhohner** [comment]
Cool idea! I'll check with my colleagues at the university if we can help you distribute the data.

**Comment by andrew** [comment]
@janhohner The compressed sql dump from pg_dump is 13gb, about 170,000,000 rows.

I need to choose a license for the data before sharing it as well, may use https://en.m.wikipedia.org/wiki/Open_Database_License

**Comment by janhohner** [comment]
Sounds like a good option to me. I'll talk to @0xhansdampf and we'll see what we can do.

**Comment by andrew** [comment]
Planning to get this out before https://sustainoss.org in June

**Comment by janhohner** [comment]
Do you know how much traffic that would produce (roughly)?

**Comment by andrew** [comment]
@janhohner not sure, we'll be hosting the originals on s3 and encouraging people to mirror it in other places

**Comment by janhohner** [comment]
Ok, ping me when the files are online on S3 and I'll see what we can do :)

**Comment by andrew** [comment]
@janhohner we've published it now on Zenodo: https://zenodo.org/record/808273 and I'm currently uploading the individual files to Google BigQuery
