### ISSUE TITLE
First Pull Request issues

### ISSUE THREAD

**Issue by andrew** [librariesio/libraries.io#611]
Similar to [help wanted](https://github.com/librariesio/libraries.io/issues/471), we can show issues labelled with a number of labels aimed at people sending their first pull request like "first-timers-only" and "first-patch", ordered by repo rank and number of comments and filterable by language.

**Comment by andrew** [comment]
Pulled a list of all the labels used across open source repositories on issues and prs: https://gist.github.com/andrew/03d78048b7f47b979c7f232394ca22a9

Here's a list of ones that look relevant to this issue:

- good first bug
- good first contribution
- good-first-bug
- first-timers-only
- good first issue
- Good First Task
- easy first bug
- Your First PR
- FirstBug
- good-first-pr
- [Type] Good First Bug
- good first patch
- first bug
- good first step
- good-first-issue
- IdealFirstBug
- first contribution
- good first task
- Good First Pull Request
- Good For First Contribution
- SuitableAsFirstIssue
- your-first-pr
- contributors/first-timers
- first timers only
- good first commit
- good first pr
- goodfirstpatch
- good-first-PR (easy)
- First Time
- First Timers Only
- first-timers only
- firsttimersonly
- first-timers

cc @Charlotteis @kentcdodds as they might be interested in this feature too.

**Comment by kentcdodds** [comment]
This would be fantastic! In addition, I'm not certain how you could rank it by "beginner friendliness" but I often see issues with the `first-timers-only` that are not first timer friendly at all. Would be great to filter those out somehow.

**Comment by M-Zuber** [comment]
As someone who has no idea how to work with NLP/ML algos, I think the simplest way to determine "beginner friendliness" would have to be some sort of ranking based on original issue body text length and/or presence of some sort of checklist.
Thoughts?

**Comment by andrew** [comment]
Perhaps we can use the presence of  `README`, 'LICENSE`, `CONTRIBUTING.md` and `CODE_OF_CONDUCT.md` as a measure of contributor friendlyness, as well as looking at the number of people who have already contributed to the repo, assuming both those things contribute to how beginner friendly the project is?

**Comment by kentcdodds** [comment]
Those things sound great! Need to consider smaller projects too that may have few contributors because it's small and/or mostly "done"

**Comment by andrew** [comment]
Perhaps ordering rather than filtering by contributor count would avoid that?

**Comment by kentcdodds** [comment]
:+1:

**Comment by M-Zuber** [comment]
>as well as looking at the number of people who have already contributed to the repo

Since making things complicated is a hobby of mine (:wink:) -is there way to check if the contribution was the first on GH?
Meaning project X has Y contributors of whom Z where making their first PR?

**Comment by andrew** [comment]
@M-Zuber You do like to make things more complicated!

There definitely is, would require lots of api calls to cache but we could add a first_pr_id to all github users and populate it from the data that I've already downloaded and then watch for new firstprs using this code I've already written: https://github.com/librariesio/firstprbot/blob/master/index.js

**Comment by andrew** [comment]
Check it out: https://libraries.io/first-pull-request

**Comment by kentcdodds** [comment]
Wow! That was fast!

**Comment by M-Zuber** [comment]
>There definitely is, would require lots of api calls to cache but we could add a first_pr_id...

Wouldn't the code from http://firstpr.me/ work simpler?
I could try and hook you up with the person who made that :laughing:

**Comment by andrew** [comment]
That literally is the same API call as firstpr.me, I have lots of API tokens too 😉

**Comment by M-Zuber** [comment]
Ahh, you mean it would be a lot of api calls for the initial (old really) data, but relatively simple from there on in?

**Comment by andrew** [comment]
Going to class this as shipped now, ordering and quality will be improved when #477 and #473 are complete.
