### ISSUE TITLE
[WebHook] Overlapping of elements in layout

### ISSUE THREAD

**Issue by alloy** [librariesio/libraries.io#615]
I guess the issue is the URL? Alas, CSS etc is not my forte.

**Comment by alloy** [comment]
Ugh, posted the wrong unedited screenshot… Will re-upload in a sec.

**Comment by alloy** [comment]
![screen shot 2016-06-10 at 10 11 48](https://cloud.githubusercontent.com/assets/2320/15958097/c454e114-2ef3-11e6-9638-bfa92f527b3b.png)

**Comment by andrew** [comment]
Good spot, just deploying a fix for it now:

![screen shot 2016-06-10 at 9 14 20 am](https://cloud.githubusercontent.com/assets/1060/15958179/e58b53e8-2eeb-11e6-8ab2-c82cd918cdb6.png)

**Comment by alloy** [comment]
Fast turn-around 👍 :clap:
