### ISSUE TITLE
CSS - missing row on users template

### ISSUE THREAD

**Issue by BenMann** [librariesio/libraries.io#618]
Hey, looks like the users template needs to open/close a new `.row` in case there are "Most used" and "Published" projects. Probably [right here](https://github.com/librariesio/libraries.io/blob/master/app/views/users/show.html.erb#L67). 🍰 

Sorry for not opening a PR right away.. :-)

**Comment by andrew** [comment]
Ah good spot, just deploying a fix for that now 🚢
