### ISSUE TITLE
Add avatar and email attributes on GitHub user endpoint

### ISSUE THREAD

**Issue by zenorocha** [librariesio/libraries.io#625]
Is it possible to add `avatar_url` and `email` attributes on GitHub users endpoint?

> https://libraries.io/api/github/zenorocha
> https://api.github.com/users/zenorocha

**Comment by andrew** [comment]
You can generate their avatar url from just their username, for example: https://github.com/zenorocha.png?size=200

At the moment I don't store email addresses for GitHub users, I've open a separate issue to store public email addresses in the github users table: https://github.com/librariesio/libraries.io/issues/630

**Comment by andrew** [comment]
@zenorocha the field is there now in the api response, I just need to resync 2.6 million github users to load the data into it 😢

Will prioritize the 800 or so users who've published a `web-components` module 😆
