### ISSUE TITLE
Multiple keywords doesn't seem to be working

### ISSUE THREAD

**Issue by zenorocha** [librariesio/libraries.io#626]
When requesting https://libraries.io/api/search?q=&platforms=bower&keywords=web-components everything seems to be working fine. 

But when adding another keyword, results appear to be empty: https://libraries.io/api/search?q=&platforms=bower&keywords=web-components,polymer

**Comment by andrew** [comment]
Yep that's a bug, will get that sorted out in the next couple days

**Comment by zenorocha** [comment]
👍

**Comment by andrew** [comment]
@zenorocha just deployed a fix for this too 🤘
