### ISSUE TITLE
Multiple platforms filter seems to be showing extra results

### ISSUE THREAD

**Issue by zenorocha** [librariesio/libraries.io#627]
For example, when requesting https://libraries.io/api/search?q=&platforms=bower,npm&keywords=web-components&per_page=3&sort=stars we can see a result from `Packagist` too.

**Comment by andrew** [comment]
Yep that's a bug, will get that sorted out in the next couple days

**Comment by zenorocha** [comment]
Ok, thanks for looking into it ;)

**Comment by andrew** [comment]
@zenorocha just deployed a fix for this, passing multiple platforms separated by a comma should work now
