### ISSUE TITLE
Add GitHub repository data when requesting projects from a certain author

### ISSUE THREAD

**Issue by zenorocha** [librariesio/libraries.io#628]
For example, when building a profile page like this https://customelements.io/JaySunSyn I need to use the https://libraries.io/api/github/JaySunSyn/projects?keywords=web-components endpoint. The problem is that some useful information like `stars` are not present here.

What do you think of adding GitHub repository data when requesting projects from a certain author?

**Comment by andrew** [comment]
Just added the missing `stars` and `forks` counts to that endpoint, should return the same data as everywhere else now 👍

**Comment by zenorocha** [comment]
Awesome! Works perfectly for all endpoints I'm using 🎉
