### ISSUE TITLE
New endpoints that bundles packages by `repository_url`

### ISSUE THREAD

**Issue by zenorocha** [librariesio/libraries.io#629]
In order to build the "most popular" section on https://customelements.io homepage, I need to sort the 3 most starred packages. I could use the https://libraries.io/api/search?q=&platforms=bower,npm&keywords=web-components&per_page=3&sort=stars endpoint but the problem is that it shows the same repository from different package managers.

The same problem happens when building the repository page (https://customelements.io/airyland/vux/). I don't need two separate pages just because the same repo is hosted on two different package managers. I would prefer to have only one page with instructions on how to install depending on what package manager you use.

What do you think of having endpoints that bundles packages by `repository_url`?

Something like...

```js
{
	full_name: "allmobilize/amazeui",
	stargazers_count: 123,
	...
	packages: {
		bower: {
				name: "amazeui",
				platform: "Bower",
				description: "The first crossing screen front-end framework in China, for developing mobile first, responsive web projects.",
				homepage: "http://amazeui.org",
				repository_url: "https://github.com/allmobilize/amazeui",
				normalized_licenses: ["MIT"],
				rank: 12,
				latest_release_published_at: "2016-05-24T02:07:39.000Z",
				latest_release_number: "v2.7.0",
				keywords_array: [
					"css",
					"js",
					"less",
					"mobile-first",
					"responsive",
					"front-end",
					"framework",
					"web",
					"web-components"
				],
				language: "CSS",
				status: null,
				package_manager_url: null,
				stars: 7251,
				keywords: [
					"css",
					"js",
					"less",
					"mobile-first",
					"responsive",
					"front-end",
					"framework",
					"web",
					"web-components"
				],
				versions: []
			}
		},
		npm: {...}
	}
}
```

**Comment by andrew** [comment]
That's a tricky one, unlike bower, not every npm package has a github repository associated with it, it could be published on bitbucket, gitlab or no-where so grouping by repository wouldn't always fix that issue.

For the repository page you can load something similar to https://libraries.io/github/airyland/vux with this endpoint: https://libraries.io/api/github/airyland/vux/projects that will load all projects referencing a github, which gets you back the vux and vux-rem packages including stars and forks count

For search, in the short term I'd suggest loading more than you need and grouping by `repository_url` on the clientside, or sorting by `rank` which looks at more than just github stars but actually how many projects depend on that library, but that will tend towards showing npm packages as the dependency graph is much bigger than on bower.

**Comment by andrew** [comment]
Example of what those top three would look like if sorted by rank: https://libraries.io/search?q=&keywords=web-components&per_page=3&sort=rank

![screen shot 2016-06-13 at 6 59 34 am](https://cloud.githubusercontent.com/assets/1060/15998223/66e19840-3134-11e6-9e65-13027522e934.png)

**Comment by zenorocha** [comment]
Sounds good. I'll try working with the suggestions you made ;)

**Comment by zenorocha** [comment]
When searching for a term the same repository can show multiple times too:

<img width="1204" alt="screen shot 2016-06-13 at 9 23 55 pm" src="https://cloud.githubusercontent.com/assets/398893/16031185/3da18cd2-31ad-11e6-916f-21ceb641f518.png">

So here I would have to group by `repository_url` as well. But what if the same repo is located on another page? Do you have a suggestion on how to avoid duplicated results?

**Comment by andrew** [comment]
Added a new endpoint for search github repos, allows filtering by keywords and platforms, I think you want something like this: https://libraries.io/api/github/search?keywords=web-components,polymer&platforms=NPM,Bower&sort=stargazers_count
