### ISSUE TITLE
Include latest_stable_release to project api responses

### ISSUE THREAD

**Issue by andrew** [librariesio/libraries.io#635]
Dependent on #634

**Comment by pketh** [comment]
this seems to be working now:
I'm able to get this info with `package.latest_stable_release.number`

Thanks Andrew!

**Comment by STRd6** [comment]
It looks like this is in for the exact lookups like https://libraries.io/api/npm/express, but still missing from the search results for queries like https://libraries.io/api/search?q=express&platforms=npm

![image](https://cloud.githubusercontent.com/assets/18894/19899259/b54f1e7e-a01c-11e6-9b64-1e4f2b1aeb30.png)

**Comment by pketh** [comment]
The problem that this causes for HyperDev is that when you search for a package and add it, we're not able to give you the latest stable version - we have to give you the latest instead which might be unstable :(

**Comment by andrew** [comment]
Will get that added for you this evening after :poodle: training

**Comment by pketh** [comment]
Sounds like a rich full day :) Thanks!

**Comment by andrew** [comment]
Also, incase you didn't see the news yet: https://medium.com/@teabass/libraries-io-joins-brave-new-software-c8cb7bba93bf

**Comment by pketh** [comment]
Wow I had no idea, congrats! I'll float the idea of contributing up the chain, also are you still gonna have business sponsors?

**Comment by andrew** [comment]
Absolutely, in fact sponsorship via Brave New Software is tax deductible as it's a charity 🎉

**Comment by andrew** [comment]
@pketh @STRd6 Just deployed that, `latest_stable_release` should be available in the project search api responses now.
