### ISSUE TITLE
Add the ability to exclude results from API calls

### ISSUE THREAD

**Issue by zenorocha** [librariesio/libraries.io#647]
As a owner of an open source discoverability tool which relies on package managers keywords, I find many many results which abuse the use keywords. Package authors include keywords that don't match the reality in order to increase the chances of being found but that's not cool.

I thought about building this kind of filter on the client-side but pagination wouldn't work.

My idea is to add an `exclude` parameter where I could pass a list of repositories to be removed from results. What do you think?

**Comment by andrew** [comment]
Moving this to the [Backlog](https://github.com/librariesio/libraries.io/blob/master/Backlog.md) as we'd still like to implement it but can't see that happening in the near future.
