### ISSUE TITLE
Add platforms filter on GitHub author's projects endpoint

### ISSUE THREAD

**Issue by zenorocha** [librariesio/libraries.io#648]
Is it possible to add the `platforms` filter to this endpoint?

https://libraries.io/api/github/amazeui/projects?keywords=web-components,polymer

That way I could get only Bower and NPM results when requesting

https://libraries.io/api/github/amazeui/projects?keywords=web-components,polymer&platforms=NPM,Bower

Thanks!

**Comment by andrew** [comment]
Moving this to the [Backlog](https://github.com/librariesio/libraries.io/blob/master/Backlog.md) as we'd still like to implement it but can't see that happening in the near future.
