### ISSUE TITLE
Filter packages by dependency version

### ISSUE THREAD

**Issue by zenorocha** [librariesio/libraries.io#650]
If #649 is implemented, it would be SUPER awesome to be able to search packages by dependency version. And semver could be used as the range resolution.

> http://semver.npmjs.com/
> https://semver.mwl.be
> https://docs.npmjs.com/misc/semver#Ranges

**Comment by zenorocha** [comment]
For example: https://libraries.io/api/github/search?q=scroll&platforms=npm&depends=react>15.0.0 or https://libraries.io/api/github/search?q=scroll&platforms=bower&depends=polymer^1.0.0

**Comment by andrew** [comment]
Moving this to the [Backlog](https://github.com/librariesio/libraries.io/blob/master/Backlog.md) as we'd still like to implement it but can't see that happening in the near future.
