### ISSUE TITLE
Wordpress.org url parsing

### ISSUE THREAD

**Issue by andrew** [librariesio/libraries.io#74]
POST `http://api.wordpress.org/plugins/info/1.0/`
body:
`action=query_plugins&request=O%3A8%3A%22stdClass%22%3A3%3A%7Bs%3A6%3A%22browse%22%3Bs%3A3%3A%22new%22%3Bs%3A8%3A%22per_page%22%3Bi%3A100%3Bs%3A4%3A%22page%22%3Bi%3A1%3B%7D`

slug regex `/"slug";s:[0-9]+:"([^"]+)";/`

Load individual: `https://api.wordpress.org/plugins/info/1.0/imoneza.json`

**Comment by BenJam** [comment]
ERR: language != human.
