### ISSUE TITLE
NPM keywords parsing when specified as a single comma-separated string

### ISSUE THREAD

**Issue by knolleary** [librariesio/libraries.io#740]
In a node modules's `package.json` file, the author can specify a set of keywords. The expectation is they provide an array of individual keywords:

```
keywords: [
   "one",
   "two",
   "three"
]
```

I have spotted a package file in the wild where the user has provided their keywords as a comma-separated string within the keyword array: https://github.com/dexterlabora/node-red-contrib-meraki-cmx/blob/c0e0d59c886e13c927c168501ae6f98e2b5c19e3/package.json#L15

```
keywords: [
   "node-red, meraki, cmx"
]
```

On the [npmjs.org page for the module](https://www.npmjs.com/package/node-red-contrib-meraki-cmx), it appears some attempt has been made to parse that string and treat them as three separate keywords:

<img width="180" alt="node-red-contrib-meraki-cmx" src="https://cloud.githubusercontent.com/assets/51083/17157687/e36f04bc-5388-11e6-927a-c0e9303fb654.png">

Although that reveals they are doing a crude split on comma and not trimming the whitespace as the links for `"meraki"` and `"cmx"` are actually to the pages for `" meraki"` and `" cmx"`.

The [docs for the keywords section of `package.json`](https://docs.npmjs.com/files/package.json#keywords) are fairly comprehensive on this subject:

> Put keywords in it. It's an array of strings. This helps people discover your package as it's listed in npm search.

But given that npmjs.org makes some sense to do the right thing, it may be useful for libraries.io to follow suit (although if you chose to trim whitespace, I wouldn't object).

**Comment by andrew** [comment]
Good spot, will trim the whitespace ;)
