### ISSUE TITLE
Get total counts for certain APIs?

### ISSUE THREAD

**Issue by zeke** [librariesio/libraries.io#744]
Kind of a followup to https://github.com/librariesio/libraries.io/pull/743

We're using the `dependent_repositories` API. Is there a way to find out the total number of results, so we know when to stop paginating? We're current just using a really big number and hoping for the best. 🙈

**Comment by andrew** [comment]
<img width="905" alt="screen shot 2016-07-28 at 1 48 30 pm" src="https://cloud.githubusercontent.com/assets/1060/17223397/5c6845a8-54ca-11e6-83af-347426c2c6fa.png">

Check out the `Total` header, will give you the count of the whole list without having to paginate, you can also get that using a `per_page` of 1 to speed things up if you just need the total

**Comment by zeke** [comment]
cc @jlord and cc @pengwynn who long ago taught me this trick for the GitHub API. :)

**Comment by zeke** [comment]
We are not seeing a `Total` header for this request:

```
curl -i "https://libraries.io/api/npm/electron-prebuilt/dependents/?api_key=7c4111e91e0814d8b9922a8b6b05d5d6&page=1&per_page=1"
```

**Comment by andrew** [comment]
Believe I have fixed this for you, can you confirm?

**Comment by zeke** [comment]
Now seeing a total of 30, which doesn't seem right:

```
curl -i -s "https://libraries.io/api/npm/electron-prebuilt/dependents/?per_page=1" | grep Total
Total: 30
```

**Comment by andrew** [comment]
Fixed, returns the correct value in the total now, sorry about that!

**Comment by zeke** [comment]
Works. Thanks!
