### ISSUE TITLE
Home page package manager links clickable

### ISSUE THREAD

**Issue by royka** [librariesio/libraries.io#755]
Can we make these links clickable? I guess they would just take you to the platform page

i.e. bower link would go to https://libraries.io/bower

![screen shot 2016-08-03 at 16 51 44](https://cloud.githubusercontent.com/assets/1868592/17372195/aee71b72-599a-11e6-9a6a-3cb1c9d12f73.png)

**Comment by royka** [comment]
I'll do the work if we think its a good idea :)

**Comment by andrew** [comment]
🚢
