### ISSUE TITLE
Allow users to curate their own 'collections'

### ISSUE THREAD

**Issue by andrew** [librariesio/libraries.io#76]
Something like https://github.com/showcases but for any user to make or collaborate on, like http://lanyrd.com/guides/

**Comment by BenJam** [comment]
Possibly a good lead in to #20

**Comment by andrew** [comment]
Moving this to the [Backlog](https://github.com/librariesio/libraries.io/blob/master/Backlog.md) as we'd still like to implement it but can't see that happening in the near future.
