### ISSUE TITLE
Add support for Bintray JCenter

### ISSUE THREAD

**Issue by mhurne** [librariesio/libraries.io#760]
Per https://bintray.com/bintray/jcenter,

> JCenter is the place to find and share popular Apache Maven packages for use by Maven, Gradle, Ivy, SBT, etc.

Some open source projects in the Java ecosystem have chosen to publish builds to JCenter _instead_ of Maven Central. Unfortunately, such projects are not currently represented in libraries.io

Since JCenter provides a "just another Maven repository" interface to build tools such as Maven and Gradle, perhaps including it in libraries.io can heavily leverage the work done to support Maven Central?

**Comment by andrew** [comment]
At the moment Maven Central makes it pretty hard to get data out of, so I'm using https://maven-repository.com/ as the list of packages at the moment which might mean there's no existing work that can be used to integrate jcenter but it would be great to add support for it.

At the moment Libraries's Maven support doesn't know about multiple sources so that'll need to be added, also do you know of any API for JCenter to get meta data about it's packages?

**Comment by mhurne** [comment]
I don't think JCenter has an API of its own, but Bintray definitely does: https://bintray.com/docs/api/

You can think of JCenter as one instance of a Maven repo in Bintray. I'm not at all familiar with the Bintray API, but perhaps it could be used to deal with packages in JCenter while ignoring packages in other Bintray repositories.

**Comment by andrew** [comment]
That REST API looks like it will most of what's needed, but the 300 req/day rate limit is a killer, might need to get a Silver account to be able to do the first download of everything from there.

**Comment by mhurne** [comment]
Hmm, yeah - perhaps there's justification for them to make an exception for this case, since libraries.io revolves around open source projects.

**Comment by mhurne** [comment]
For giggles, a couple of example API calls:

```
➜  ~ curl -X GET -ufoo:bar https://api.bintray.com/repos/bintray/jcenter/packages | jq .
...
[
  ...
  {
    "name": "accessibilitools",
    "linked": true
  },
  {
    "name": "accesspoint",
    "linked": true
  },
  ...
]

➜  ~ curl -X GET -ufoo:bar https://api.bintray.com/packages/bintray/jcenter/accesspoint | jq .
...
{
  "name": "accesspoint",
  "repo": "maven",
  "owner": "mvdan",
  "desc": "Manage wireless access points in Android",
  "labels": [
    "access point",
    "android",
    "wifi"
  ],
  "attribute_names": [],
  "licenses": [
    "Apache-2.0"
  ],
  "custom_licenses": [],
  "followers_count": 0,
  "created": "2015-05-15T23:50:27.232Z",
  "website_url": "",
  "issue_tracker_url": "",
  "linked_to_repos": [
    "jcenter"
  ],
  "permissions": [],
  "versions": [
    "0.2.0",
    "0.1.3",
    "0.1.2",
    "0.1.1",
    "0.1.0"
  ],
  "latest_version": "0.2.0",
  "updated": "2016-01-27T14:01:41.690Z",
  "rating_count": 0,
  "system_ids": [
    "cc.mvdan.accesspoint:library"
  ],
  "vcs_url": "https://github.com/mvdan/accesspoint",
  "maturity": ""
}
```

**Comment by andrew** [comment]
Excellent, that's very nicely formatted, should make it easy to add once I've added the ability to index multiple maven repositories

**Comment by andrew** [comment]
Moving this to the [Backlog](https://github.com/librariesio/libraries.io/blob/master/Backlog.md) as we'd still like to implement it but can't see that happening in the near future.
