### ISSUE TITLE
URL is parsed incorrecly

### ISSUE THREAD

**Issue by No9** [librariesio/libraries.io#761]
Hi all 
Just noticed git repositories from subdomains (it may be more wide spread) 
are getting messed up a little on the package page 

i.e. https://libraries.io/npm/apiconnect  
Is - **Repository:** https://github.com/github.ibm.com:apiconnect/apiconnect
When it should be - **Repository:** https://github.ibm.com/apiconnect/apiconnect

Hope this helps and please ping if you need more info. 

Love as always 
@no9 xxx

**Comment by andrew** [comment]
Have stopped it mangling the url, just shows the original from package.json now and stops Libraries.io thinking it's a github.com url, thanks for reporting @No9!
