### ISSUE TITLE
Deal with change of repo for a package (npm/dropbox issue)

### ISSUE THREAD

**Issue by bengourley** [librariesio/libraries.io#829]
It looks like at some point dropbox flipped the repo of their [js sdk package on npm](https://www.npmjs.com/package/dropbox) from https://github.com/dropbox/dropbox-js to https://github.com/dropbox/dropbox-sdk-js. The old repo now contains a deprecated warning.

On libraries.io the [package page](https://libraries.io/npm/dropbox) still picks up the readme from the old repo and as a result libraries.io marks the current `npm/dropbox` library as deprecated, which is not correct.

**Comment by andrew** [comment]
Fixed 🆗
