### ISSUE TITLE
Some newly published versions not appearing (npm/github)

### ISSUE THREAD

**Issue by bengourley** [librariesio/libraries.io#830]
![screen shot 2016-10-13 at 09 58 00](https://cloud.githubusercontent.com/assets/609579/19342860/8e1a475c-912b-11e6-8495-44d8ce47008f.png)

For instance, `eslint-config-standard` v6.2.0 was published 14 days ago. Could this be just a backed up job, or has libraries.io missed it?

**Comment by andrew** [comment]
It must have missed or errored on that one, I've synced it now

**Comment by bengourley** [comment]
- will it take a while for [this page](https://libraries.io/npm/standard) to update?
- do you think we should show the ⚠️  sign when `requirement version > latest release`? I'm tempted to say that in general if that is the case, libraries just hasn't picked up the latest release yet… what do you think?

**Comment by andrew** [comment]
yeah that's a bug, often comes up where the dependency tables are aggressively cached

**Comment by andrew** [comment]
Just deployed a fix for the aggressive caching and have scheduled an update for all npm modules that haven't been synced in the past 4 weeks

**Comment by andrew** [comment]
> do you think we should show the ⚠️ sign when requirement version > latest release? I'm tempted to say that in general if that is the case, libraries just hasn't picked up the latest release yet… what do you think?

@bengourley can you open a separate issue for that?
