### ISSUE TITLE
Check logic for marking a dependency as outdated

### ISSUE THREAD

**Issue by bengourley** [librariesio/libraries.io#831]
[Extracted from #830]

Do you think we should show the ⚠️  sign when requirement `version > latest release`? I'm tempted to say that in general if that is the case, libraries just hasn't picked up the latest release yet…

I see two options:

1. Display nothing, just let it have a version mismatch until the page is *hopefully* eventually consistent
2. Display a less visually alarming icon and popover that says something to the effect of: "The version specified hasn't been picked up by Libraries.io yet. Either it has been published and will eventually appear, or it is possible that the specified version doesn't actually exist. In the latter case, you have a problem!"

**Comment by andrew** [comment]
@bengourley I've just shipped a tweak to the `outdated?` dependency method that doesn't complain if the dependency requires a new version than libraries knows about, basically option 1 🚢

**Comment by bengourley** [comment]
Sweet! 🦄
