### ISSUE TITLE
Can't login, bad url on the button

### ISSUE THREAD

**Issue by whit537** [librariesio/libraries.io#838]
### Steps to Reproduce

1. Visit https://libraries.io/.
1. Click "Login" at upper right.

### Expected

Log in! 💃 

### Actual

Get sent to https://librariesio-app-servers/auth/github. 😖 

![screen shot 2016-10-19 at 2 37 21 pm](https://cloud.githubusercontent.com/assets/134455/19532407/8f9abb4c-9609-11e6-8250-4d150f3944ee.png)

**Comment by andrew** [comment]
Ah sorry about that, I made some server config changes today, I've fixed that up now, can you try and login with github again?

**Comment by whit537** [comment]
All set, thank you! 💃
