### ISSUE TITLE
Add an API for "resolved transitive dependency tree for any version of any library"

### ISSUE THREAD

**Issue by whit537** [librariesio/libraries.io#839]
Picking up from [Twitter](https://twitter.com/teabass/status/788827835855175682) ...

This would be super-helpful to us in https://github.com/gratipay/gratipay.com/pull/4135.

**Comment by andrew** [comment]
Dependent on #864

**Comment by andrew** [comment]
@whit537 just shipped https://github.com/librariesio/libraries.io/pull/907 :shipit:

**Comment by whit537** [comment]
Awesome, thanks @andrew! 💃
