### ISSUE TITLE
Yarn dependencies still appear/alert after removal of yarn.lock

### ISSUE THREAD

**Issue by kpfefferle** [librariesio/libraries.io#867]
I've removed `yarn.lock` from some of my GitHub repos to reduce the number of email alerts I get, but I still seem to be getting alerted for the sub-dependencies of these projects. The Yarn dependencies also remain listed in the web interface for these repos.

Here are a few examples to demonstrate the issue:

https://github.com/kpfefferle/ember-cli-deploy-cloudfront
https://github.com/kpfefferle/ember-octicons
https://github.com/kpfefferle/liquid-fire-reveal

**Comment by andrew** [comment]
Just deploy a fix for that now, will resync those three repos for you once it's live.

**Comment by andrew** [comment]
Synced and yarn.lock files removed 🚢
