### ISSUE TITLE
Sanitize & Standardize Website Addresses

### ISSUE THREAD

**Issue by bdkjones** [librariesio/libraries.io#869]
Some entries on Libraries.io appear to have malformed `website` properties. Here, for example, is the entry for `semantic-grid` (a Bower component): 

<img width="494" alt="screen shot 2016-11-04 at 13 50 01" src="https://cloud.githubusercontent.com/assets/926566/20022448/e3f88e9a-a297-11e6-9175-df4d06c449aa.png">

The `website` property is missing a scheme. `http://` or `https://`. Note that `url` is correct, but `website` is not.

**Comment by andrew** [comment]
Moving this to the [Backlog](https://github.com/librariesio/libraries.io/blob/master/Backlog.md) as we'd still like to implement it but can't see that happening in the near future.
