### ISSUE TITLE
Still on versions

### ISSUE THREAD

**Issue by drAlberT** [librariesio/libraries.io#895]
@andrew  there should still be some issue as dependency are reported "out-of-date" in composer.lock but not in composer.json, moreover the "stable release" indicated is a "`-dev`" ..

Please investigate

Relted to #877

![screen shot 2016-11-14 at 09 24 57](https://cloud.githubusercontent.com/assets/1442700/20257789/3e1d9954-aa4c-11e6-99f6-7a41ec660db1.png)

**Comment by andrew** [comment]
Which repo is that showing on?

**Comment by drAlberT** [comment]
- [faktiva/php-redis-admin](https://github.com/faktiva/php-redis-admin)
- [faktiva/php-admin-tk](https://libraries.io/github/faktiva/php-admin-tk)

On same repos I can only see `composer.json` on libraries.io .. even if .lock is committed too:
- [faktiva/prestashop-seo-tk](https://github.com/faktiva/prestashop-seo-tk)

**Comment by andrew** [comment]
Just shipped a fix for this, `3.1.x-dev` isn't a valid semver number so it wasn't considered as a `prerelease` which is then used to work out the latest stable releases 😬

**Comment by drAlberT** [comment]
@andrew uhmm .. and what about project not having `composer.lock` displayed even if it has been committed (yes it is probably out-dated) ???

**Comment by andrew** [comment]
@drAlberT ah I missed that extra bug you snuck in there, investigating now.

**Comment by andrew** [comment]
@drAlberT have opened an issue here: https://github.com/librariesio/librarian-parsers/issues/54

**Comment by andrew** [comment]
@drAlberT Fixed that now, good spot! 

Will have to resync 77,486 `composer.lock` files from GitHub now to pick up all the missing dependencies!

**Comment by drAlberT** [comment]
Ok, but I think there is still an issue:

![screen shot 2016-11-14 at 12 47 17](https://cloud.githubusercontent.com/assets/1442700/20263845/bd2ec8e6-aa68-11e6-8509-27a6b97df5a8.png)


AFAIK `composer.json` is **not** out-of date .. of course it is `composer.lock` 

Only `composer.lock` section should report issues in this example IMHO

**Comment by drAlberT** [comment]
uhmmm.. my bad .. I have to substitute ~ with ^ I suppose .. please confirm ;)

**Comment by andrew** [comment]
I don't know the implementation of `~` range in composer, will have to check but there is a bug in ruby projects where `~` don't resolve to the correct range as the implementation is different to npm, i will add it to https://github.com/librariesio/libraries.io/issues/337 to investigate
