### ISSUE TITLE
Tilde is not processed correctly

### ISSUE THREAD

**Issue by Jean85** [librariesio/libraries.io#913]
I've found this wrong warning sign on my library:

https://libraries.io/packagist/facile-it%2Fparaunit-testcase

![schermata del 2016-11-22 10-35-58](https://cloud.githubusercontent.com/assets/6729988/20518525/c52336c6-b09f-11e6-8bd1-9b89c7a9b758.png)

The requirement is `~1.3`, so latest stable `1.6.x` is compatible, but it's shown as outdated.

**Comment by andrew** [comment]
Also affects rubygems (https://github.com/librariesio/libraries.io/issues/337), will need to be fixed in https://github.com/librariesio/semantic_range

**Comment by andrew** [comment]
Closing this as a dupe of #337

**Comment by andrew** [comment]
@Jean85 just deploying a fix for this now
