### ISSUE TITLE
Tweet about new projects

### ISSUE THREAD

**Issue by andrew** [librariesio/libraries.io#93]

**Comment by BenJam** [comment]
A la http://githubcom/24pullrequests/tweets

**Comment by andrew** [comment]
Can basically use the whole projects but swap the firehose url in https://github.com/24pullrequests/tweets/blob/master/index.js#L4 for `http://firehose.libraries.io/events`

**Comment by andrew** [comment]
Moving this to the [Backlog](https://github.com/librariesio/libraries.io/blob/master/Backlog.md) as we'd still like to implement it but can't see that happening in the near future.
