### ISSUE TITLE
Usage percentage sum inconsistency.

### ISSUE THREAD

**Issue by jdalton** [librariesio/libraries.io#931]
I noticed on the [lodash bower usage](https://libraries.io/bower/lodash/usage) that the percentages shown total ~77% which leaves 23% missing and [lodash npm usage](https://libraries.io/npm/lodash/usage) totals ~65% leaving 35% missing.

**Comment by andrew** [comment]
@jdalton at the moment it's showing the top 18 groups, which leaves out most of the long tail of small usage of a lot of different versions, I'm going to add an "other" column that shows the details for the rest of the total

**Comment by andrew** [comment]
Just deploying a fix for this now that adds an "Other" column in.

**Comment by andrew** [comment]
![screen shot 2016-12-16 at 3 37 03 pm](https://cloud.githubusercontent.com/assets/1060/21268196/8a4141f6-c3a5-11e6-9d22-7964f0e9d474.png)

🚢

**Comment by jdalton** [comment]
Rock!

Is "latest" the actual entry "latest" or like `4.17.whatever`? 
From the look of the chart are things like "^4.6.1" packages with that exact range entry or is it those that fall within that range?

When I look at things like this I'm usually curious of the uptake of a version range. Like how well my current major version adoption is doing to previous versions. The way it currently is displayed it's hard to get that. I see high "^3.10.1" usage but that makes sense as it was the last v3 release. Since  v4 is still being updated update on a single point release will be lower as it keeps shifting.

**Comment by andrew** [comment]
All values are exactly as specified in `package.json` files on GitHub, there's no semver grouping going on on this page at the moment.

I've been thinking about making the raw counts available in the API so you could group by semver ranges yourself to see the usage data you're after?

**Comment by jdalton** [comment]
Nice!

Side note on this issue it looks like the "other" bar isn't scaled right as it, which is 35%, is nearly the same height as another with 11%.

**Comment by andrew** [comment]
@jdalton right, I didn't want it to be to scale as I figured it would dwarf the other bars on some very big, long running projects. 

Have got plans for a bit of a redesign to make it work better for those projects: https://github.com/librariesio/libraries.io/issues/930
