### ISSUE TITLE
Usage stats include github forks?

### ISSUE THREAD

**Issue by jdalton** [librariesio/libraries.io#934]
Do usage numbers include forks of repos?

**Comment by andrew** [comment]
@jdalton they do include some forks but Libraries doesn't download most forks from github. Going to stop including usage data from forks in https://github.com/librariesio/libraries.io/pull/971

**Comment by andrew** [comment]
With forks:

<img width="1204" alt="screen shot 2016-12-07 at 11 09 14 am" src="https://cloud.githubusercontent.com/assets/1060/20966028/582dcfb8-bc70-11e6-8f9d-db9d984b53da.png">

Without forks:

<img width="1145" alt="screen shot 2016-12-07 at 11 28 39 am" src="https://cloud.githubusercontent.com/assets/1060/20966035/6053c58a-bc70-11e6-9281-c5791308d880.png">

**Comment by jdalton** [comment]
Nice!

It's interesting to see for sure. There seems to be a disconnect between github repos and those packages published to the npm registry. For example using [npmrank](https://github.com/anvaka/npmrank)

```bash
node countVersions.js lodash --semver="^4.0.0"
```
will report total public regular dependents as 13,200

and

```bash
node countVersions.js lodash --semver="^3.0.0"
```
will report total public regular dependents as 10,474

**Comment by andrew** [comment]
@jdalton this data isn't for npm modules depending on other modules and their versions, it's just from open source github repositories that have a package.json, so that's end user applications and the master branches of modules.

I have the data to be able to do a similar page for the version ranges of modules that have been published, similar to what npmrank does if that would be helpful?

**Comment by jdalton** [comment]
> I have the data to be able to do a similar page for the version ranges of modules that have been published, similar to what npmrank does if that would be helpful?

If it's easy, then yeah, I dig charts (and others do too I'm sure).

**Comment by andrew** [comment]
@jdalton made a new issue for that over here so I don't forget: https://github.com/librariesio/libraries.io/issues/973
