### ISSUE TITLE
URL path related issues for the new `dependency-issues` feature

### ISSUE THREAD

**Issue by d2s** [librariesio/libraries.io#955]
Noticed a small URL-redirection related issue.

When trying to view content from a recent feature, it was not possible to open page where GitHub organisation’s name was written in lowercase.

```
https://libraries.io/github/microsoft/dependency-issues
                            vs.
https://libraries.io/github/Microsoft/dependency-issues
```

Looks similar, but the first URL goes to `https://libraries.io/github/Microsoft`
instead of the right location.

**Comment by andrew** [comment]
@d2s just deploying a fix for this now, good spot!
