### ISSUE TITLE
Add 'supported by' notice to /about

### ISSUE THREAD

**Issue by BenJam** [librariesio/libraries.io#958]
I think it's right to include a supporters section/notice reflecting individual grantors to the /about page. In addition there *might* be a contractual obligation to include Brave New Software as the fiscal sponsor, which I will confirm asap.

**Comment by andrew** [comment]
Was also going to put it in the footer: https://github.com/librariesio/libraries.io/issues/850

**Comment by BenJam** [comment]
Closing in favour of #850
