### ISSUE TITLE
Total package install size in the "Project Statistics"?

### ISSUE THREAD

**Issue by jthomas** [librariesio/libraries.io#987]
Would it be possible to show total package install size in the "Project Statistics"? This would be the sum of the package and all the dependencies that would end up being downloaded.

I use Libraries.io to compare packages on NPM as I prefer using packages with fewer dependencies. As well as the number of dependencies, it'd also be really useful to see how large the combined package install will be to help me evaluate packages.

I'm not sure if this is possible or practical but I think it would be useful feature. I had a look through the Issues list but couldn't see anything related.

**Comment by andrew** [comment]
Yeah I definitely want to do this, dependent on https://github.com/librariesio/libraries.io/issues/46 and https://github.com/librariesio/libraries.io/issues/35 although could make HEAD requests for the tarballs to get the gzipped size in the short term

**Comment by andrew** [comment]
Moving this to the [Backlog](https://github.com/librariesio/libraries.io/blob/master/Backlog.md) as we'd still like to implement it but can't see that happening in the near future.

**Comment by camUrban** [comment]
Is there any movement on this? I see that it's still in the backlog a few years later. Do you see this changing?
